<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/2fighters3.htm">二人の戦士アル＆レイ 第３話　協力者の誤算</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/7/6(日)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある村の周辺で魔族が出没すると言う情報を得たアルとレイは先に依頼を受けていたジルという男に協力を申し出た。ジルはその提案を承諾したがある条件をつけて……<BR><B>【コメント】 </B>今回はいろんな意味で誤算でした。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>的確に敵を倒すために、自らの身に与える苦痛を承知で雷撃を放ち、耐え抜いたレイ。彼女らは、最高レベルの戦士だ、間違いなく。<BR>
<B><A HREF="../novel/200210/28213920/2fighters1.htm">【第一話はこちら】</A><A HREF="../novel/200210/28213920/2fighters2.htm">【第二話はこちら】</A></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 アクション ファンタジー <BR>【種別】 変身 魔法<BR>【キーワード】 出会い 戦い 女戦士二人旅(笑)</TD></TR></TABLE><BR><BR>『ライターマン』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/otome1.htm">乙女くん（前編）</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/7/11(火)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、目を覚ますと俺の身体は……そのとき俺は学校に伝わる話を思い出した。<BR><B>【コメント】 </B>ある日突然こんなことになったらそりゃあパニックになるでしょうが……主人公はどんどんドツボにはまっていきます（笑）<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200011/03192112/easy_come_easy_go.html">ＥＡＳＹ ＣＯＭＥ ＥＡＳＹ ＧＯ</A> <FONT SIZE="-1">(十郎太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>４年に一度の『乙女現象』。はたして、省太くんの１ヶ月後の運命やいかにっ！　……って、何でしょう皆様？　その期待に満ち満ちた視線は（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 神秘 変身<BR>【キーワード】 伝説 学校 よろこぶ母（笑） タブー</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/bouken.htm">冒険者たち</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/6/11(日)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>トレジャーハンター、それは世界の各地に眠る財宝を求めて飛び回る現代の冒険者。これは伝説となったトレジャーハンターとそのパートナーのお話？<BR><B>【コメント】 </B>冒険、してみます？<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/light_light/title.html">ライト・ライト・ストーリー</A> <FONT SIZE="-1">(ＫＥＢＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>命懸けで財宝を求める冒険者たち。……しかし、冒険の代償が命でなく“アレ”だったら？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 神秘 変身<BR>【キーワード】 冒険 遺跡 トラップ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/kakurenbo.html">別れの日</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/5/27(土)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>今日を最後に僕という存在は消える。この町から、そして世界から。そのとき、僕の目の前に現われたのは……<BR><B>【コメント】 </B>　”【天体観測】〜子供だった頃〜”を読んでちょっと作ってみました。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/fullmoon.html">ＦＵＬＬ　ＭＯＯＮ　ＮＩＧＨＴ</A> <FONT SIZE="-1">(ＢＡＣＫＢＯＮＥさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>かくれんぼでいつも見つけてもらうって、実はかなりうれしいことなのかもしれません。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 ボクっ娘 幼馴染み</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/valkyrie04.htm">機甲天女ヴァルキュリア Scramble4：「爆裂！！　一瞬に全てをかけて」</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/5/7(日)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ヴァルキュリアのパイロットになって初めての夜間待機、時間を持て余し気味だった石野に羽谷野が持ちかけた話とは？<BR><B>【コメント】 </B>気をつけよう、暗い夜道と甘い話（爆）。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200109/21035514/kizuna.html">絆</A> <FONT SIZE="-1">(樹遠零さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ヴァルキュリアパイロット羽谷野美姫、その秘められた能力と過去に迫るっ（……笑）。<BR>
<b><a href="../novel/200210/28213920/valkyrie01.htm">【Scramble1はこちら】</a><a href="../novel/200210/28213920/valkyrie02.htm">【Scramble2はこちら】</a><a href="../novel/200210/28213920/valkyrie03.htm">【Scramble3はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション <BR>【種別】 テクノロジー 変身<BR>【キーワード】 ロボット 侵略</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/kahun.htm">厄介な季節</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/4/4(火)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある朝、目を覚ました俺は身体に異変を感じた。それから始まる厄介な季節の日々……<BR><B>【コメント】 </B>春、それは○○○の季節（爆）？<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/tr_gals/title.html">生命戦隊トランスギャルズ</A> <FONT SIZE="-1">(矢治浩平さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>○○○、厄介ですよね（笑）。毎年この時期になると耳鼻科に行って、先生に「や〜今年もまた来ましたね」なんて笑顔で言われた日には……まあとにかく、特殊（笑）な○○○に苦しむひとりの男性社員のお話。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 変身</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/kanata.htm">彼方より</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/3/22(水)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>大学からの帰り道、雑木林で俺は倒れていた子供を発見した。だがそいつは彼方からやってきた来訪者で……<BR><B>【コメント】 </B>これは時代と世代を超えた男と男の友情の物語……な訳ありません（爆）。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200202/03004409/heart01.html">ハートのペンダント</A> <FONT SIZE="-1">(Marieさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>時の輪が閉じる時、運命の転轍器が切り替わる……ライターマンさんのハートウォーミングなＳＳです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 天才 タイムスリップ 暴走する従姉弟（爆）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/dotabata.htm">入れ替わり騒動記</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/1/28(土)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>体験学習の帰り道、俺たちの乗ったバスは事故に遭い横転した。そしてそこは不思議な伝説のある場所だった。<BR><B>【コメント】 </B>入れ替わりも２、３人ならかわいげがあるんですが……<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/200209/19204751/borderless.htm">ボーダーレス</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そして伝説は終わり、歴史が始まる……（違）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 入れ替わり 神秘 変身<BR>【キーワード】 伝説 みんなで替われば怖くない？ 地蔵</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/realize.htm">成就</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/1/20(金)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>アベックで賑わう恋愛成就で有名な元旦の神社。「今年こそ恋人が出来ますように」と願った俺は……<BR><B>【コメント】 </B>世の中はた迷惑な神が多すぎます(笑)。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200103/11203206/sotu.html">卒業</A> <FONT SIZE="-1">(風祭玲さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ちょっと時期が過ぎちゃいましたけど、初詣のお話。それにしても、あっちこっちに被害者（？）というか……（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 初詣</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/bracelet.htm">誓いの腕輪</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/1/13(金)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺は最近、考古学を専攻している麻衣子にぞっこんである。ある日俺が麻衣子の作業場所に行ってみると……<BR><B>【コメント】 </B>くれぐれも人の物を勝手に扱うことはしないようにしてくださいね(笑)。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200109/15004009/daily_life1.html">DAILY LIFE</A> <FONT SIZE="-1">(ふらっとさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>入れ替わりものの要素が加味された、コミカル（？）な変身譚です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 アイテム</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/manly.html">男らしく</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/12/15(木)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺が目指すものは「男の中の男」だ！！　しかし何故か周囲はそれを邪魔しようとする奴が多くて……<BR><B>【コメント】 </B>まあ、こういうパターンもありかな？　と思って作ってみました。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/200209/19204751/d_upboy_title.htm">着せ替え少年〜Ｄｒｅｓｓ　ＵＰ　Ｂｏｙ〜</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どうやら、続き物ではないそうです……。でも、続きが読みたい！！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 学園 <BR>【種別】 変身<BR>【キーワード】  オレっ娘 TS熱</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/kitanokuni.htm">北の国へ</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/10/2(日)</TD><TD>50KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>私立探偵の俺は大きな事件を解決し、北海道で夏休みとしゃれこんだ。だがそこで待ち受けていたものは……（かなり誇張表現含んでいます（笑））<BR><B>【コメント】 </B>○○過ぎには注意しましょう（笑）<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/robot_triathlon/title.htm">ロボＴＲＹ美少女っ</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>北の大地を舞台に繰り広げられる、男と女（？）の物語。「文庫」初期作品の香りがする、ライターマンさんの力作です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ミステリ（？） 現代 <BR>【種別】 変身 薬品<BR>【キーワード】 親友萌え オレっ娘 女性人格化</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/valkyrie03.htm">機甲天女ヴァルキュリア Scramble3：「閃光！！　偽りの中の真実」</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/9/9(金)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ヴァルキュリアのパイロットの幾田は、ある日「特別任務」のを命じられた。だがその内容は……<BR><B>【コメント】 </B>これはわが身を犠牲にして戦う勇気ある若者たちの物語である……筈なんだけど。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200110/28050903/fushigigirl.htm">不思議な少女</A> <FONT SIZE="-1">(Ｔ．Ｈさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>幾田くん改め石野真紀ちゃん、「特別任務」であのふたりに出会います。<BR>
　それにしても、もう３０年以上前になるのか……あの作品（しみじみ）。<BR>
<b><a href="../novel/200210/28213920/valkyrie01.htm">【Scramble1はこちら】</a><a href="../novel/200210/28213920/valkyrie02.htm">【Scramble2はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション <BR>【種別】 変身 テクノロジー<BR>【キーワード】 ロボット 侵略</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/sister.htm">Oh my sister?</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/7/12(火)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺、水原恵輔と御子神純は親同士の再婚で兄弟になるはずだった。しかし一緒に暮らし始めた翌日……<BR><B>【コメント】 </B>これは運命に翻弄されながらも絆を深めていく２人の「きょうだい」の物語である……なんつって(笑)。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/short/antique.html">あんてぃーく？</A> <FONT SIZE="-1">(HIKUさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>恵輔くんと純くんで義兄妹カップルになるのかと思いきや……。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 女系一族 妹</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/valkyrie02.htm">機甲天女ヴァルキュリア Scramble2：「飛翔！！　戦いの空へ」</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/5/26(木)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>未知なる生物「インセクター」と戦うためヴァルキュリアで出撃した幾田。しかしそれにより彼の身体は女性になってしまう。戸惑う彼（女）に三枝が語るヴァルキュリアの、そしてインセクターの真実とは？<BR><B>【コメント】 </B>今回は物語の背景説明です。それと萌えも少しね（笑）。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/goddess_mask/title.html">女神仮面ミーミル</A> <FONT SIZE="-1">(ＫＥＢＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>恐るべきインセクター、その驚愕の正体とは？　そして、目覚めた幾田にさらなる運命の濁流が……！？（笑）<BR>
<b><a href="../novel/200210/28213920/valkyrie01.htm">【Scramble1はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション <BR>【種別】 変身 テクノロジー<BR>【キーワード】 ロボット 侵略</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/guragura.html">揺れる……</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/5/6(金)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「大きな地震は起きない」と思われていた地域で起きた地震。ところが災いはそれだけでなく……<BR><B>【コメント】 </B>いやあびっくりしました。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/perky_girl/perky_girl1.html">いんまなあの子はPerky☆Girl！</A> <FONT SIZE="-1">(米津さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「天災は忘れた頃にやってくる」「泣きっ面に蜂」「後悔先に立たず」を是非この作品に捧げたいと思います(笑)</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 地震 親友萌え？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/magic.html">まーじ・まじ？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/4/29(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「あたしの家って魔法使いの家系らしいのよ」最近知り合った彼女が俺にこう言った。その彼女が俺に……<BR><B>【コメント】 </B>魔法、信じますか？<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/sephi/sephi0.html">聖命樹の大地</A> <FONT SIZE="-1">(ＫＣＡさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法でとんでもないことに。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 不思議 <BR>【種別】 魔法 変身<BR>【キーワード】 オレっ娘 存在変化</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/valkyrie01.htm">機甲天女ヴァルキュリア Scramble1：「誕生！！　５人目の戦士」</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/4/23(土)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>未知なる生物「インセクター」の脅威にさらされている世界。一人の青年が東京で道に迷っていた（笑）。彼にふりかかる運命とは？<BR><B>【コメント】 </B>メカ戦だっ！！（ちょっと違うかも）<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200209/19204751/yunomachi01.html">湯の街奇談</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライターマンさん久々のメカアクションもの。「機甲天女」の秘密とは？　そして、絶体絶命の主人公の身に起こる出来事とは……？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション <BR>【種別】 変身 テクノロジー<BR>【キーワード】 ロボット 侵略</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/siranuga.htm">病気を甘く見ていると</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/4/12(火)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>仕事の締め切りに追われていた俺がある日かかった病気、それはただの病気ではなかった。とはいえ命にかかわるものじゃなかったので気にせず(？)に仕事を続けていると……<BR><B>【コメント】 </B>みなさん、健康管理はきちんとしましょう(笑)<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/rental/rb20.html">Rental　Body　Ver2.01</A> <FONT SIZE="-1">(２ｂｉｔさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>忙しいからと言ってうっかりは禁物です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 近未来？ 異世界？ <BR>【種別】  病気 変身<BR>【キーワード】 がさつな奴 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage_ex2.htm">変身美少女戦士ミラージュガール 番外編２：「雪と少女と精霊と」</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/3/22(火)</TD><TD>48KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>冬休み、不思議な夢を見た俺は礼戸と古木、そしてペルと一緒に長野のスキー場へと向かった。そこで一人の少女と出会い……<BR><B>【コメント】 </B>久しぶりのミラージュガール。お楽しみいただければ幸いです。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="../novel/200306/14163618/doki_01.htm">どきどき！　メガネっ娘くん</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>女の子として生活してるわりに男言葉がちっとも抜けない真奈美ちゃん。祐一くんとの関係も少しは進展したようで（……？）。<BR>
<b><a href="../novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ヒーロー 学園？ アクション <BR>【種別】 変身 アイテム<BR>【キーワード】 お正月 美少女戦士</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/comfortable.html">気楽にいこうよ</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/12/28(火)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、教室に入った俺はいつもと違う雰囲気に気がついた。そんな俺に話し掛けてきた友人は……<BR><B>【コメント】 </B>まあ……楽しんでください。<BR><B>【ライターマン さんのオススメ作品】</B> <A HREF="novel/youma/youma.html">妖魔城の寵姫</A> <FONT SIZE="-1">(ことぶきひかるさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これぞまさしく紅一点……のはずだったんだけども、あれ？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 医術 変身<BR>【キーワード】 親友萌え オレっ娘 女性仮性半陰陽</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/cinderella.html">俺がシンデレラになったわけ</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/12/4(土)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>６年前、俺はある事故によって身体が小さな子供になってしまった。そして現在、小学校の学芸会で俺は……<BR><B>【コメント】 </B>初めての年齢退行ものです。ちょっとひねりが効き過ぎてるかも……<BR><B>【ライターマン さんのオススメ作品】</B> <a href="novel/best_friend.html">ベストフレンド</a>(ミズキヒカルさん作)、<a href="novel/4sister/4sister.html">４人目の姉妹</a> <FONT SIZE="-1">(ことぶきひかるさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>小さくなったのも大変なのに、試練が待ち構えていた？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 医術 変身 薬品<BR>【キーワード】 学芸会 年齢退行 シンデレラ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/seal.html">封印を解きし者</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/10/22(金)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>山の中を藪を掻き分け進んでいた僕には大きな目的があった。それは隣にいる相棒を女にするというものだった。<BR><B>【コメント】 </B>封印や祟りはそっとしておく方が無難です(笑)。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>やはり、思惑通りに物事が運ばないのが、封印とかそーゆー類の物でして……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 飛んで火に入る……(爆) 策士策に溺れる 人を呪わば穴二つ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/forest.htm">森の中の女神</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/10/7(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>休みを利用して訪れたその森には美しい湖があった。「霧の日には入ってはならぬ」という言い伝えを無視してそこに入った俺は……<BR><B>【コメント】 </B>神話をもとに作ったんですが、現代を舞台にしているのでこんな風になってしまいました（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>禁忌とされている事象には、それなりの意味があるのです。わたしたちはともすれば「迷信」のひと言で、それをないがしろにしているのではないでしょうか……？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 女神様（笑） 神話</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/henten3.htm">変転(後編)</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/10/1(金)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「壁」に囲まれた不思議な世界から脱出するために俺たちは「像」を捜した。そしてようやく見つけた像を俺は……<BR><B>【コメント】 </B>サスペンスを期待すると肩透かしをくらいます(笑)。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライターマンさんのコメントが全てを表しています(笑)。毎度おなじみＭＯＮＤＯさんの絵もこれまたグーです。<BR>
<strong><a href="novel/200112/19020205/henten1.htm">【前編はこちら】</a><a href="novel/200112/19020205/henten2.htm">【中編はこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 伝奇 <BR>【種別】 神秘 変身 可逆<BR>【キーワード】 遺跡 肉体変移 パニック</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/henten2.htm">変転（中編）</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/9/15(水)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「壁」に囲まれた不思議な世界で俺たちは次々と変わっていった。男から女へ、女から男へ……<BR><B>【コメント】 </B>サスペンスを期待すると肩透かしをくらうかも？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>異空間に閉じ込められ、次々と性転換していく仲間たち。そして、ついに……<BR>
<b><a href="../novel/200112/19020205/henten1.htm">【前編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 伝奇 <BR>【種別】 神秘 変身 可逆<BR>【キーワード】 遺跡 肉体変移 パニック</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/henten1.htm">変転（前編）</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/〜kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/8/19(木)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>過疎により廃校になった学校で見つかった遺跡で俺は奇妙な像を掘り出した。それが全ての始まりだった。<BR><B>【コメント】 </B>ゲームとか小説とかを参考に作ってみましたが……ジャンル分けが難しいかも？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>やっぱり遺跡にはこういうものが付き物？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 伝奇 <BR>【種別】 神秘 変身 可逆<BR>【キーワード】 遺跡 肉体変移 パニック</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/morning.htm">目が覚めると</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/7/4(日)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>どこにでもいる高校生の筈の俺の人生はある日を境にして一変した。やがて俺自身と周囲が慣れ始めると……<BR><B>【コメント】 </B>人間というのはこのような状況でも慣れて（あるいは流されて）いくものでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>もしかすると、彼——彼女は人類の新たな進化の形なのかもしれない？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 学園 <BR>【種別】 神秘 変身 可逆<BR>【キーワード】 親友萌え オレっ娘 周囲の反応</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/prince.htm">王を継ぐ者</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/6/19(土)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>国王の後継問題で揺れるある国で、当事者の一人は不可思議な賢者に相談をもちかける。それに対し賢者の示した解決策は……<BR><B>【コメント】 </B>こういうのもファンタジーと言うのでしょうか？（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さても思い切ったことをしたもんです。……お互いに（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身 魔法？ 薬品<BR>【キーワード】 後継者争い オレっ娘？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/taiketsu.htm">対決！！</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/6/3(木)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女の子が生まれなくなった近未来、日本では人類の滅亡を避けえるため、ある「制度」が作られた。<BR><B>【コメント】 </B>「雌雄を決する戦い」というのはよく聞きますがここでは本当に雌雄を決しています（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>アサリさんの作品「友人」の世界観をカスタマイズして、ライターマンさんが放つ異色作。<BR>
君は、「男」で居続けることができるか……！？（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 近未来 <BR>【種別】  変身 テクノロジー<BR>【キーワード】 約束（笑） ゲーム</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/oreore.htm">おれおれ……</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/5/28(金)</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一儲けを企んだ二人の若者が書けた１本の電話。それは……<BR><B>【コメント】 </B>よい子の皆さんは絶対真似をしないで下さい！！　(どっちの？(爆))<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>儲けようととある番号に電話を掛けたが運の尽き。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 魔法 変身<BR>【キーワード】 しっぺ返し？ 電話 犯罪</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/idolboy3.htm">僕はアイドル？　完結編</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/5/10(月)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>苦労の末、僕とみずきさんはお互い元の身体に戻る事ができた。だがしかし……<BR><B>【コメント】 </B>全ての謎が今明かされる？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前回のラストでやっと元に戻った光司くんにふりかかる、理不尽（……でも『文庫』的にはＯＫ？）な運命とは！？（笑）<BR>
<b><a href="../novel/200112/19020205/idolboy1.htm">【前編はこちら】</a><a href="../novel/200112/19020205/idolboy2.htm">【後編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 入れ替わり（復帰） 人格転移（終了） テクノロジー<BR>【キーワード】 アイドル マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/idolboy2.htm">僕はアイドル？　後編</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/5/8(土)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>事故により僕とアイドルのみずきさんはお互いの人格が入れ替わってしまった。元に戻るまでの間、僕はみずきさんの代わりをする事になり……<BR><B>【コメント】 </B>羨ましいとみるか可哀想とみるかは人それぞれ（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>女の子と入れ替わっただけでも大変なのに、さらに「アイドル」としての生活……光司くん、ご苦労さまです（笑）。<BR>
<b><a href="../novel/200112/19020205/idolboy1.htm">【前編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 入れ替わり 人格転移 テクノロジー<BR>【キーワード】 アイドル マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/idolboy1.htm">僕はアイドル？　前編</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/4/27(火)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>後期試験の一つを受けられなかった僕とアイドルのみずきさんは、担当の教授に呼び出された。そして……<BR><B>【コメント】 </B>怪しげな教授の実験には参加しない方が無難です（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライターマンさん初の入れ替わりもの。相手は超人気アイドル……う〜ん、波瀾のよ・か・んっ♪（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 入れ替わり 人格転移 テクノロジー<BR>【キーワード】 アイドル マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/2fighters4.htm">二人の戦士アル＆レイ 第４話　花嫁の旅路</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/4/18(日)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>レイはとある事情から一人の女性を護衛する仕事を引き受けた。しかしそれは苦難の旅の始まりだった。(少し違うかも)<BR><B>【コメント】 </B>本当にしばらくぶりで忘れた人もいるかも知れないアル＆レイ。少しボリュームアップして帰ってきました。(笑)<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>言動っていうのは、普段の生活で染みついちゃっているから矯正は大変だと思いました（？）。<BR>
<B><A HREF="../novel/200210/28213920/2fighters1.htm">【第１話はこちら】</A><A HREF="../novel/200210/28213920/2fighters2.htm">【第２話はこちら】</A><A HREF="../novel/200210/28213920/2fighters3.htm">【第３話はこちら】</A></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー アクション 異世界 <BR>【種別】 魔法 変身<BR>【キーワード】 ファンタジー アクション 異世界</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/kininaru.htm">俺の気になるアイツ</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/1/15(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、俺の仕事仲間が体調不良で会社を休んだ。数日後、回復して再び出社したそいつは……<BR><B>【コメント】 </B>以前作った「ＴＳ熱」の設定をもとに作ってみました。まあ、笑ってやってください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＴＳ熱の猛威再び！（笑）　……皆様、風邪などお召しになりませぬように。<BR>
<b><a href="../novel/200112/19020205/girldays.htm">【前作『俺の女子高生な日々』はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界？ 近未来？ コメディかも？ <BR>【種別】 病気 変身<BR>【キーワード】 ボクっ娘 オレっ娘 どんでん返し</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage09.htm">変身美少女戦士ミラージュガール　最終話：そして……全ては終わり…………</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/1/12(月)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>度重なる戦いのために身体に異変が生じた俺は、変身を止められてしまった。しかし仲間の危機を知った俺は、忠告を無視して……<BR><B>【コメント】 </B>「西の空に明けの明星が輝くとき、一つの光が宇宙に向かって……」　<b>バキッ！！</b>「嘘をつくな、嘘を！！(by武士)」<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「変身美少女戦士ミラージュガール」、ついに最終回！！　……そして最後の戦いのあとに待つものは！？<BR>
<b><a href="../novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 学園？ ヒーロー <BR>【種別】 変身 アイテム<BR>【キーワード】 美少女戦士 最終決戦 その後</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage08.htm">変身美少女戦士ミラージュガール　第八話：驚きと戸惑いと怒りと喜び、そして……</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/12/25(木)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>邪霊界からの魔物を倒すために仕方なく美少女戦士に変身し女の子として学校に通うことになった俺。しかし運命はそんな俺に更なる試練を課し始めた……(でいいのかな？)<BR><B>【コメント】 </B>とうとう来てしまいました……この日が（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>回を重ねて第八話。……武士くん（真奈美ちゃん）に今、運命の時（笑）が！！<BR>
<b><a href="../novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 学園？ ヒーロー <BR>【種別】 変身 アイテム<BR>【キーワード】 美少女戦士 お約束の日（爆）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/pachi.htm">変○？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/11/29(土)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>疲れた身体を引きずって帰宅の途についていた俺は、見知らぬ店がオープンしているのを見つけた。<BR><B>【コメント】 </B>１８禁の世界の物語（爆）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「『文庫』は１８禁ＮＧじゃなかったのか！？」と思われた貴方。１８禁は１８禁でも、こっちの方なのです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 不条理 <BR>【種別】 神秘 変身<BR>【キーワード】 ミステリーワールド？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage_ex1.htm">変身美少女戦士ミラージュガール　番外編：運命の出会い？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/11/16(日)</TD><TD>59KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日クラブ活動の助っ人を頼まれた俺は、ロボットの操縦方法を教えてもらうために昔の知り合いに連絡をとった。<BR><B>【コメント】 </B>やってしまいました（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「……というわけで、ミラージュガールにゲスト出演なのでああああ〜るっ！！」<BR>
「「なんでお前が仕切るんだっ！！」」<BR>
<b><a href="../novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 ロボＴＲＹ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/world.htm">歪む世界</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/10/23(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、俺は今までつけたことのなかった日記をつけ始めた。俺の周りで起きている事を記録するため、そして俺が正気を保っていられるために……<BR><B>【コメント】 </B>ミラージュの番外編作ってて……何故かこっちが先に出来てしまいました。（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>少しずつ……少しずつ日常がすり変わっていく。歪んでいるのは……世界か？　俺か？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 不思議 <BR>【種別】 変身 神秘<BR>【キーワード】 日記 ミステリーワールド？ 変わりゆく世界</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage07.htm">変身美少女戦士ミラージュガール　第七話：衝撃（笑撃？）デビュー！？　転校生三代真奈美！！</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/10/1(水)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>魔物との戦いが続く中、俺たちは２学期を迎えた。学校に通うことが出来なくなった俺に母さんは……<BR><B>【コメント】 </B>特にコメントはありません。タイトル見りゃ内容は一発でしょう？（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ついにこの日がやって来た！　武士くんには悪いけど、みんなで真奈美ちゃんの学校デビュー（笑）を見守ろうっ。<BR>
<b><a href="../novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 転校生 お姉様（爆）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage06.htm">変身美少女戦士ミラージュガール　第六話：発動！！ 脅威！ 驚愕！ 恐怖？のパワーアップ！！</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/9/17(水)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>パワーアップのためしばらくの間変身できない俺たち。しかし魔獣出現の情報を得た俺たちは危険を顧みず現場へと向かう……<BR><B>【コメント】 </B>ミラージュガールたちがついにパワーアップ！！　その姿に驚き、そして笑って（？）下さい。（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ト○プル○ァイターにカイ○ーグ…………君らいったい何歳だ？（核爆）<BR>
<b><a href="novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 学園？ ヒーロー <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 パワーアップ 新たな展開</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage05.htm">変身美少女戦士ミラージュガール　第五話：逆転？反転？本日は性転なり！？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/9/6(土)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>戦力アップのため合体技の訓練をする俺たちミラージュガール。だが技の制御に失敗し、爆発に巻き込まれた俺たちは……<BR><B>【コメント】 </B>さて問題です。今回の一番の被害者は誰でしょう？（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「特訓」エピソード（……だったのか？）に続いて、お約束のパワーアップ…………と思わせておいて、実はとんでもないことになるんです……（笑）。<BR>
<b><a href="novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 立場の逆転 親友萌え？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage04.htm">変身美少女戦士ミラージュガール　第四話：夏の海は危険がいっぱい！？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/8/29(金)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>強力になってきている敵に対抗するため俺たちは海の近くのお寺で合宿をする事になった。そして俺たちは新たな存在と出会う……<BR><B>【コメント】 </B>夏と言えば海！！　海と言えば……（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>海と言えば水着！！　水着と言えば……（笑）。で、何故か敵と戦ったあとの話が長かったりして（……笑）。<BR>
<b><a href="novel/200210/28213920/m_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 迫り来る危機 水着 浴衣</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage03.htm">変身美少女戦士ミラージュガール　第三話：登場！(誕生？)真・美少女戦士？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/8/9(土)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺たちの前に現われたミラージュレッドを名乗る女の子。彼女の口から出た「事実」に衝撃を受け、俺は魔獣退治を拒否してしまう。そして……<BR><B>【コメント】 </B>ついに現われた三人目のミラージュガール、その衝撃の正体とは？……なんつって（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>賛否両論あるかもしれませんが、今回も不幸なお方がひとり……（笑）。<BR>
<b><a href="novel/200210/28213920/mirage0.html">【プロローグはこちら】</b></a><b><a href="novel/200210/28213920/mirage01.htm">【第一話はこちら】</b></a><b><a href="novel/200210/28213920/mirage02.htm">【第二話はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 揺れる乙女心？（爆）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage02.htm">変身美少女戦士ミラージュガール　第二話：気になるアイツは敵か？　味方か？　恋人か！？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/7/24(木)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>あれ（第一話）から一週間。あいつの笑顔に悩まされながら俺は学生生活を送っていたのだが、俺の前に突然謎の女性が現われて……（あれ？　なんか違うような気が）<BR><B>【コメント】 </B>○○よ、お前もか？（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回はある意味、涙なくしては読めません（……笑）。<BR>
<b><a href="novel/200210/28213920/mirage0.html">【プロローグはこちら】</b></a><b><a href="novel/200210/28213920/mirage01.htm">【第一話はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 着替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/2fighters3.htm">二人の戦士アル＆レイ 第３話　協力者の誤算</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/7/6(日)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある村の周辺で魔族が出没すると言う情報を得たアルとレイは先に依頼を受けていたジルという男に協力を申し出た。ジルはその提案を承諾したがある条件をつけて……<BR><B>【コメント】 </B>今回はいろんな意味で誤算でした。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>的確に敵を倒すために、自らの身に与える苦痛を承知で雷撃を放ち、耐え抜いたレイ。彼女らは、最高レベルの戦士だ、間違いなく。<BR>
<B><A HREF="../novel/200210/28213920/2fighters1.htm">【第一話はこちら】</A><A HREF="../novel/200210/28213920/2fighters2.htm">【第二話はこちら】</A></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 アクション ファンタジー <BR>【種別】 変身 魔法<BR>【キーワード】 出会い 戦い 女戦士二人旅(笑)</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/ichigo19.htm">いちごちゃんシリーズ：はっぴい？ばーすで……い？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/6/11(水)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺は何者かに尾行されていた。誰が？　どうして？　疑問に思った俺は逆にそいつを尾行して倉庫に入ると……<BR><B>【コメント】 </B>みんなで祝福してあげましょう（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あれれっ？　いちごちゃん、確かきみって……（笑）<BR>
<a href="../novel/kayo_chan/extra/i_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 ショートショート <BR>【種別】 変身<BR>【キーワード】 いちごちゃん サスペンス？ 誕生日（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage0.html">変身美少女戦士ミラージュガール　プロローグ：降りかかった変身(災難？)</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/6/10(火)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>父さんの仕事の都合で新間市に引っ越してきた俺は荷物の中にブローチがあるのを見つけた。昔、美少女戦士だったという母さんがそのブローチの話をしていると突然ブローチが光り出し……<BR><B>【コメント】 </B>うれし？恥ずかし初めての○○！？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なぜ、美少女戦士になったのか。こうだったんですか！<BR>
<b><a href="novel/200210/28213920/mirage01.htm">【第一話：俺は転校生で美少女戦士！？はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 着替え 入浴？ 喜ぶ家族(笑)</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightningex.htm">超装甲機動兵器ライトニング　外伝：それさえもおそらくはそれも平穏な日常</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/5/17(土)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>謎の敵「エネミーＱ」の攻撃を受ける日本で、国防軍のパイロット迫水恭平は人型機動兵器「ライトニング」を操縦することになるが、それと引き換えに女性になってしまい、「沢木響子」と名乗ることになってしまった。そんな彼(？)が戦いの合間に送る日々とは？<BR><B>【コメント】 </B>ライトニング各話の穴埋め的にストーリーを作ってみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>戦士たちに訪れる束の間の平穏。しかし我らが響子さんにとっては、「平穏」とはいかないようで……（笑）。<BR>
<b><a href="novel/200112/19020205/l_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 (ありません) 巨大ロボット (出ません) 遺伝子書換え (終わりました)</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/mirage01.htm">変身美少女戦士ミラージュガール　第一話：俺は転校生で美少女戦士！？</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/5/4(日)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>中学生だった俺はある日、悪と戦う力を受け継ぎ正義と平和を守る戦士になった。ヒーロー物が好きだった俺にとってそれは喜ぶべきことだったが、その変身にはとんでもない「おまけ」が付いていて……<BR><B>【コメント】 </B>とうとうこれに手を出してしまいました。（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「変身」で「美少女」ときたら、<b>期待するなってのが無理な話です。</b>堪能しましょう、皆の衆。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ ヒーロー アクション <BR>【種別】 アイテム 変身<BR>【キーワード】 美少女戦士 着替え 運命の出会い？（爆）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/2fighters2.htm">二人の戦士アル＆レイ 第２話　放浪の女戦士</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/4/12(土)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一緒に旅を始めたアルとレイの二人の戦士はとある都市を訪れた。宿屋のベッドで横になるレ<BR>
イにアルは自分の過去を少しずつ語り始める。<BR><B>【コメント】 </B>今回はアルの物語です。<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おおよそ一年前のお話。アルティナ=ランクードが語る過去。物語は、まだ続く……。<BR>
<B><A HREF="../novel/200210/28213920/2fighters1.htm">【第一話はこちら】</A></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション ファンタジー 異世界 <BR>【種別】 変身 魔法<BR>【キーワード】 出会い 戦い 女戦士二人旅(笑)</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/onegai.html">神様お願い</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/3/11(火)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「僕を女にしてください」ふざけて言ったその願いは何と叶ってしまった。女になってしまった僕は会社の先輩である引野さんと……<BR><B>【コメント】 </B>もしも願い事が叶うなら、あなたは何を願いますか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>愚痴るときは、時と場所をわきまえた上でどうぞ。特に場所は……ね。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 願い</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/2fighters1.htm">二人の戦士アル＆レイ 第１話　囚われの姫君</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/2/11(火)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人間と魔族の戦いの後、森に覆われた世界で戦士のレイは女戦士のアルと出会った。<BR><B>【コメント】 </B>剣と魔法の世界でのアクション物、を目指しました。楽しんでくれれば幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>やっぱり、ファンタジーの正統は、剣と魔法でしょう（笑）　彼女らの活躍や如何に！？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション ファンタジー 異世界 <BR>【種別】 変身 魔法<BR>【キーワード】 出会い 戦い 女戦士二人旅(笑)</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/oretachi2.htm">俺たちは女だ！！(学校編)</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/1/23(木)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>事故により俺達学生と教師は全員女になってしまった。止むを得ず俺達は女子高生として学校に通うのだが……<BR><B>【コメント】 </B>「学校編」ようやく出来上がりました。楽しんでいただけたら幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>爆発事故で発生した謎のガスを浴びて、女性化してしまった浩介たち。彼ら……もとい、彼女たちの新しい学園生活が始まる。<BR>
<b><a href="novel/200210/28213920/oretachi1.htm">【病院編はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身 薬品<BR>【キーワード】 集団性転換</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/rbxmas.htm">クリスマスイブに乾杯</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/12/23(月)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>五木と沢渡、最近付き合い始めた二人はデートの際のちょっとした行き違いから喧嘩してしまう。<BR>
　女性の気持ちが分からないと悩んでいた五木は、仕事上のトラブルを解決するために「レンタルボディ」の利用を提案し女性になるが……<BR><B>【コメント】 </B>みなさん、よいクリスマスを。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライターマンさんのＲＢシリーズ第二弾は、聖夜を前にすれ違うひと組のカップルのお話です。<BR>
<b><a href="novel/200202/01171723/rbsyucho.htm">【第一弾「急な出張にＲＢ」はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ SF 近未来 <BR>【種別】 テクノロジー 人格転移<BR>【キーワード】 クリスマスイブ レンタルボディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/tssales.htm">こちら手久乃総合販売株式会社</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/11/26(火)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>東京からＵターンした俺は「手久乃総合販売株式会社」に就職した。だが、そこには俺の知らない驚くべき秘密があった。<BR><B>【コメント】 </B>みなさん、就職するときは相手の会社のことをよく調べましょう（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>う〜ん……こんな会社が実際にあったら、就職してみますか？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 呪い</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200210/28213920/oretachi1.htm">俺たちは女だ！！(病院編)</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/10/28(月)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高校一年生最後の日、終業式の場でその悲劇(？)は起こった。爆発事故に巻き込まれた俺と仲間達の運命は？<BR><B>【コメント】 </B>「集団性転換とその後」を書こうとしたんですが、とりあえず変身の部分だけ。(笑)<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どんなカタチであろうとも、未来を語ることができるのは、残されたものだけの特権かもしれない。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園？ <BR>【種別】 医術？ 変身 薬品<BR>【キーワード】 集団性転換 鏡</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning6.htm">超装甲機動兵器ライトニング６</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/10/12(土)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「凶戦士」の攻撃を受け、左腕を失ったライトニング。絶体絶命の響子だったが駆けつけた戦闘機部隊との協力で何とかこれを撃退する。そして、ライトニングを降りて中枢ユニットの奥深く進む響子。その先に待ち受けるものとは？<BR><B>【コメント】 </B>ライトニング本編、完結です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライトニング、ラストバトルっ！！　はたして「カーネル」の正体とは？　そして、この戦いが意味するものは……？<BR>
<a href="../novel/200112/19020205/l_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書き換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning5.htm">超装甲機動兵器ライトニング５</a></B></TD><TD><B><A href="mailto:kagawa@elf.coara.or.jp">ライターマン</a></B> さん (<A href="http://www3.coara.or.jp/~kagawa/writerman/index.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2002/9/29(日)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに発見された「エネミーＱ」の本拠地。防人と弓削、そして響子の思いが交錯する中、総攻撃が開始される。<BR><B>【コメント】 </B>ライトニングの第５話、今回は前後編の前編です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>明かされる衝撃の事実。そして三段構えの作戦で挑む国防軍に勝機はあるのか？　それぞれの思いを胸に、最後の戦いの幕が上がる……<BR>
<a href="../novel/200112/19020205/l_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning4.htm">超装甲機動兵器ライトニング４</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/8/11(日)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ライトニングの操縦者、沢木響子は国防軍創立記念の観閲式に参加しようとしていた。だが、ちょうどそのとき現れた一人の人物の存在が、響子に今までの日々の終わりと戦いの新たな展開を予感させる。<BR><B>【コメント】 </B>ライトニングの第４話です。今回は結構シリアス……だと思います（本当かよ？）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ライトニングに迫る「エネミーＱ」の魔の手！　響子の流す涙は怒りか悲しみか……？<BR>
<a href="../novel/200112/19020205/l_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書き換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/natuyume.htm">ま夏の夜の夢</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/6/30(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>パソコンの前でうとうとしていた俺に呼びかける声。現れたのは宇宙から来た不思議なコウモリだった。<BR><B>【コメント】 </B>ちょっと思いつきで書いてみましたが、わかる人あんまりいないかも(笑)<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>この文庫内で不条理に変身させられた人の一人です（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作？ コメディ <BR>【種別】 変身<BR>【キーワード】 特撮 アニメ ウルトラマン 仮面ライダー セーラームーン その他いっぱい</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/angelterm2b.html">天使の携帯端末(後編・パターンＢ)</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/6/9(日)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>公園で拾った不思議な機械を使ったボクは誤って女の子になってしまい、元に戻る前に持ち主の女性が現れて機械を持ち去ってしまった。元に戻るために女の人を捜していたボクは……<BR><B>【コメント】 </B>パターンＡと同じ文章で始まりますが、途中の選択肢(？)よりストーリーが分岐します(笑)。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「天使の携帯端末」もうひとつの結末。……あなたならどちらを選択しますか？<BR>
<b><a href="novel/200112/19020205/angelterm1.html">【前編はこちら】</a></b><b><a href="novel/200112/19020205/angelterm2a.html">【後編・パターンＡはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 神秘 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/angelterm2a.html">天使の携帯端末（後編・パターンＡ）</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/5/30(木)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>公園で拾った不思議な機械を使ったボクは誤って女の子になってしまい、元に戻る前に持ち主の女性が現れて機械を持ち去ってしまった。元に戻るために女の人を捜していたボクは……<BR><B>【コメント】 </B>後編のストーリー、やっと出来ました。はたしてしのぶくん（ちゃん？）は幸せになれるのか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「天使の携帯端末」後編、満を持して登場っ！　そして…………やっぱりお前かっ！！（笑）<BR>
<b><a href="novel/200112/19020205/angelterm1.html">【前編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 神秘 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning3.htm">超装甲機動兵器ライトニング３</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/4/20(土)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>国防軍はライトニングに装備する兵器を開発していた。兵器のテストをしていた沢木響子は、榎本少尉と親しげに話す弓削大尉を見て動揺する。その直後に襲来した「エネミーＱ」に対し、響子は弓削大尉の制止を振り切り勝手に出撃してしまう。<BR><B>【コメント】 </B>ライトニングの第３話です。サブタイトルは「響子、暴走」と言うところでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ラーメン屋でマドモアゼルとデートしませう（笑）。<BR>
<b><a href="novel/200112/19020205/lightning.htm">【第１話はこちら】</a></b><b><a href="novel/200112/19020205/lightning2.htm">【第２話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/angelterm1.html">天使の携帯端末(前編)</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/3/29(金)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日の放課後、僕は公園で不思議な機械を拾った。それが僕の運命を大きく変えることも知らずに……。<BR><B>【コメント】 </B>未完の作品なんですが、考えた末に前編として出すことにしました。しのぶくん（しのぶちゃん？）の明日を決めるのはあなたかもしれない？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>しのぶ君の運命やいかに。しかし、妖しいものを拾ったら注意しましょうね。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 神秘 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/girldays.htm">俺の女子高生な日々</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/2/28(木)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、熱を出した俺は診察に向かった病院で意外な病名を告げられる。そこから始まる俺の恥ずかしく騒がしい２ヶ月間。<BR><B>【コメント】 </B>現在の日本とちょっとだけ違う世界が舞台です。これはパラレルワールド？　それとも近未来？　それとも……？　何はともあれ楽しんでいただけたら幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>第二掲示板で“ちらっ”と公開されていた、謎の「ＴＳ熱」にかかった彼の運命は……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界？ 近未来？ 学園 <BR>【種別】 病気 変身<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning2.htm">超装甲機動兵器ライトニング２</a></B></TD><TD><B>ライターマン</B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2002/2/11(月)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>敵人型機動兵器の奪取、起動に成功した国防軍では特殊機動部隊を編成して国防の要としようとするが、パイロットの迫水にとってそれは困惑の日々の始まりだった。<BR><B>【コメント】 </B>前作の続きとしていろいろ考えてみたらこんな風になってしまいました。前作よりもギャグ多め、シリアス少な目です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>『ライトニング』第２話、満を持しての登場です。キャラクターも増えて、にぎやかになってきました。<BR>
<b><a href="novel/200112/19020205/lightning.htm">【前作はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書き換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200202/01171723/rbsyucho.htm">急な出張にRB</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/2/1(金)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>締め切り前の修羅場にかかってきた出張依頼の電話。窮地に立たされた社長は一計を案じるが。<BR><B>【コメント】 </B>ビジネスの世界では急な出張はよくあること。でも、こんな出張あなたならどうします？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そんな出張だったら喜んで行くな〜</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ SF 近未来 <BR>【種別】 テクノロジー 人格転移<BR>【キーワード】 レンタルボディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200201/26224453/shinden.html">禁じられた神殿</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/1/26(土)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男性神と女性神の争いの末に生まれたとされる世界。女人禁制の聖地に潜り込んだ女性とその幼馴染みの物語。<BR><B>【コメント】 </B>ファンタジー物を目指してみたのですが……うーん、どうでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ふとしたことで出会った男と女。しかしその二人、実は…？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 ファンタジー <BR>【種別】 変身 魔法<BR>【キーワード】 神殿 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200201/05004202/holyex1.htm">聖霊戦隊ホーリーレンジャー　外伝その1</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/1/5(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>正月の御剣神社。例年と変わらず参拝客でごった返す中でただ一人、<BR>
例年と違う正月を迎える者がいた。<BR><B>【コメント】 </B>巫女です<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>みなさ〜ん。初詣にいきましたか？<BR>
<b><a href="novel/200201/05004202/holy1.htm">【第一話はこちら】</a><a href="novel/200201/05004202/holy2.htm">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ヒーロー アクション <BR>【種別】 神秘 変身<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200201/05004202/holy2.htm">聖霊戦隊ホーリーレンジャー　第二話</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2002/1/1(火)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>神族と魔族の代理人による戦いに巻き込まれた光一は偶然にも神族の<BR>
代理人になってしまう。光一を襲う更なる悲劇(喜劇？)とは？<BR><B>【コメント】 </B>前回、これからというところで終わらせたので急いで書き上げてみま<BR>
した。さて、光一にとっての災難は戦いに巻き込まれたことか？それとも？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>怜子の事情をしった光一は・・・<BR>
<b><a href="novel/200201/05004202/holy1.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ヒーロー アクション <BR>【種別】 神秘 変身<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200201/05004202/holy1.htm">聖霊戦隊ホーリーレンジャー　第一話</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2001/12/26(水)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>現代の世界では神族と魔族の代理人による戦いが人知れず行なわれていた。偶然その戦いを目撃した姉弟の運命は？<BR><B>【コメント】 </B>今度は戦隊物に挑戦してみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そう、戦隊ものです。そしてその中に一人は必ずいるものといえば……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ヒーロー アクション <BR>【種別】 神秘 変身<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/19020205/lightning.htm">超装甲機動兵器ライトニング</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2001/12/19(水)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>20XX年、謎の組織のテロにより窮地に陥った日本では敵から奪った兵器を何とか動かそうとしていた。敵襲の中、主人公はある方法を試してみるが…<BR><B>【コメント】 </B>一応シリアスもののつもりですが、最後の最後になって崩れます。<BR>
「これのどこがTSなのだ！」と言う方もいらっしゃるかもしれませんが、最後までお付き合いくださいますようお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>触らぬ兵器にたたりなし？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション？ 戦記？ SF 近未来 <BR>【種別】 テクノロジー 変身<BR>【キーワード】 戦闘 巨大ロボット 遺伝子書換え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/03015947/moonlight.html">月の光の下で</a></B></TD><TD><B>ライターマン</B> さん </TD><TD>(イラストなし)</TD><TD>2001/12/3(月)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=writerman">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人跡未踏の地で発見された超古代の遺跡。好奇心旺盛で調査に参加した主人公は満月の晩に…。<BR><B>【コメント】 </B>長いこと見るだけだったのですが、ちょっと思いついて初めて書いてみました。もう少し神秘性や主人公の心理描写を書いてみたかったのですがこの辺が限界のようです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これぞ変身の王道ってな感じです。シリアス路線の作品をお一つどうぞ。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 遺跡 月 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(209.237.238.231) , Competence : -1 -->
</BODY></HTML>
