<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_01.html">微妙存在ろろみ　第１話『存在の耐えられない微妙』</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/7/28(水)</TD><TD>61KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人体分身（スプリット）装置の実験台となった主人公の青年。ところがトラブルで少女の体の分身ができてしまい、主人公の意識も分身の少女の肉体のほうに！　本当の主人公だとわかってもらえない少女は実験室から逃げ出し、文芸雑誌編集長と名乗る女性に街中でスカウトされます。「あなた、アイドルになってみない？」<BR><B>【コメント】 </B>２年ぶりのご無沙汰です。「バケルくん」「おみそれ！トラぶりっ娘」「マイ・ピュア・クローンドール」……、そんなタイトルが思い出されそうな“異体分身ＴＳ”ジャンルに挑戦してみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>意識もが移動し、自分が少女になってしまった主人公。彼は、いや彼女は、小説家を目指していた。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR>『こうけい』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_06c.html">微妙存在ろろみ　第６話『すべてが微妙になる』（後編）</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/7/5(水)</TD><TD>116KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ろろみの作家人生初の大イベント、新人賞の授賞式。作家仲間や各界の有名人がろろみを祝福する。けれどもライバル作家がろろみの受賞に異議を唱え、追い詰められたろろみは会場を飛び出す。作家人生初のイベントが、作家生命の幕引きになってしまうのか。<BR><B>【コメント】 </B>第６話がついに完結します。Ｓ伸一郎に反発するフツーの女子高生・ろろみに、優一郎が思わせぶりな指摘をします。Ｐ伸一郎とＳ伸一郎、互いに異なるふたりの“もうひとりの自分”の協力を得て、ろろみはどのようにピンチに対処していくのか。ご注目ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ろろみは一歩ずつ成長していきます。そのなかで見つけるろろみらしさ。揺れ動く気持ちは周りからの励ましによって、見失っていた思いを取り戻します。<BR>
（後編はページ数が多いので、読みすぎにご注意を。。）<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 学園 <BR>【種別】  人格転移 テクノロジー<BR>【キーワード】 作家 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_06b.html">微妙存在ろろみ　第６話『すべてが微妙になる』（中編）</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/10/24(月)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>昼間の事件の余韻冷めやらぬ中、深夜にさらなる事件が発生する。ろろみ＝Ｐ伸一郎は自分に克つことができるのか。“ひとりでふたり”の関係が、ある意味で近くなる。<BR><B>【コメント】 </B>前中後編に分かれた第６話の中編です。Ｐ伸一郎からろろみが分身するアイテム、スプリッターの意外な使い道が判明します。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さらなる事件にろろみの心は揺れ動く。<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 学園 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル 作家</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_06a.html">微妙存在ろろみ　第６話『すべてが微妙になる』（前編）</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/10/3(月)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高校生活にも馴染んだかに見えるろろみですが、下校途中に事件に巻き込まれます。「守護騎士団」の男子生徒や親友の史枝、そしてもうひとりの自分・Ｓ伸一郎が救出に活躍するのですが……。<BR><B>【コメント】 </B>ろろみの高校生活はフツーなようであまりにスリリング。日頃は疎ましいあいつだけれど、やっぱり切っても切れない関係なのだ。前中後編に分かれた第６話、まずは前編をどうぞ。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ろろみに危機が訪れる。しかし、Ｓ伸一郎が救出する。<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 学園 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル 作家</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_05a.html">微妙存在ろろみ　第５話『微風立ちぬ』（アイドル作家編）</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/2/27(日)</TD><TD>47KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高校への初登校の前後、ろろみはアイドル作家としても様々な同業者と出会います。こちらでもやはり、伸一郎を意識させられる局面はあるのです。<BR><B>【コメント】 </B>第５話の「アイドル作家編」です。「学園編」で名前だけちらりと登場した、ある人物の正体が明らかになります。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>出会いあり、驚きありです。<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】  人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_05.html">微妙存在ろろみ　第５話『微風立ちぬ』（学園編）</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/2/17(木)</TD><TD>58KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>晴れて高校生になったろろみの初登校です。クラスメイトたちとの出会いの中で、ろろみは伸一郎としての自分も意識せずにはいられません。ひとりでふたりの微妙な関係はまだまだ波紋を広げます。<BR><B>【コメント】 </B>第５話は長くなったので「学園編」と「アイドル作家編」に分割して投稿することにしました。まずは「学園編」をどうぞ。ＭＯＮＤＯさんの制服ろろみが付いてます。<BR><B>【こうけい さんのオススメ作品】</B> <A HREF="novel/200011/15112734/lookyays_01.html">八重洲様がみてる</A> <FONT SIZE="-1">(BAFさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ろろみの高校初登校です。そこには意外なことが。<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業 現代 学園 <BR>【種別】  人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_04.html">微妙存在ろろみ　第４話『誰がために微妙は鳴る』</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/12/12(日)</TD><TD>68KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>もうひとりの自分との近くて遠い距離に、伸一郎としてのガールフレンドとの痛し痒しな関係、そして高校の編入試験。ろろみを悩ます種は多けれど、悪いことばかりなはずがない。<BR><B>【コメント】 </B>ろろみは意外な人物の応援を受けて高校の編入試験に挑みます。今回は“身内”の人々が活躍する話になりました。そういう中では一層微妙になってくる、ろろみの存在位置を味わいください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ろろみと伸一郎は、スプリット・リンクアップも慣れてきたのでしょうか。<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_03.html">微妙存在ろろみ　第３話『微妙戦線異状あり』</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/10/10(日)</TD><TD>88KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>すっかり有名になった微風ろろみが編集部に顔を出します。編集長たちとお買い物を楽しんで、テレビの生放送でも大活躍。けれども、もうひとりの自分との距離はまだまだ微妙です……。<BR><B>【コメント】 </B>プロフィールを決める打ち合わせ、スキャンダル発覚、お買い物、テレビ出演と盛りだくさんの内容です。ちょっと怪しげな電子掲示板も登場します（苦笑）。ＭＯＮＤＯさんのイラストが新たな魅力を吹き込んでくれました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ろろみの初めてのお買い物？です。だんだん、ろろみに慣れていきます。このあとどうなっていくのかな？<BR>
<b><a href="novel/200207/03224430/roromi_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_02.html">微妙存在ろろみ　第２話『限りなく微妙に近い計画』</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/8/17(火)</TD><TD>77KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>なんとか元に戻れた主人公の青年は、もう分身なんてこりごり状態。ところが自分が分身した少女の寄稿した小説が、知らぬ間に新人賞に選ばれていた。少女にアイドル作家デビューのチャンス！　さあ青年のとった対応は？<BR><B>【コメント】 </B>分身ＴＳ少女が次第に“アイドル作家・微風ろろみ”としての自覚を持っていく過程をお楽しみください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>アイドル作家としての出発をするのか、それとも新人賞を放棄するか？　少女の苦悩も伺える？<BR>
<B><A HREF="novel/200207/03224430/roromi_01.html">【第１話はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】  人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/roromi_01.html">微妙存在ろろみ　第１話『存在の耐えられない微妙』</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/7/28(水)</TD><TD>61KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人体分身（スプリット）装置の実験台となった主人公の青年。ところがトラブルで少女の体の分身ができてしまい、主人公の意識も分身の少女の肉体のほうに！　本当の主人公だとわかってもらえない少女は実験室から逃げ出し、文芸雑誌編集長と名乗る女性に街中でスカウトされます。「あなた、アイドルになってみない？」<BR><B>【コメント】 </B>２年ぶりのご無沙汰です。「バケルくん」「おみそれ！トラぶりっ娘」「マイ・ピュア・クローンドール」……、そんなタイトルが思い出されそうな“異体分身ＴＳ”ジャンルに挑戦してみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>意識もが移動し、自分が少女になってしまった主人公。彼は、いや彼女は、小説家を目指していた。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 アイドル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/babyboom.htm">ベビーブーム</a></B></TD><TD><B><A href="mailto:koukei@koukei.org">こうけい</a></B> さん (<A href="http://www.koukei.org">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/7/3(水)</TD><TD>4KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>子沢山の家庭に、男女の養子がやってきた。ところが…？<BR><B>【コメント】 </B>こんな理屈でＴＳしたらたまりませんね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これの元ネタって、実に様々なバージョンがあります。調べてみるのも一興でしょう。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 ショートショート <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/overchange.html">かわりすぎ</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/8/8(水)</TD><TD>4KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>完璧な性転換薬をめぐる争いの結末は？<BR><B>【コメント】 </B>吉井重治さんの『契約』に刺激されて書きました。吉井さん、ありがとうございます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>極秘の研究と秘密兵器、そしてスパイとくりゃこれでしょう。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 現代 ショートショート <BR>【種別】 変身 薬品<BR>【キーワード】 博士</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200103/24194542/himegami_x_19.html">姫神奇譚　外伝十九話＆二十話「始業式（前編＆後編）」</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/7/14(土)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=himekami">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>書類ミスで男の子が女子校に転入することに！？大騒ぎの校長室に姫神様が現れて…。<BR><B>【コメント】 </B>前編と後編の二部作です。ぜひ通しでお読みください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「ココロとカラダの悩み、お受けいたします　古都音」？？？　いえ、何となくこんなフレーズが頭に浮かびまして（笑）<BR>
<b><a href="novel/200103/24194542/himetitle.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 姫神奇譚</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200103/24194542/himegami_x_18.html">姫神奇譚　外伝十八話「Ah! My Goddess」</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/7/14(土)</TD><TD>4KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=himekami">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>おとぼけ姫神様が３つの願いをかなえてくれます。<BR><B>【コメント】 </B>亜希みちるさんの「ああっ姫神さまっ」が帰ってきました！？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>古都音様の知られざる能力がまた一つ明らかに。今回はグローバル化に対応して…。<BR>
<b><a href="novel/200103/24194542/himetitle.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 姫神奇譚</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/rensou21.html">連想ゲーム２１</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/6/30(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男女対抗のクイズ番組『連想ゲーム』が２１世紀に復活！『２１』ならではの新しい演出とは…？<BR><B>【コメント】 </B>気軽に読めるバラエティ番組感覚で仕上げました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>よくある形式のクイズ番組も、ひとひねり加えるとおもしろさ倍増！　あくまで視聴者側は、ですが（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 ♀→♂ 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200103/24194542/himegami_x_10.html">姫神奇譚　外伝十話「神の領域」</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/6/8(金)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=himekami">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>今度は姫神様が陸上競技のアシストに挑戦します。<BR><B>【コメント】 </B>調子にのって姫神外伝２作目を書いてしまいました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>健全な精神は健全な肉体に宿る？果して古都音は勝利の女神になれるのか？<BR>
<a href="novel/200103/24194542/himetitle.html"><b>【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 変身<BR>【キーワード】 姫神奇譚</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200103/24194542/himegami_x_6.html">姫神奇譚　外伝六話「正直者は」</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/5/17(木)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=himekami">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>制服が見当たらなくて困っている男子高校生の前に姫神様が現れて…。<BR><B>【コメント】 </B>亜希みちるさん、さっそく外伝五話の世界観を使わせていただきました。こういう設定って大好きです！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ますます広がる姫神ワールド！　こうけいさんの外伝六話ですっ。<BR>
さて、「正直者は」のあとに続く言葉はなんでしょう？　「得をする」？　それとも「バカを見る」？<BR>
<strong><a href="novel/200103/24194542/himetitle.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 姫神奇譚</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/hensou.html">変奏曲</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/5/9(水)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>舞台は高校の吹奏楽部。希望通りの楽器が担当できなくて駄々をこねている主人公に、先輩が“変奏曲”という題名の曲を演奏するよう勧めるが…。<BR><B>【コメント】 </B>少し不思議で、それでいてさわやかな短編に仕上げました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>みなさんはトランペットとクラリネット、どっちを演奏したいですか？<BR>
こんな曲があるならどっちでもいいから演奏したいです（爆）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/hiruyasumi4.html">昼休み（最終回）</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/5/6(日)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>淑子が基晴を女子に変えてしまった。それを見て、理絵は自分がやったことを思い出し、基晴を男子に戻すよう淑子を説得するが…。<BR><B>【コメント】 </B>物語もいよいよ完結に向かいます。淑子・理絵・基晴の心が微妙に絡み合いながら、変身の秘密が明らかにされていきます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>人を好きになるということを正面から受け止めようとする彼女達。結論は如何に？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身<BR>【キーワード】 女性人格化 強制 精神改変 メガネっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/hiruyasumi3.html">昼休み（第３回）</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.j">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/4/13(金)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女子に変身してしまった淑子は、自分の内面にも変化が進んでいることに気づく。その変化を受け入れたとき、彼女はいじめを克服していくのだが…。<BR><B>【コメント】 </B>ストーリーは新たな局面を迎えました。心まで淑子になっていく彼女の葛藤や、さらなる変身など、見どころも用意してあります。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>開き直りを契機として安息が訪れた淑子の生活ですが、事態は思わぬ方向から核心に迫っていきます。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身<BR>【キーワード】 女性人格化 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/hiruyasumi2.html">昼休み（第２回）</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/3/31(土)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男子の勝から女子の淑子に変身してしまった主人公は、放課後に女子バレー部へと連れていかれる。初めての女子運動部で、淑子はどうなるのだろうか？<BR><B>【コメント】 </B>今回は部活動と帰宅後をメインに描きました。女子になってしまった主人公にさらに襲いかかる受難と、彼女の心の揺れ動きにご注目ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>　たとえ女の子になったって、無情な人生はつらいのです。<BR>
自らの姿を確かめる暇もない、安心して友に背中を向けることもできない蟻地獄。存分に味わってください。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/kayo_chan50.html">華代ちゃんシリーズ 「なりきり」</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2000/12/25(月)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>主人公はアニメの男性声優。人気アニメに晴れてゲスト出演を果たしたものの、演技が監督から不評を買い、窮地に立たされる。そこに現れた華代ちゃんは…。<BR><B>【コメント】 </B>華代ちゃんの手にかかれば、こんなシーンでも、キャラクターになりきった迫真の演技が可能になるのです！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あぁぁぁ！見てみたいぃぃ！！　実際に放映されないかな、このアニメ作品♪　臨場感・緊迫感あふれる演技も実際に…　華代ちゃんシリーズ最新作！（今回でちょうど５０作品目）<BR>
<a href="novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200207/03224430/hiruyasumi.htm">昼休み</a></B></TD><TD><B><A href="mailto:KHE02352@nifty.ne.jp">こうけい</a></B> さん </TD><TD>(イラストなし)</TD><TD>2000/11/29(水)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=koukei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>勝は、男子トイレの「大」に入ったことをクラスメイトの健也たちにからかわれる。健也が勝の机の名札ラベルを女子のものに貼り変えたとき、体や服装のみならぬ勝のすべてに異変が起こった…。<BR><B>【コメント】 </B>女性化を皮切りに、理不尽な受難の数々が、いじめられっ子の男子中<BR>
学生に降りかかります。彼、いや彼女の「どうしてこんなことに！？」という心の悲<BR>
鳴を感じていただければ、作者としては幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どこかダークな雰囲気が漂う小品。変わってしまった自分と変わってしまった周囲を主人公がだんだん認識するさまがうまく描かれています。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(64.208.172.173) , Competence : -1 -->
</BODY></HTML>
