<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji02.html">虹の瞳を得たのは</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2000/2/25</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一介の書院付神官であるラティルはある大きな苦悩に悩まされていた。その悩む彼を見兼ねた書院長は一計を謀って…。<BR><B>【コメント】 </B>前作、<a href="novel/rainbow/niji01.html">“虹の瞳と呼ばれて”</a>より半年ほど前のエピソードです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>男女二つの身体を持つ神官ラティルの物語です。今回は「虹の瞳」と呼ばれるラティルが女性としての身体を得るに至った経緯が描かれています。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 ファンタジー <BR>【種別】 身体交換 魔法<BR>【キーワード】 </TD></TR></TABLE><BR><BR>『夜夢』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress_ng.html">ミストレスと奇妙な仲間達〜NG</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2010/12/24(金)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>朝、目覚めた“彼”は、その身に訪れた異常を知る……そんな我が身の異常に戦慄する“彼”の名は……！<BR><B>【コメント】 </B>久し振りのミストレス・シリーズになります。今回は、外伝と言うか……番外編になります。ある意味で、ちょっと——或いは、かなり風変わりな作りなっているかと思いますが、楽しんで頂ければ幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>】「ＮＧ」といっても、撮影中にセリフ噛んだりとちったりすることの方じゃなくて──おっと、それ以上は見てのお楽しみ♪<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身<BR>【キーワード】 異形（ケモノ耳） 年齢変化？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/ruark2.htm">ヴァンゼール騒動記２</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2010/10/18(月)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ルアーク＝ヴァンゼールは、妹の再三に渡る懇願に負けてその願いを叶えることにしたのだが……それは、大事件の始まりとなってしまい……<BR><B>【コメント】 </B>久し振りとなる投稿です。今回は以前から思いついていたネタではありますが、果たして楽しんで頂けるでしょうか？<BR><B>【夜夢 さんのオススメ作品】</B> <A HREF="../novel/200607/02124625/yaoma_top.html">ヤオヨロヅ物語</A> <FONT SIZE="-1">(天爛さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶり夜夢さんの異世界奇譚。たとえ金属人──メタルヒューマノイドでも、お兄ちゃんは妹に弱いのです。そしてワリを食うのもやっぱりお兄ちゃんの方なのです（乾笑）。<BR>
<b><a href="../novel/rainbow/ruark.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】 入れ替わり 人格転移 テクノロジー？ 可逆<BR>【キーワード】 年齢変化？ メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress22.html">ミストレスと奇妙な仲間達〜その22</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2009/11/14(土)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレスハウス”を訪れた少年達……それは“うさ”の師匠——庖姐——の弟子達だった。彼等との共同生活を続けて数日後……彼等や“ミストレスハウス”の面々を巻き込む大騒動が……！<BR><B>【コメント】 </B>今回のお話は、ミストレス・シリーズでいつも微妙に不幸な目にあっている彼女が、盛大に不幸になってしまう……と言うお話を書いてみました（苦笑）。でも結局、誰が一番不幸な目に遭ったのでしょうか……？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そんなことをしてしまったら……というのに、皆さん容赦がないです。<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 異形（ケモノ耳）<BR>【キーワード】 ケモノ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress21.htm">ミストレスと奇妙な仲間達〜その21</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2009/3/20(金)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレスハウス”の一員——“ねこ”が密かに抱いていた悩み……それを聞いたミストレスに与えられた物がとんでもない事態を招き寄せる！<BR><B>【コメント】 </B>本当に久し振りのミストレス・シリーズになりますが……書いていて、かつてやったDQを思い出しました（笑）　（「“ねこ”は○○ランクになった。××の▲▲をおぼえた」……ってなことを）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>実はひそかに『“ねこ”は○○○っ娘になった』でもあります！<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法 変身<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200711/19201612/sanki02.html">三姫巡遊記　流闘姫編その二</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2008/7/12(土)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>森の中の街道を抜けるフィラ一行……一行に同行するルティオは、そこでとんでもない出会いを経験することに……！<BR><B>【コメント】 </B>取り敢えず、やっと何故“流闘姫編”なのかを描くことが出来ました。ある意味、そのまんまな呼び名だなぁ〜と思わなくもない……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>薄幸の女装（を強要される）少年ルティオくん。だけどひとたびＴＳして水棲人の少女に変わると……<BR>
<b><a href="../novel/200711/19201612/sanki01.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200711/19201612/sanki01.htm">三姫巡遊記　流闘姫編その一</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2007/11/19(月)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>貿易商フィルラーナ商会を訪れた少年ルティオ……商会を訪れた彼に降りかかる運命とは……？<BR><B>【コメント】 </B>久しぶりの投稿になります。その一となっていますが、その長さと言い、内容と言い、序章に過ぎない出来と思わなくもない……（苦笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶりの夜夢さんの新作は、お得意の異形変身譚。……ををっ！　そうきましたか。<BR>
<b><a href="../novel/rainbow/niji01.html">【虹の瞳と呼ばれて】</a><a href="../novel/rainbow/niji02.html">【虹の瞳を得たのは】</a>もご一緒に読んでみては？</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/kenzya03.html">狂才!?沼池教授の生活 賢者の石（？）争奪編　第三話：萌え出ずる者達</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/6/5(日)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレス・ハウス”を訪れた謎の女性……それは、ミストレス・グレイの使者であった！……彼女等の執拗な追及（と言うか、襲撃）を振り払う為に、“彼女”達が立ち上がる……!!<BR><B>【コメント】 </B>ドタバタ・コメディーになりきれないので、思い切って別路線を狙ったシーンを入れてみました。成功したかどうかは……あんまり自身はないかも……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>新たな参戦で、争奪戦は混迷を深めていく。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow_ex3.htm">影の騎士外伝“少女に見る夢”</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/6/1(水)</TD><TD>65KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“影の騎士”に付き従いし少女……その誕生に秘められた悲劇……<BR><B>【コメント】 </B>「“影の騎士”外伝」の三作目……想定していた“影の騎士”の物語は描き終えたことになります……例によって、ＴＳキャラは一人も出てきていません（爆）。今回は、少しばかり捻りを効かせた物語構造になっていますので、ニヤリとして頂ければ幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＴＳキャラが登場しないことにご不満（笑）がありましたら、本編を読破されることをお薦めします。それと、最後の余話にもちょっとした仕掛けが。<BR>
<b><a href="../novel/200112/18123055/sh_title.htm">【『影の騎士』シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/kenzya02.html">狂才!?沼池教授の生活 賢者の石（？）争奪編　第二話：流れ始める事態</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん (<A href="http://www16.ocn.ne.jp/~kariyado/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/3/5(土)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>沼池教授宅を襲うモノ！……託される“賢者の石”（推定）！……それを手にした狗美が駆け込んだ先とは……!!<BR><B>【コメント】 </B>全五話のドタバタ・コメディーになる予定だったのに……自分では巧く行ったとはとても言えない。ちゃんと、五話で完結するんだろうか……？<BR><B>【夜夢 さんのオススメ作品】</B> <A HREF="novel/hakken/hakken01.html">シャイニング・スピリッツ・ブレイヴス</A> <FONT SIZE="-1">(ことぶきひかるさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>危機一髪の狗美。事態は思いがけない方向に流れ始めた。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/ruark.htm">ヴァンゼール騒動記</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/30(金)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高々空から墜落したメタル・ヒューマノイドの少年ルアーク……彼が目覚めた時、その姿は少女のそれに変わっていた！？<BR><B>【コメント】 </B>以前「第二掲示板」に予告編を掲載させて頂いた作品の本編になります。こう言うパターンって珍しいと思うのですが、如何だったでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>キーボードにお茶こぼしても、ＨＤさえ無事なら……って、そうぢゃないっ！（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】 入れ替わり 可逆？ テクノロジー？<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow-ex2.htm">影の騎士外伝“老婆の見る夢”</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/30(金)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“影の騎士”シェアナの周囲で暗躍していた者の一人……“黒鱗のお婆”。彼女の意外な、そして波乱に満ちた生涯……<BR><B>【コメント】 </B>こちらへの投稿を迷う出来の作品なのですが…………“彼女”の物語、よろしければご覧になって下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>影の騎士シェアナを導いた“黒鱗のお婆”を通して見えてくる、アティス大陸の歴史。これを機に、未読の方は本編も読んでみてください。<BR>
<b><a href="../novel/200112/18123055/sh_title.htm">【『影の騎士』シリーズタイトルはこちら】</TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/kenzya01.html">狂才!?沼池教授の生活　賢者の石（？）争奪編第一話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp ">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/15(火)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>遂に……遂に、沼池教授と狗美は長年の悲願が達成された！　——と思われたその時、騒動がやって来た！<BR><B>【コメント】 </B>意外な程に執筆に時間がかかりましたが、ミストレスシリーズ番外長編の第二段です。楽しんで頂けると良いのですが・・・（今回の見所は、やはりミストレス対決・・・でしょうか？）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>幻の結晶体、賢者の石。それを狙ってくる人たち。沼池教授の苦難がまたひとつ。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法 変身<BR>【キーワード】 異形（ケモノ耳） （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji_ex.htm">虹の瞳 亜伝</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/14(金)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>所は神殿都市セオミギア……神殿学院の講義をサボって市街に出た少女が目にしたものは……！<BR><B>【コメント】 </B>以前「第二掲示板」に掲載させて頂いた物の加筆版です。長く寝かせていた作品の一つではありますが、如何でしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶりの夜夢さん。“虹の瞳”ラティルさんの子どもたちのお話です。<BR>
<b><a href="../novel/rainbow/niji01.html">『虹の瞳と呼ばれて』</a><a href="../novel/rainbow/niji02.html">『虹の瞳を得たのは』</a>はこちら</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】  変身 魔法？ 可逆<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena12.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第十二話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/1/1(木)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>最後の封妖……ランシンとの激しいは終わった。晴れ渡る空の下、皆が笑顔で迎える大団円！（と言うのは微妙に間違っています！　（Ｉ．Ｍ．「……って、絶対間違ってるぞ〜！」））<BR><B>【コメント】 </B>何とか送り出せました封妖編完結巻……！　う〜ん、ラストは救いがなさ過ぎるかも……と半ば思う私……（残り半分は、正反対なことを思っております。（苦笑））<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>息もつかせぬラストバトルから、怒濤（？）のエンディングまで目が離せないぞっ！！　……いろんな意味で（笑）。<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena11.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第十一話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/12/21(日)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>辛くもコウユウを撃退したイーナ達……だが、その代償は大きかった。壊滅的被害を受けた御空神社と死に瀕する青弓氏……そんな彼女達の元に、最後の‘それ’がやって来る！（と言うのは微妙に間違っています）<BR><B>【コメント】 </B>封妖編も、何とか最終章に突入しました。今回のラストは結構気に入っているのですが、如何ですか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>稲生くんと炎くんのやりとりがいいです。やっぱあの母様たちには逆らえないわな……（笑）。<BR>
そして、最後にして最強の封妖が、イーナたちに襲いかかるっ！！<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena10.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第十話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/12/8(月)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>衝撃の真実を知った稲生は驚きと戸惑いを隠せない……だが、そんな彼等に復讐心を燃やすコウユウが襲いかかる。イーナ達は、決死の作戦を敢行する！（と言うのは微妙に間違っています）<BR><B>【コメント】 </B>結構早めに送り出せました（……でも、11月中発表の目論見は脆くも崩れ去りましたけどね（苦笑））。今回の見所は、幻の変身形態です！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>残る封妖はあと二体。だが、イーナたちは魔法の効果を打ち消す結界によって、変身を解除されてしまう……<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena09.html">電光の魔法少女エレクトリック・イーナ　十二封妖編第九話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/11/15(土)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>歳妖四天王筆頭コウユウ・・・その圧倒的な実力の前に、イーナ達は翻弄される。だが、それを打ち滅ぼした彼の者の正体とは・・・（と言うのは微妙に間違っています。）<BR><B>【コメント】 </B>副題に出ていた“使者”の正体・・・一体、どれ位の方が気が付いてくれただろうか？　ともあれ、封妖編も完結まで後三話（予定）・・・頑張って書ききるぞ！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>以外な展開になりました。この後は続きを待つしかない。。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/fms-k.html">FMS：pattern K</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/10/6(月)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>彼はその宣告にうちのめされる……そんな彼の元へ訪れたのは……<BR><B>【コメント】 </B>ちょっと思い付いたので書いてみました。捻りが少ない作りになっていますが、如何でしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>彼にとってはどちらも災いでしかなかったような。<BR>
<b><a href="../novel/200112/18123055/fms.html">【シリーズ設定・タイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 医学（？） <BR>【種別】 変身<BR>【キーワード】 華代ちゃんシリーズ番外編 ハンターシリーズ番外編</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress20.html">ミストレスと奇妙な仲間達〜その20</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/9/20(土)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>理不尽な父親の言葉、それに反抗した彼が駆け込んだのは・・・<BR><B>【コメント】 </B>お待たせしました。待望されていたであろう彼のお話です。それと、“料理のお姉さん”が登場致します（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>本当に食べられなくてよかったですね。あやうし○○ちゃん。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 魔法？ 変身<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/fms-r.html">FMS：pattern R</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/8/29(金)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>彼は語る・・・FMSについて・・・<BR><B>【コメント】 </B>作者からのお願いです。この作品を読む前に「FMS：pattern P」を御一読下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「pattern P」と表裏一体とも言えるこの作品、「pattern P」の舞台裏が見えてくるかもしれません。<BR>
<a href="novel/200112/18123055/fms-p.html"><strong>【FMS：pattern P はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 メタ(？) 現代(？) 医療 <BR>【種別】 （変身）<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/fms-p.html">FMS：pattern P</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/8/29(金)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>その朝、彼が目を覚ますと、奇妙な微熱を感じていた・・・<BR><B>【コメント】 </B>不意に思い付いて書いてみた作品です。ホラーっぽい作品を目指しましたが、果たして巧く描けているでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>タイトルの「FMS」とは一体何を表しているのか？　「pattern R」とあわせてごいっしょにどうぞ。<BR>
<a href="novel/200112/18123055/fms-r.html"><strong>【FMS：pattern R はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 ホラー(？) <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena08.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第八話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/8/18(月)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>封妖との戦いも最終局面に近付き、雪奈達による特訓の日々が始まる。この時、稲生は戦友の驚愕の正体を知ることになる！（と言うのは微妙に間違っています）<BR><B>【コメント】 </B>新キャラ登場…………と言えますかどうか？　彼女の登場で、話は一層ややこしく……なることはあるんでしょうか？（……イヤハヤ……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>残る封妖はあと三体。御空神社で稲生は運命の出会いをするっ！（笑）<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress19.html">ミストレスと奇妙な仲間達〜その19</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/7/11(金)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある日、”ミストレスハウス”を一人の少女が訪れる。その少女の正体こそ・・・・・・<BR><B>【コメント】 </B>今回は新シリーズ＆新キャラクターの登場です・・・が、彼女の登場に皆さんはどんな感想を抱くのだろうか・・・？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>"ひぃ"がちょっと畏ろしい。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress18.htm">ミストレスと奇妙な仲間達〜その18</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/6/7(土)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある朝、目を覚ました御上　狗美は・・・いつもと違う何かを感じたのだが・・・ドクトル編第四弾です。<BR><B>【コメント】 </B>今回はその９と関連がある作品となっております・・・しかし、偶然にも９・18と続くのなら、その27もこんな話なのか・・・？（サクシャモシラズ）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>突然モテモテになった狗美。困ったり汗ったり。<BR>
<b><a href="../novel/200112/18123055/title.htm">【シリーズタイトル＆設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena07.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第七話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/5/6(火)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>稲生達に襲い来る新たなる刺客……歳妖四天王が一角、シンインの能力によって、イーナ達は次々と打ち倒されて行く……（というのは微妙に間違っています。）<BR><B>【コメント】 </B>久々のイーナ封妖編です。これから物語りは、佳境への階段を上って行く…………予定です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>毎回ぎりぎりの戦いを強いられるイーナたち。今度の封妖も強敵だっ！<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress17.htm">ミストレスと奇妙な仲間達〜その17</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/4/28(月)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>年の瀬も押し迫ったとある日に、ミストレスハウスを訪れた者は……！<BR><B>【コメント】 </B>時期が大幅にずれてしましました……しかし、“ある意味”時期が合ってしまったのはイヤハヤ……ともあれ、（ある意味で）ウィザーズハウスの最も危険な人物の登場です。（微妙に初登場じゃないですけど……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ウィザーズハウスの面々が設定集に追加されました。今回はその中の一人が登場します。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress16-b.htm">ミストレスと奇妙な仲間達〜その16の裏</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/4/28(月)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ミストレス・キリクの師匠、グラン・マスター……彼はある物の出現を感知する。それが本当の始まりだったのだ。<BR><B>【コメント】 </B>以前投稿させて頂いた「〜その16〜」の“裏”です。他の意味でも“裏”の意味合いのある物語ですがね……（苦笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なるほど、やっぱり“アレ”だったのね……（笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ アイテム 変身<BR>【キーワード】 異形（ケモノ耳） LB</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow08.htm">影の騎士 第八話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/4/2(水)</TD><TD>47KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>…………長い長い紆余曲折の後、彼女はそこに戻って来た……王都フォーサイトに……新たな協力者と共に訪れたこの地で、彼女を待っていたものは…………<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。これでいよいよ最終話になります。全ての終わりとも言えるし、全ての始まりともいえる……大団円と見るかそうでないと見るか……それは読み手の皆々様の判断次第でしょうか……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>影の騎士……シェアナ……シェユラス・ロフト……全てが繋がった時、ひとつの物語が終わり、そして始まる……<BR>
<b><a href="novel/200112/18123055/sh_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow07.htm">影の騎士 第七話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/3/27(木)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>偽の“影の騎士”の凶行はなおも続く…………今回の標的は親衛騎士、彼の警護に向かったショーネルを待っていた者とは……！<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。さて、物語は終結に向かいます！　……でも、クリックさんってここで登場だったのか……（って、作者が言うことでもないが……（苦笑））<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>殺戮を繰り返す偽者と、その影に暗躍する者たち。そして影と“影”がぶつかり合い、物語は終焉に向け大きく動く……<BR>
<b><a href="novel/200112/18123055/sh_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow06.htm">影の騎士 第六話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/3/22(土)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>先の会戦に、辛くも勝利したフォーサイト……その会戦の余韻覚めやらぬ中、宮中の人々は再び“影の騎士”に思いを馳せる……まさに、その時……<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。トルヴシティ王国との一戦を終結した人々の様々な策動・蠢動をはじめます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>再びポルとともに旅に出たシェアナ。話はいよいよ佳境に入っていきます。<BR>
<b><a href="novel/200112/18123055/sh_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow05.htm">影の騎士 第五話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/3/11(火)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>トルヴシティ侵攻に、フォーサイトは全軍の過半数を動員した国王親征で対抗しようとする。“影の騎士”シェアナは間に合うのか？ ……そして、彼女等が動く時……<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。さてさて、いよいよ戦記らしい場面が出て来ます。戦場での……そして、戦場外での人々の活躍をご覧下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>戦神の騎馬が見守る中、地に空に魔法機械が入り乱れ、数多の血が流される…………そして……<BR>
<b><a href="novel/200112/18123055/sh_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow_ex.htm">影の騎士 外伝</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/3/6(木)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“影の騎士”シェアナの愛馬であるシャーフィール。金属生命体であり意志を持って生きてきた彼の半生……<BR><B>【コメント】 </B>ここへの転載を少し迷ったのですが……“彼”の半生を皆様はどうご覧になられますか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>この話を読めば、きっとあなたも“彼”がいとおしくなると思います……<BR>
<b><a href="novel/200112/18123055/sh_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー 戦記 <BR>【種別】 （変身）<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow04.htm">影の騎士 第四話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/3/3(月)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>久しぶりにホルトの谷に里帰りしたシェアナ。ポルとシャーフィールを静養させている合間にファルト老から頼まれたものを買い出しに町に出た。そこで彼女を待ちうけていたものは……<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。今回は、戦いを離れて平穏な一時を過ごすシェアナのお話です。でも、ただ平穏無事に……はなってくれないようで……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>思いがけない人物との再会。しかし、それは嵐の前の静けさにも似て……<BR>
<a href="novel/200112/18123055/sh_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow03.htm">影の騎士 第三話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/2/28(金)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>シェアナはある寂れた町へ訪れた。そこには、意外な人との再会、驚くべき事態、思いも寄らぬ出会いが彼女を待っていた。<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。いよいよ「影の騎士」の伝説が広がり始めます。今回は、異形の騎士同士の対決です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「影」対「陰」、二人の騎士の戦いの結末は……？　夜夢さんのファンタジー戦記、第二部突入！！<BR>
<a href="novel/200112/18123055/sh_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow02.htm">影の騎士 第二話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/2/20(木)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『影の騎士』伝説の出現は、ある者達に不安、恐怖、あるいは希望、歓喜、そして後悔をもたらしてゆく……その中で、彼が訪れたのは…………<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。以前の作品を読んでくれた方も、そうでない方も楽しんでいただけるのであれば、幸いなのですが……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>野盗に追われる吟遊詩人の前に現れた、怪異なる漆黒の騎士の正体は……？　夜夢さんのファンタジー戦記、早くも第二話！！<BR>
<a href="novel/200112/18123055/sh_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/shadow01.htm">影の騎士 第一話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/2/16(日)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>騎士シェユラスは死の淵から蘇った……その真実を知る為に……後世、伝説として語り継がれた『影の騎士』の真相は……<BR><B>【コメント】 </B>以前、「眠夢の夢文庫」に寄稿させて頂いた同名の作品の改訂版です。以前の作品を読んでくれた方も、そうでない方も楽しんでいただけるのであれば、幸いなのですが……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>奸計に嵌められ、愛馬とともに千尋の谷へと落とされた騎士の運命は……？　夜夢さんのファンタジー戦記、堂々開幕！！<BR>
<a href="novel/200112/18123055/sh_title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 異世界ファンタジー <BR>【種別】 変身<BR>【キーワード】 メカ？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress16.html">ミストレスと奇妙な仲間達〜その１６</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2003/1/18(土)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ドクトルこと、沼池教授の元に一通の手紙が届いた。それが全ての始まりだった・・・・・・<BR><B>【コメント】 </B>今回は、ドクトル編（狗美さん編）です。今回の話は色々と仕掛けが仕込んでありますが、そんなことには関係なく楽しんで頂ければ幸いなのですが・・<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さて、今後の展開が楽しみです。でも、取り立ては容赦なしですか。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法 薬品<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress15.htm">ミストレスと奇妙な仲間達〜その15</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/12/18(水)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>・・・・・・“いん　ざ　びぎにんぐ”なお話“ぱーと　つー”・・・です。（笑）・・・「ミストレスハウス」に駆け込んだ彼女の運命は・・・・・・<BR><B>【コメント】 </B>ミストレスシリーズ本編もかれこれ十五作目、最初の頃はここまで続くとは思わなかったなぁ・・・ともあれ、今回も当文庫作品としては反則技（？）かな・・・<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ミストレス、ついに１周年！　波瀾万丈な一年でした。さて、今回のお話は、「こう」に関する話題でございます………<BR>
<I>ミストレス設定集が更新されました！　</I><b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></b>　</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法 変身 薬品<BR>【キーワード】 異形（翼？） ♀→♂</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress14.htm">ミストレスと奇妙な仲間達〜その14</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/11/20(水)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレスハウス”を訪れた稲生は、そこで奇妙な人達と出会うことに……<BR><B>【コメント】 </B>久し振りのイーナ短編です。封妖編のイーナも良いけど、こう言うイーナも良いでしょう……？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>イーナちゃん、ちょっと一息ティーブレイク…………でもなんか不幸？<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena06.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第六話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/11/10(日)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真夏の空……それを振り仰ぐ叢雲姉弟の目前に舞い降りたもの……それは姉弟に新たなる力をもたらす。（……と言うのは微妙に間違っています。）<BR><B>【コメント】 </B>さて今回は、第五話で驚嘆して頂いた‘ある方’の種明かし編……になっております。そして、一部の方には待望の‘あの方’の登場も……！（……って、これだけだと意味不明……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ますます熾烈を極める対封妖戦。三人の魔法少女たちの運命やいかに？<BR>
<b><a href="novel/200112/18123055/title.htm">【「ミストレスと奇妙な仲間たち」のシリーズタイトルはこちら】</b></a>（‘うさ’のイラストが追加されました！）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress13.htm">ミストレスと奇妙な仲間達〜その13</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/10/27(日)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>その日の“ミストレスハウス”には、とても奇妙なお客様が現われて……<BR><B>【コメント】 </B>ついに、ついに書いてしまった……と言うのが今の心境……“ミストレスハウス”ってこう言う店なんです。（良くも悪くも……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>“ミストレスハウス”の常連さんには、こんな人たちもいるのです。またひとつ謎が解けたっ！（……のか？）<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法？ 薬品<BR>【キーワード】 異形 華代ちゃんシリーズ番外編 ハンターシリーズ番外編</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress12.htm">ミストレスと奇妙な仲間達〜その12</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/10/27(日)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>その晩、“ミストレスハウス”に起こった事件が全ての始まりであった……<BR><B>【コメント】 </B>今回は、ある意味反則技と言えるのかも知れない……ともあれ、ラストが文庫における某人気作と被ってしまったことは、ナントモハヤ……と言う所ではあります。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ネタバレになりそうなので、多くは語りませんが……‘ひぃ’さんのゲームソフト、わたしもプレイしてみたいです。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法？ 薬品 再転換<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena05.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第五話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/9/29(日)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イーナが倒され、封妖の魔の手はフレイに迫る。たった一人で戦いに挑むフレイは絶体絶命の危機に・・・その時、最強の味方がその場に現われる！（・・・と言うのは微妙に間違っています。）<BR><B>【コメント】 </B>読者の方に衝撃を与えた前回ですが、今回も衝撃を受けて頂きます！（・・・って、衝撃を受けて貰えない可能性が高いかも・・・・・・）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>な、なんと！　味方が現る！　そして、フレイのショータイとは!?(て、分かっている人多いと思う……)<BR>
<a href="novel/200112/18123055/title.htm"><b>【ミストレスシリーズのタイトル＆公開設定集はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress11-2nd.htm">ミストレスと奇妙な仲間達〜その11（改訂版）</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/9/28(土)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ミストレスの言い付けで、”ねこ”はとある町へとお使いに行くことになり・・・<BR><B>【コメント】 </B>今回は、”ねこ”の『初めてのお使い』なお話です。感想掲示板でご指摘を受けましたので、少し書き直してみました。（暮／本当にほんの少しだけです。）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>訂正版との差し替えです。すこぉ〜し変わった部分を探し当てるのも一つでは？<BR>
<!-- <B>【お知らせ】設定集が更新されました！</B>--><B><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身 薬品<BR>【キーワード】 **耳 ♀→♂？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress11.htm">ミストレスと奇妙な仲間達〜その11</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/9/10(火)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ミストレスの言い付けで、“ねこ”はとある町へとお使いに行くことになり……<BR><B>【コメント】 </B>今回は、“ねこ”の『初めてのお使い』なお話です。ちょっとクロスオーバーな作りになっていますが、あまりお気になさらず楽しんで頂ければ幸い……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>多忙なミストレスたちの代わりに、“ねこ”が隣町までお届けもの……はてさて、どうなりますやら。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 薬品 変身<BR>【キーワード】 ＊＊耳 ♀→♂？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena04.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第四話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/8/11(日)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>稲生を狙う次なる刺客——第四の封妖テンジュツ・・・その能力にイーナとフレイは圧倒される・・・そして、遂にイーナは彼奴の牙に倒れる。（・・・と言うのは微妙に間違っています。）<BR><B>【コメント】 </B>久し振りの封妖編です。今回のラストはちょっとショッキングかも・・<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法少女、イーナに危機が訪れる！　この先やどうなるか！？激白の第四話です！<BR>
<a href="novel/200112/18123055/title.htm"><b>【ミストレスシリーズのタイトル＆公開設定集はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress10.htm">ミストレスと奇妙な仲間達〜その10</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>どら</B>さん)</TD><TD>2002/7/29(月)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>……“いん　ざ　びぎにんぐ”なお話です。<BR><B>【コメント】 </B>ミストレスシリーズ中最強の存在が登場します！　……って言うのは関係なく、彼女の意外な一面に驚いていただけたら幸い……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>回を重ねて第１０話。今回は、『ミストレスハウス』開店直前のエピソードです。<BR>
（お知らせ：公開設定集、追加＆変更されました）<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身 薬品<BR>【キーワード】 異形（翼？ 水掻き？） ♀→♂</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress9.htm">ミストレスと奇妙な仲間達〜その９</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/7/12(金)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレスハウス”のとある一日を描いた作品です。<BR><B>【コメント】 </B>今回、ミストレスシリーズ中二番目の美女（？）が登場します……しかし、今回は少々キワドイ描写が……（時期外れの時事ネタってのは少し虚しいかも……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>目が覚めると、おなかの上に“ねこ”がのっかっていた……（笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身？<BR>【キーワード】 異形（ケモノ耳……）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena03.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第三話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>どら</B>さん)</TD><TD>2002/6/23(日)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>二体の封妖を倒し、平穏な日常を取り戻したかに見えた稲生に第三の封妖の襲撃が！・・・イーナの危機に、最高の戦友が駆け付ける。（・・・と言うのは微妙に間違っています。）<BR><B>【コメント】 </B>何故、魔法戦士なのか？と言うと・・・少女と言うには、薹（とう）が立っているからで・・・（S.B.hit!）・・・・・・（S.F.／では、私の華麗なる活躍をお楽しみに・・・！）　<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回の封妖は、結構手間取っていました。敵か味方か、魔法戦士の正体は！？　そして、やっぱりイーナが最強（笑）<BR>
どらさんが描いた絵も見逃せません！白熱(?)の第三話をご堪能あれ〜<BR>
<b><a href="novel/200112/18123055/title.htm">【ミストレスシリーズのタイトル＆公開設定集はこちら】</a><A HREF="novel/200112/18123055/e-ena01.htm">【第一話はこちら】</A> <A HREF="novel/200112/18123055/e-ena02.htm">【第二話はこちら】</A></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 ミストレスシリーズ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena02.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第二話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/6/7(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>封妖の正体を知り、封妖との対決の決意を新たにしたイーナに第二の刺客が襲い掛かる！（……と言うのは微妙に間違っています）<BR><B>【コメント】 </B>十二封妖編の第二羽……じゃなくて、第二話です。最後のあの展開は、この手のお話のお約束でしょう（これ、次回の伏線とも言う……）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>御空神社の宮司が語る、封妖たちの由来とは？　そして、“彼ら”はイーナに的を絞った……<BR>
<b><a href="novel/200112/18123055/e-ena01.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女（ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/e-ena01.htm">電光の魔法少女エレクトリック・イーナ　十二封妖編第一話</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/5/15(水)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いにしえに封じられた妖が開放されてしまった！　それを知った稲生少年は正義に燃えて立ち上がる！（……と言うのは微妙に間違っています）<BR><B>【コメント】 </B>「ミストレスシリーズ」に出演しているイーナの新シリーズです。物語の色合いが少し違いますが、お楽しみくだされば幸い……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>電気系魔法少女のシリーズがスタート！　おおっ、イーナちゃんが普通に魔法少女してる……（笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【ミストレスシリーズのタイトル＆公開設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身 魔法<BR>【キーワード】 魔法少女 （ミストレスシリーズ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress8.htm">ミストレスと奇妙な仲間達〜その８</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/5/5(日)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>某大学の迷物（？）教授……その助手のとある一日の物語…………<BR><B>【コメント】 </B>ドクトル編第二弾です。イーナ編と併せて御笑覧下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>……一方その頃、狗美さんは（まんまですやん……笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身？ 薬品<BR>【キーワード】 異形（ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress7.htm">ミストレスと奇妙な仲間達〜その７</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD><B>画</B>(<B>どら</B>さん)</TD><TD>2002/5/5(日)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>某市に遊びに来た稲生少年の身に振りかかる運命とは……！？<BR><B>【コメント】 </B>今回はイーナ編です。稲生少年の災難はまだまだ続き…………そうですね。この分だと……（カハイタワラヒ）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>天が呼ぶ！　地が呼ぶ！　人が呼ぶ！　悪を倒せと…………あ、いや、同じ「電気系」のヒトだから（笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身？<BR>【キーワード】 魔法少女 年齢変化 オレっ娘？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress6.html">ミストレスと奇妙な仲間達〜その６</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/4/4(木)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>“ミストレスハウス”の面々のお出掛け編です。<BR><B>【コメント】 </B>今回第二の見せ場は、“ふく”の最大にして最強（最凶？）の特殊能力の発動でしょう！（・・・ッテイッテイインダロウカ？）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>"ねこ"ちゃんのお出かけ・買い物編です。しかし、お約束ながらそこまで翻弄されるか。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身？<BR>【キーワード】 異形（ケモノ耳・・・） 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress5.html">ミストレスと奇妙な仲間達〜その５</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/2/16(土)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>今日も今日とてミストレスハウスの面々は、頑張っています。今回のお客様は、ミストレスの昔馴染みの…………<BR><B>【コメント】 </B>先の目論みも無くこんな物を書く私は、チャレンジャーなのか無謀者なのか……？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>まほーしょーじょにボコられる犯罪者……これだけにはなりたくはない（笑）。<BR>
<b><a href="novel/200112/18123055/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 アイテム 可逆？ 変身 魔法 薬品<BR>【キーワード】 魔法少女 年齢変化 オレっ娘？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress4.html">ミストレスと奇妙な仲間達〜その４</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/2/16(土)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>某大学の迷物（？）教授……その隠された素顔とは！？<BR><B>【コメント】 </B>今回は、“ミストレスハウス”の真の常連の一人にスポットを当ててみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>夜夢さんが「ミストレス〜」の粋で不思議な仲間たちをシェアワールド化してくれました！<BR>
　くわしくは、<b><a href="novel/200112/18123055/title.htm">【シリーズタイトル＆公開設定集】</a></b>を見てください。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身？ 魔法？ 薬品<BR>【キーワード】 異形（獣化＆ケモノ耳）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress3.html">ミストレスと奇妙な仲間達 その３</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/1/21(月)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ミストレスハウス最大の危機!!・・・凶悪犯の手に捕らえられた”ねこ”の運命は・・・（・・・と、思いきや・・・）<BR><B>【コメント】 </B>意外な程に早く三話目をお送りすることが出来ました。今回、割を食ったのは一体、誰と誰と誰でしょう・・・？（トリアエズ、イチバンハワカリキッテイルガ・・・・・・）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>凶悪犯の運命はいかに。。。オールキャストでお送りします。<BR>
<b><a href="novel/200112/18123055/mistress.html">【その１】</a></b><b><a href="novel/200112/18123055/mistress2.html">【その２】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身？ 魔法？ 薬品<BR>【キーワード】 異形（ケモノ耳） ダーク？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress2.html">ミストレスと奇妙な仲間達　その２</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/1/15(火)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>そこは奇妙な人々のいる不思議なお店・・・この店の一員になってしまった少女——“ねこ”・・・彼女の一日を追う・・・<BR><B>【コメント】 </B>取り敢えず書いてみた続きです。まぁ・・・少しばかり細工があるのですが・・・（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ケモノ耳の場合、髪を洗うときに耳に水は入らないのだろうか……？素朴な疑問でした。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身 薬品<BR>【キーワード】 **耳 ♀→♂？ シェアードワールド</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200112/18123055/mistress.html">ミストレスと奇妙な仲間達　その１</a></B></TD><TD><B><A href="mailto:m-yoko@giga.ocn.ne.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/12/18(火)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>そこは奇妙な人々のいる不思議なお店・・・この店の一員になってしまった彼は・・・？（・・・って、あらすじになっているんだろうか・・・？）<BR><B>【コメント】 </B>余りに突発的に思いついた話ですが、一応始めて書く現代劇・・・なんですけどね。さて、この話、続きがみたいですかね・・・？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>うまい話には裏がある？……誰だ？こんな話ならついていきたいっていう人は？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 魔法？ 変身 薬品<BR>【キーワード】 **耳 ♀→♂？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji2_03.htm">もう一人の“虹の瞳”の物語　第三話“もう一つの・・・”</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/10/26(金)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>天使族の姿になってしまったレイテス……身体に慣れる為にと魔法院長から休暇を貰う事になりましたが……<BR><B>【コメント】 </B>やっとお送りできました……“もう一つの虹の瞳”の其之三です。<BR>
何が“もう一つ”なのかは読んでみてからのお楽しみと言う事で……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のぞみが〜かなうなら〜、つばさを〜ください〜♪　……ってな歌がありましたが、あったらあったでいろいろと気苦労が多いようです。<BR>
　やっぱりレイテス君ってば、……不幸？<BR>
<b><a href="novel/rainbow/niji2_01.htm">【第一話はこちら】</a></b><b><a href="novel/rainbow/niji2_02.htm">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界ファンタジー <BR>【種別】 変身？ 可逆 魔法<BR>【キーワード】 虹の瞳 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji2_02.htm">もう一人の“虹の瞳”の物語　第二話彼の方との出会い</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/9/16(日)</TD><TD>57KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ニフォーラ魔法院長の施術の影響により、レイテスの女性神官としての日々が始まった・・・そんなある日、彼女はある人物に助けられるのだが・・・<BR><B>【コメント】 </B>もう一つの“虹の瞳”」の続編です。今回もレイテス君は遊ばれてます・・・彼の方の出現が救いになると良いんですが・・・（救いにならない気がしてならない（苦笑））・・・・・・それにしても、また初期の構想のラストにまで辿り着けなかった・・・もう少し続きます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回もいろんな出来事や家人の計略(笑)に巻き込まれ、一部で話題の"レイテス君とっても不幸説"にさらに信憑性が増しました。そして、TSっ娘のうれしはずかしな不幸は読者にとっては蜜の味、なのです(笑)。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 可逆 変身 魔法<BR>【キーワード】 虹の瞳 異形 天使娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji2_01.htm">もう一人の“虹の瞳”の物語　第一話</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/8/16(木)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B> セオミギア神殿に仕える神学士レイテス、平凡な一神学士であった彼を変える事となったのは、たった一冊の書籍の発見からだった……。<BR><B>【コメント】 </B> 原点回帰と言う意味もこめて書いてみました……先の“虹の瞳”の物語からかなり時代を経た頃のお話、の筈なのですが……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B> 前作<b><a href="novel/rainbow/niji01.html">『虹の瞳と呼ばれて』</a><a href="novel/rainbow/niji02.html">『虹の瞳を得たのは』</a></b>から数百年後を舞台に、新たな伝説がスタートします。<BR>
 しかし、どんな世界でも主人公の母親と事情通の家政婦さんは最強やね……。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 ファンタジー <BR>【種別】 変身 魔法<BR>【キーワード】 虹の瞳</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200108/02205840/ladybringer08.html">レディ・ブリンガー第八話“荒野に笑いしは…”</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2001/8/2(木)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B> この物語は、呪われた魔剣『レディ・ブリンガー』に出会った人々の被る数々の災いを記したものの一つである。<BR>
 今回の舞台は、人も訪れぬ荒野での物語……<BR><B>【コメント】 </B> ここに寄稿させて貰うのは、一応初めてになります。思い付きと勢いだけで一晩の内に書き上げた拙作です。楽しんで貰えれば幸い。いきなり第八話なんですが良いんでしょうか……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B> 知る人ぞ知る魔剣『レディ・ブリンガー』の物語、文庫初登場です。<BR>
　<b><a href="novel/rainbow/niji01.html">『虹の瞳と呼ばれて』</a></b>でおなじみ、夜夢さんお得意の異世界奇譚をお楽しみください。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 ファンタジー <BR>【種別】 アイテム 変身 魔法<BR>【キーワード】 レディ・ブリンガー</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji02.html">虹の瞳を得たのは</a></B></TD><TD><B><A href="mailto:cmnt0369@try-net.or.jp">夜夢</a></B> さん </TD><TD>(イラストなし)</TD><TD>2000/2/25</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一介の書院付神官であるラティルはある大きな苦悩に悩まされていた。その悩む彼を見兼ねた書院長は一計を謀って…。<BR><B>【コメント】 </B>前作、<a href="novel/rainbow/niji01.html">“虹の瞳と呼ばれて”</a>より半年ほど前のエピソードです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>男女二つの身体を持つ神官ラティルの物語です。今回は「虹の瞳」と呼ばれるラティルが女性としての身体を得るに至った経緯が描かれています。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 異世界 ファンタジー <BR>【種別】 身体交換 魔法<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/rainbow/niji01.html">虹の瞳と呼ばれて</a></B></TD><TD><B>夜夢</B> さん </TD><TD>(イラストなし)</TD><TD>1999/8/30</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yamu">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>神殿都市‘セオミギア’で神殿書院付の神官を勤めているラティル＝コアトリア。‘剣撃ち（つるぎうち）のラティル’との二つ名を持つ彼の、女性としての二つ名を与えられることになったエピソードです。<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(174.129.228.67) , Competence : -1 -->
</BODY></HTML>
