<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/osakana.html">おさかな転換</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/1/5(金)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>魚、ロリータ、セレブ、謎のトランペッター、不思議の国の少女、野菜などが共演するスペクタブルドタバタコメディ、第一弾！<BR><B>【コメント】 </B>久しぶりの作品です。とりあえずはっちゃけてます。<BR><B>【日比野 さんのオススメ作品】</B> <A HREF="../novel/perky_girl/title.html">いんまなあの子はPerky☆Girl！</A> <FONT SIZE="-1">(米津さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>よい子のみんな、あの愉快なお歌に乗せて、楽しい楽しいお話の始まりだよ〜</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 ボクっ娘 コスプレ（家族） 女装（家族）</TD></TR></TABLE><BR><BR>『日比野』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/katatumurinisugar.htm">かたつむりにシュガー</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2010/6/23(水)</TD><TD>235KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>常に非日常を求め、精力的に活動する渚。さすらいの女の子を保護し、通りすがりの女子大生に無理矢理大学に入学させられる。そして凶暴な野犬の発生、大学教授の汚職と、様々な問題が渚を包む。さあゆけ！　オバレンジャー！<BR><B>【コメント】 </B>かたつむりに塩をかけると、浸透圧の関係で脱水して縮みます。お砂糖でも分子量が大きくて縮みにくいとは思いますが、たぶん縮みます。あえてお砂糖という天邪鬼さ。あとマザーグースあたりがタイトルの意味だったりなかったり。<BR>
科学チックで長い小説ですので、時間があって気が向いた時にどうぞ。<BR><B>【日比野 さんのオススメ作品】</B> <A HREF="../novel/200312/05062153/yumenotuduki_index.html">夢の続き</A> <FONT SIZE="-1">(Taika Yamaniさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>主人公・渚をはじめ魅力的な登場人物たちの織り成す非日常な日常の物語。ぜひとも最後までお読み下さい。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 SF <BR>【種別】 変身<BR>【キーワード】  女装 年齢変化 百合？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/osakana2.html">おさかな転換　二番〜変態という名の称号〜</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/2/14(水)</TD><TD>50KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>変態、ロリータ、セレブ、謎のトランペッター、不思議の国の少女、野菜などが共演するドラマティックアクションコメディー、第二弾。<BR><B>【コメント】 </B>書いた自分が見てもくだらない作品ですが、くだらないのが売りなわけで……そんな作品でも読んでくださる方がいればと思っています。<BR><B>【日比野 さんのオススメ作品】</B> </a>ミィちゃんと呼ばないで（<a href="../novel/200203/05130136/fit.html">fit…</a>/<a href="../novel/200203/05130136/fit2-1.htm">1</a>/<a href="../novel/200203/05130136/fit2-2.htm">2</a>/<a href="../novel/200203/05130136/fit2-3.htm">3</a>/<a href="../novel/200203/05130136/fit2-4.htm">4</a>/<a href="../novel/200203/05130136/fit2-5.htm">5</a>/<a href="../novel/200203/05130136/fit2-6.htm">6</a>/<a href="../novel/200203/05130136/fit2-7.htm">7</a>/<a href="../novel/200203/05130136/fit2-8.htm">8</a>）<a> <FONT SIZE="-1">(薪喬さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おさかなは見事、変態に出世しました。出世魚だったのか（違）<BR>
<b><a href="../novel/200203/23203640/osakana.html">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】  変身 可逆<BR>【キーワード】 コスプレ（家族が） ボクっ娘 女装（家族が）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/osakana.html">おさかな転換</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/1/5(金)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>魚、ロリータ、セレブ、謎のトランペッター、不思議の国の少女、野菜などが共演するスペクタブルドタバタコメディ、第一弾！<BR><B>【コメント】 </B>久しぶりの作品です。とりあえずはっちゃけてます。<BR><B>【日比野 さんのオススメ作品】</B> <A HREF="../novel/perky_girl/title.html">いんまなあの子はPerky☆Girl！</A> <FONT SIZE="-1">(米津さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>よい子のみんな、あの愉快なお歌に乗せて、楽しい楽しいお話の始まりだよ〜</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 ボクっ娘 コスプレ（家族） 女装（家族）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_08.html">雨時々時雨　第八話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/13(水)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨は克己とのお墓参りデートを計画する。<BR><B>【コメント】 </B>最終話です。特にあまり変化のない内容かもしれません。ぶっちゃけ何か衝撃的なことが起こったりとかはまったくありません。でもこういう終わり方もいいかなと……。よくないですか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>雨は克己と墓参りに行くが、お互いに条件を出した。雨が真っ赤になった、その条件とは……？<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_07.html">雨時々時雨　第七話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/7(木)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨の心境に変化が訪れる……。そして２０年後の親友と初めて会う。<BR><B>【コメント】 </B>大分時間があいてしまいました。申し訳ありませんでした。次の話で終わりです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お買い物をすませて上機嫌の真昼。やっぱり真昼は、雨のよき理解者なようです。<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_06.html">雨時々時雨　第六話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/6(火)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨はショックを受けながらも、母としての想いに目覚め始める。<BR><B>【コメント】 </B>説明臭いです。申し訳ないです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>佐々木家の中で雨が「藤咲雨」として存在するには、何が必要なのか？　それは……<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 理解ある娘 年齢変化 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_05.html">雨時々時雨　第五話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/16(水)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>文化祭を中心に雨は振り回され、そして心境の変化が現れる。<BR><B>【コメント】 </B>文化祭っていいですよね。僕は大好きです、あの雰囲気。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>それなりに先生としての貫禄(？)が出てきた雨。その雨が文化祭の準備中、意外なものに遭遇する。<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_04.html">雨時々時雨　第四話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/1(火)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨は初めて学校に教師として通います。<BR><B>【コメント】 </B>前話までとはちょっと違うかんじになっていると思います。ＴＳってかんじじゃないですね……。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>本当は似たような年齢の生徒達を相手に奮闘する雨。初めての割にはいいセンいってます。<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_03.html">雨時々時雨　第三話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/20(木)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨は真昼と一緒に家事をしてみます。お馴染みのお風呂シーンもあります？<BR><B>【コメント】 </B>お風呂のシーンが今までの作品とは逸脱している気がします。普通は自分の裸を見て恥ずかしいみたいな展開ですが……。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ふとしたことから、現在自分が置かれている状況は現実なんだと強く思い知らされる雨。<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_02.html">雨時々時雨　第二話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/11(火)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>朝起きてもやっぱり状況は変わらず、現代の機械にあたふたな雨。<BR><B>【コメント】 </B>１６→３６なこの話。意外と書いてて楽しかったりします。年上、人妻好きはぜひ！なんて。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>現代のハイテクメカに雨、悪戦苦闘！<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 理解ある娘 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/ame_01.html">雨時々時雨　第一話</a></B></TD><TD><B><A href="mailto:kuu_squirrel@yahoo.co.jp">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/5(水)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>主人公“雨”はごく普通の高校一年生。でもふとうたた寝して起きると、世界は一変していた。<BR><B>【コメント】 </B>読むと期待はずれかもしれません……。冒頭部分だけですが、これからはもっと異色になっていくかと。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>作品タイトルがなんともうまいですね。TSに加えてタイムスリップもありということで、どんな展開になるのか楽しみです。<BR>
<a href="../novel/200203/23203640/ame_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 人格転移？<BR>【キーワード】 年齢変化 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200305/04184146/relay6.html">小さなお守り - 最終章 『思い出のお守り』</a></B></TD><TD><B><A href="mailto:relaynovels@freeml.com">日比野</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/22(月)</TD><TD>75KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_relay_novel.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>遠い日の思い出は、また目の前で繰り返される。同じ境遇の二人の物語。<BR><B>【コメント】 </B>最終話です。少々長いですが、お付き合いお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お守りによって変わってしまった少年。彼は、お守りを知るものと出会う。<BR>
<B><A HREF="../novel/200305/04184146/title.html">【シリーズタイトルはこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身<BR>【キーワード】 少年少女文庫・リレー小説実行委員会主催作品</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/seitaro.html">清太郎の秋</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2003/5/14(水)</TD><TD>57KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>時は平安の末期。京の都に住んでいた、清太郎という男の話。清太郎はある二人の女と出会い、その運命を大きく変えていく。<BR><B>【コメント】 </B>時代物ってあんまりありませんでしたよね。だから作っちゃいました。ＴＳ要素のみは辛かったので、シリアスな物語です。これを楽しむには、深いことは考えてはいけません！間違いも見過ごしましょう。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>最後が少し物悲しいです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 時代 歴史 <BR>【種別】 神秘 変身<BR>【キーワード】 入浴 ♀→♂ オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/heaven2.html">天国か地獄　〜花嫁編〜</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2003/3/10(月)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>正幸といるかと深雪は仲良し三人組み。そして今日、正幸と深雪の結婚式が行われるが……。<BR><B>【コメント】 </B>ココロちゃんについても書きたい。でも書くと話がややこしくなるからしない。
<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>天使のようで、実は悪魔だったりしちゃうココロちゃんが叶えた願いとわ？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/heaven.html">天国か地獄</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2003/2/2(日)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新キャラ悪魔天使ココロちゃんの初短編<BR><B>【コメント】 </B>内容は……。題名は……。ああ、嫌な汗が……。あんまりＴＳっ気もないかも。
<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>次の日比野さんの作品は、不幸に陥れる悪魔……のはずだけど？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘<BR>【キーワード】 強制 親友萌え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/snow_brillant.html">ＳＮＯＷ　ＢＲＩＬＬＩＡＮＴ</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2003/2/2(日)</TD><TD>59KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>三人は新たな一歩を踏み出した。そして踏み外した！<BR><B>【コメント】 </B>『ＳＮＯＷ　ＢＲＩＧＨＴ』の続編です。前の三作もぜひ読んでくださいっ！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>彼女の中に、三つの心。その一つの心は、男として生きてきた記憶。その一つの心は、友達として辰馬と生きてきた記憶、もう一つは…<BR>
<B>【前作はこちら】<a href="../novel/200203/23203640/snow_bright.html">ＳＮＯＷ　ＢＲＩＧＨＴ</a> <a href="../novel/200203/23203640/snow_bright02.htm">空に咲く花</a> <a href="../novel/200203/23203640/tatsuma.html">辰馬がゆく</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 アイテム  医術<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/tatsuma.html">辰馬がゆく</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/8/22(木)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>三人は去年、夏に辰馬の実家に行った。そして今年も…。<BR><B>【コメント】 </B>読んで！！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ちょいと辰馬くん、あんたいったい何者よ？　う〜ん、何気に設定がおもしろい。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 アイテム 医術<BR>【キーワード】 強制 水着</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/snow_bright02.htm">空に咲く花</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/8/5(月)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自分の名前の由来を知っていますか？<BR><B>【コメント】 </B>今回は（ ）で読みを説明しておりません。気分に応じて読み方を変えてくださいね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>美玖里ちゃんの一途な思いが、痛いくらいに伝わってきます……。
<BR>
<b><a href="../novel/200203/23203640/snow_bright.html">前作『ＳＮＯＷ　ＢＲＩＧＨＴ』はこちら</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 アイテム 医術<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/snow_bright.html">ＳＮＯＷ　ＢＲＩＧＨＴ</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/7/20(土)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雪菜はいつも勝手に何かをやってしまう辰馬のおかげで、今度は芸能界のオーディションを受けろと言われる。それによって…、<BR><B>【コメント】 </B>体の変化はない？んでしょうね。でもどうなんでしょう、男→女にはなってる？のかな。よくわからないです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>何故か強引にオーディションを受けることになった雪菜に、驚愕の事実が判明する————ん？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 アイテム 医術<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/hill_05.html">光る丘は　第五章　理想と現実の狭間</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/7/1(月)</TD><TD>42KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>　憲明と哲と章音と真紀の、三角ならぬ四角関係。そんな話です。<BR><B>【コメント】 </B>この小説にアクション的要素はいらないのかなあ、なんて書いているとき思ったりしてます。どうなんでしょうね。とってつけたみたいなのがちょっと嫌かもしれません。って、読んでみないとわからんですよ。というわけで読んでみてください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>少しだけ章音→中嶋へ戻れた主人公。章音は、原本に思いを寄せるが・・・・　ついに強敵が出現！　章音の運命やいかに！　今頃、作者のペンネームと主人公の名前が同じなことに気づく。<BR>
<b><a href="../novel/200203/23203640/hill_01.html">【序章はこちら】</a><a href="../novel/200203/23203640/hill_02.html">【第二章はこちら】</a><a href="../novel/200203/23203640/hill_03.html">【第三章はこちら】</a><a HREF="../novel/200203/23203640/hill_04.html">【第四章はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 魔法少女</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/hill_04.html">光る丘は　第四章　記憶の旅</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/6/9(日)</TD><TD>54KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>哲の記憶救出と、その後の章音の生活を描いた究極のラブコメディ…、ではありません。見る人は臭さを覚悟してください。<BR><B>【コメント】 </B>とりあえず今回のテーマは孤独。どっかにいるでしょう、無性に明るい奴。心の中ではいったい何を考えているのかわからないタイプですよね？自分でも書いていて、孤独ってなんだろうと考えてしまいました。みなさんもこれを読んで、考えていただけると光栄です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>『孤独』は人の心に最大の負担を掛ける。仲間はその『孤独』の負担をなくす友・・・　哲は仲間というものを学ぶ。そして章音は真紀ちゃんに自分の正体を明かす・・・・さて、この先どうなるのでしょ？　<BR>
<b>【お知らせ】運営委員のミスで 掲載が３週間以上遅れました。ここにお詫び申し上げます。</b><BR>
<b><a href="../novel/200203/23203640/hill_01.html">【序章はこちら】</a><a href="../novel/200203/23203640/hill_02.html">【第二章はこちら】</a><a href="../novel/200203/23203640/hill_03.html">【第三章はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 魔法少女</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/hill_03.html">光る丘は　第三章　乙女はつらいよ</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/4/12(金)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに初めての戦い。とまどいが多すぎて。そして…<BR><B>【コメント】 </B>う〜ん、まだまだって感じですかね。今回は内容が少し濃いので、ついて行けてないような…。まだまだ始まったばかりの”光る丘は”今後ともよろしくお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回は章音ちゃんに強力な(？)助っ人が登場。これからどういう展開になるのやら、興味津々です。<BR>
<b><a href="../novel/200203/23203640/hill_01.html">【序章はこちら】</a><a href="../novel/200203/23203640/hill_02.html">【第二章はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 ちょっと哲学 魔法少女</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/hill_02.html">光る丘は　第二章　ドキドキ？学園生活</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/3/27(水)</TD><TD>38KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女としての生活を始める章音。しかし様々な困難が章音を襲う。<BR><B>【コメント】 </B>序章より進歩している…と思います。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回もおいしい展開が盛りだくさん。当然お約束のあのシーンも…。それでは第二章、いってみようっ！<BR>
<a href="../novel/200203/23203640/hill_01.html"><b>【序章はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 魔法少女</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="../novel/200203/23203640/hill_01.html">光る丘は　序章</a></B></TD><TD><B>日比野</B> さん </TD><TD>(イラストなし)</TD><TD>2002/3/23(土)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_hibino.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ある程度普通の高校生の章弘に現れた謎の男、そして知らされる世界の秘密。<BR><B>【コメント】 </B>モデルは実は僕自身です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>授業中の昼寝ってなんであんなに気持ちいいんだろう…って自分は何書いてるんだか(笑)。　夢と現実、果たしてどちらが本当の世界なんでしょうね…？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.162.105.241) , Competence : -1 -->
</BODY></HTML>


