<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/gold03.html">ご・お・る・ど！〜ミキの奮闘記〜第三話</a></B></TD><TD><B>yuk</B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/5/5(土)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>道化師たちは今宵も踊る。<BR><B>【コメント】 </B>国家秘密という割にあけっぴろげな人たちが多いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>人、それを「羞恥プレイ」と呼ぶ（笑）。キャラも増えて、ミキちゃんのまわりがますます騒がしくなってきました。<BR>
<b><a href="novel/200611/07223823/gold01.html">【第一話はこちら】</a><a href="novel/200611/07223823/gold02.html">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】  変身 可逆<BR>【キーワード】 ＧＯＡＬＥＤ</TD></TR></TABLE><BR><BR>『yuk』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/middle_story_1.html">THE STORY IN THE MIDDLE 前編</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2007/9/18(火)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>魔王が現れた世界で今、勇者召喚の巫女が立ち上がる。これはそんな世界の裏でうごいたもう一つの物語をも取り込んだ一つの物語。<BR><B>【コメント】 </B>物語には私たちに語られない部分があのではないかと思います。そんな部分を自分で考えるのもいいのではないのでしょうか。<BR><B>【yuk さんのオススメ作品】</B> <A HREF="novel/200207/03224430/roromi_title.html">微妙存在ろろみ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>物語は、その物語の一部を書き記してある。残りの物語は、あなたの"妄想"にお任せ致しましょう。「この世のすべて、はじめは妄想」というぐらいですし（違。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディー 異世界召喚 <BR>【種別】 魔法<BR>【キーワード】 語られない物語</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/gold03.html">ご・お・る・ど！〜ミキの奮闘記〜第三話</a></B></TD><TD><B>yuk</B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/5/5(土)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>道化師たちは今宵も踊る。<BR><B>【コメント】 </B>国家秘密という割にあけっぴろげな人たちが多いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>人、それを「羞恥プレイ」と呼ぶ（笑）。キャラも増えて、ミキちゃんのまわりがますます騒がしくなってきました。<BR>
<b><a href="novel/200611/07223823/gold01.html">【第一話はこちら】</a><a href="novel/200611/07223823/gold02.html">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】  変身 可逆<BR>【キーワード】 ＧＯＡＬＥＤ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/gold02.html">ご・お・る・ど！〜ミキの奮闘記〜第二話</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2007/2/20(火)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>道化師は今日はどんな踊りを見せてくれるのかな？<BR><B>【コメント】 </B>テストというのはどこの世界でも大変ですね。<BR><B>【yuk さんのオススメ作品】</B> <A HREF="../novel/200206/20162303/title.html">The voice of ours</A> <FONT SIZE="-1">(水無月さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ひとおおおお〜つ！（<b>どどどおおおおおぉんっ！！</b>）可逆ＴＳっ娘は〜っ、やたらと元に戻ってはいけぬわぁああああ〜いっ！！（……笑）<BR>
<b><a href="../novel/200611/07223823/gold01.html">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】  変身 可逆<BR>【キーワード】 ＧＯＡＬＥＤ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/gold01.html">ご・お・る・ど！〜ミキの奮闘記〜第一話</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2007/2/12(月)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>さあ、お話を始めよう。<BR><B>【コメント】 </B>最初と最後の意味の解らない文章はタダの趣味です。<BR><B>【yuk さんのオススメ作品】</B> <A HREF="novel/200605/05101055/nijiiro_title01.htm">虹色のトレイル</A> <FONT SIZE="-1">(きりか進ノ介さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ゴールド——それは、人間の最終進化系と考えられる能力者の総称。決してめったに乗らないからもらえる自動車免許のことじゃないぞっ！（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】  変身 可逆<BR>【キーワード】 ＧＯＡＬＥＤ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/niceassist03.html">nice assist 明君の《オーパーツ》</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2006/12/20(水)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人情警官山科とその周りの人々がおりなすハートフルコメディー。これはそんな世界の裏で動いたもうひとつの物語。<BR><B>【コメント】 </B>上のあらすじは多分まちがっています。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>世界の裏で動いている人たちにも都合というものがあるんですよ。たぶん。<BR>
<b><a href="novel/200611/07223823/niceassist00.html">【nice assist 序章はこちら】</a><a href="novel/200611/07223823/niceassist01.html">【nice assist 明君の場合はこちら】</a><a href="novel/200611/07223823/niceassist02.html">【nice assist 夜宵さんと夏流ちゃんの場合はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー コメディ <BR>【種別】 テクノロジー？<BR>【キーワード】 happy</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/niceassist02.html">nice assist 夜宵さんと夏流ちゃんの場合</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2006/12/4(月)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自分に自信がなくてなかなか憧れの先輩に告白できない美和はある日……  これはそんな世界の裏で動いたもう一つの物語<BR><B>【コメント】 </B>完全にギャグになってます。変なところがあってもノリで乗り切ってください。<BR><B>【yuk さんのオススメ作品】</B> <A HREF="novel/kayo_chan/title-ex.htm">「華代ちゃん」シリーズ 番外編＆特別編</A> <FONT SIZE="-1">(さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>はらはら、ドキドキの展開ではなくて、なんでそうなるの！とツッコミたくなるお話です。<BR>
<b><a href="novel/200611/07223823/niceassist00.html">【nice assist 序章はこちら】</a></b><b><a href="novel/200611/07223823/niceassist01.html">【nice assist 明君の場合はこちら】</a></b><BR>
</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー コメディ <BR>【種別】 憑依 魔法<BR>【キーワード】 happy</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/niceassist01.html">nice assist 明君の場合</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2006/11/19(日)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>魔王の脅威にさらされているハイクロードサンベルク国。国中の期待を受け、勇者ライズは魔王の城に挑む。 これは、世界の裏で動いたもう一つの物語。<BR><B>【コメント】 </B>序章の直接の続きになります。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>新米　明君の活躍はいかに。<BR>
<b><a href="novel/200611/07223823/niceassist00.html">【nice assist 序章はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー コメディ <BR>【種別】 憑依 魔法<BR>【キーワード】 happy</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200611/07223823/niceassist00.html">nice assist 序章</a></B></TD><TD><B>yuk</B> さん </TD><TD>(イラストなし)</TD><TD>2006/11/7(火)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yuk">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いろいろな世界を幸せにするための物語です<BR><B>【コメント】 </B>happyend をめざします<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>世界を幸せにする？ために日夜活動している組織の物語です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー コメディ <BR>【種別】 憑依 魔法 可逆<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(3.236.232.99) , Competence : -1 -->
</BODY></HTML>
