<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_10.htm">ヴィスティア　（chapter 10）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/1/1(日)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>二学期。のぞみたち一年Ｃ組の生徒が、休み前と変わらない教室へと集まる。ただ一人を除いて。<BR>
<BR><B>【コメント】 </B>信じているからこそ、チームプレイはうまくいくのです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>揃ったエクセリュートの生み出す新たな力は、不意の強襲をはねのけられるのか？<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR>『ほたる』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201009/16215412/delayed11.htm">仮面ライターディレイド　第１１話『オープン・マイ・ハート』</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2013/4/9(火)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=delayed">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>二人の”つばさ”。互いが互いの立場、そして思いを知ったとき、世界は大きく動き出す。<BR><B>【コメント】 </B>……スーパーヒロインタイムの始まりです（笑）<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200607/02124625/ts_fight_tcg.html">転性遊戯 ～ TenSei ☆ Yu-gi ～</A> <FONT SIZE="-1">(天爛さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>新たな力に目覚めしウィッシュ。ヴィスティアの華やかなコンビネーションとディレイドの旅の軌跡の競演！<BR>
<b><a href="../novel/201009/16215412/delayed_title.htm">【『仮面ライターディレイド』シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 <BR>【種別】 魔法 変身<BR>【キーワード】 「仮面ライダーディケイド」パロディ アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201009/16215412/delayed10.htm">仮面ライターディレイド　第１０話『ふたり』</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2013/3/28(木)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=delayed">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>翼たちがやって来た世界。それは……これまでの「常識」から外れる世界だった。<BR><B>【コメント】 </B>「ディケイド」パロディなのに種別やらキーワードがおかしなことになってます（笑）<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/201101/08222059/catfoods.html">ねこのえさ</A> <FONT SIZE="-1">(石積ナラさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ねじれてもつれた運命に導かれ、翼の変じたつばさはツバサ達と出会う。<BR>
<b><a href="../novel/201009/16215412/delayed_title.htm">【『仮面ライターディレイド』シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 コメディ <BR>【種別】 魔法 変身<BR>【キーワード】 「仮面ライダーディケイド」パロディ アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_16.htm">ヴィスティア【終】　「望みを失わないために、できること」</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/8/29(水)</TD><TD>54KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自分の限界を知ったのぞみ。決意を固めた彼女の行動に、梓たちは……<BR><B>【コメント】 </B>全てを纏めるもの。それは…………生きていくということ。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200505/12003948/title.htm">フェイク☆ガール</A> <FONT SIZE="-1">(MONDOさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>平和のために戦う。それを矛盾だと思いますか？　彼女たちの覚悟の強さを、そして本編最後の晴れ姿をどうぞご覧ください。<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_15.htm">ヴィスティア　（chapter 15）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/8/2(木)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真実を知った、一人の少女。<BR>
自らの過去にけじめをつけるべく立ち向かう、その先にあるのは……<BR><B>【コメント】 </B>頼りにできる人はいますか。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/201009/16215412/delayed_title.htm">仮面ライターディレイド</A> <FONT SIZE="-1">(城弾さん他さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>巻き込めない。放っておけない。優しさの交差する先に、きっと光る未来があると信じて――。<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_14.htm">ヴィスティア　（chapter 14）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/6/17(日)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>のぞみに連れられ、見慣れたイルミネーションを見慣れない場所から鑑賞した梓。彼女の思いを確認した、その場に現れたのは……<BR><B>【コメント】 </B>その決意は、正しいと言い切れますか。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いよいよ大詰め。クリーヴァ、プロヴィとの最後の戦闘は、しかし思わしくない方向へ。<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_13.htm">ヴィスティア　（chapter 13）</a></B></TD><TD><B>ほたる</B> さん </TD><TD><B>画</B>(<B>ほたる</B>さん)</TD><TD>2012/4/29(日)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>　二十年前、志穂が伴侶と共にいた場所。迫りくる危機からのぞみを救うため、約束を果たすべき存在が追跡を開始する。<BR><B>【コメント】 </B>これまでとは風変わりな雰囲気を持つ一話です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前田のぞみの最大の危機に梓たちは――？<BR>
ちなみにドリフト入れてタイムを縮めるには相当の鍛錬が必要……らしい、ですよ？<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_13.htm">ヴィスティア　（chapter 13）</a></B></TD><TD><B>ほたる</B> さん </TD><TD><B>画</B>(<B>ほたる</B>さん)</TD><TD>2012/4/29(日)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>　二十年前、志穂が伴侶と共にいた場所。迫りくる危機からのぞみを救うため、約束を果たすべき存在が追跡を開始する。<BR><B>【コメント】 </B>これまでとは風変わりな雰囲気を持つ一話です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前田のぞみの最大の危機に梓たちは――？<BR>
ちなみにドリフト入れてタイムを縮めるには相当の鍛錬が必要……らしい、ですよ？<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_12.htm">ヴィスティア　（chapter 12）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/3/2(金)</TD><TD>41KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>今日は西風学園の文化祭。こっそり来客として振る舞う瑠美、大学へ行ってみるのぞみ、そして○○○姿の梓。<BR><B>【コメント】 </B>ピンチです。……敵味方共に。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>文化祭なんておいしいイベントを見逃す敵ではな～い！　……見る方も、食べる方も。<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_11.htm">ヴィスティア　（chapter 11）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/1/27(金)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>食の祭典。のぞみは友達とその場へ向かおうとするが、大きな問題がその前に横たわる。<BR><B>【コメント】 </B>……少しは遠慮しなさいっ（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>過ぎたるは及ばざるが如し。でも、それがあなたの良いところ♪　かも。<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 現代 ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_10.htm">ヴィスティア　（chapter 10）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2012/1/1(日)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>二学期。のぞみたち一年Ｃ組の生徒が、休み前と変わらない教室へと集まる。ただ一人を除いて。<BR>
<BR><B>【コメント】 </B>信じているからこそ、チームプレイはうまくいくのです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>揃ったエクセリュートの生み出す新たな力は、不意の強襲をはねのけられるのか？<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_09.htm">ヴィスティア　（chapter 09）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/12/17(土)</TD><TD>44KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「足りないもの」の存在を突きつけられた梓。のぞみがその答えを持つというが……<BR>
<BR><B>【コメント】 </B>話の本筋とは別に、三人目の羽目の外し方もご覧ください……<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200512/06000905/ana_title.htm">アナログ所さん</A> <FONT SIZE="-1">(バレットさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>まじめな梓のまじめな展開……　の、はずなんですけど（汗<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_08.htm">ヴィスティア　（chapter 08）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/11/26(土)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>適う存在を発見したコロネ。彼女を引き合わせるため……のぞみは予想<BR>
外の行動に出る。<BR><B>【コメント】 </B>……こんなことになるなんて（笑）<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>担当としては今度の娘がいちばん好みですよ？（爆）<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_bangai_01.htm">番外編ヴィスティア　『こんなところで！　望まないせんとう』</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/11/2(水)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>家のお風呂が壊れたのぞみ。かごを手に温浴施設に行くと……<BR><B>【コメント】 </B>お風呂はゆっくり入りたいですね。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="http://ts.novels.jp/novel/200101/14013415/title.html">らいか大作戦</A> <FONT SIZE="-1">(かわねぎさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>マナーを守って楽しい入浴を……とはいえ巻き込まれたらしょうがない？<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 現代 ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 お風呂 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_07.htm">ヴィスティア　（chapter 07）</a></B></TD><TD><B>ほたる</B> さん </TD><TD><B>画</B>(<B>ほたる</B>さん)</TD><TD>2011/10/14(金)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一人の味方と、一人の敵。現れたふたつの存在が、のぞみたちに急を告げる。<BR><B>【コメント】 </B>シリーズタイトルのページを作りましたが……未完成です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のぞみと梓は必死で戦う。たとえ敵わない強者が相手でも……<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_07.htm">ヴィスティア　（chapter 07）</a></B></TD><TD><B>ほたる</B> さん </TD><TD><B>画</B>(<B>ほたる</B>さん)</TD><TD>2011/10/14(金)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一人の味方と、一人の敵。現れたふたつの存在が、のぞみたちに急を告げる。<BR><B>【コメント】 </B>シリーズタイトルのページを作りましたが……未完成です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のぞみと梓は必死で戦う。たとえ敵わない強者が相手でも……<BR>
<b><a href="./novel/201005/20141534/vistia_index">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_06.htm">ヴィスティア　（chapter 06）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/9/11(日)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ドラマのロケ地巡りに出かけたのぞみ。その最後に、彼女が見たものは……<BR><B>【コメント】 </B>なんにしても、動かないと始まりませんね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のぞみの純粋さに良太＝サヴェージの心は揺れる。戦う意味はそこにあるのか。<BR>
<b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01】</a><a href="./novel/201005/20141534/vistia_02.htm">【02】</a><a href="./novel/201005/20141534/vistia_03.htm">【03】</a><a href="./novel/201005/20141534/vistia_04.htm">【04】</a><a href="./novel/201005/20141534/vistia_05.htm">【05】</a><a href="./novel/201005/20141534/vistia_themovie_01.htm">【劇場版】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_themovie_01.htm">劇場版『ヴィスティア　旅する乙女のハプニングタイム！』</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/8/15(月)</TD><TD>88KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>　スフレに旅させてあげたいと思ったのぞみ。相談を持ちかけた先輩が勧めたのは……ちょっと離れた場所にある博物館。<BR><B>【コメント】 </B>元ネタとなった博物館はどこでしょう（当てても賞品はありません）<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200207/03224430/roromi_title.html">微妙存在ろろみ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>夏休み！　といえば劇場版です。ゲストを迎えてますます華やかに！<BR>
<b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01】</a><a href="./novel/201005/20141534/vistia_02.htm">【chapter 02】</a><a href="./novel/201005/20141534/vistia_03.htm">【chapter 03】</a><a href="./novel/201005/20141534/vistia_04.htm">【chapter 04】</a><a href="./novel/201005/20141534/vistia_05.htm">【chapter 05】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 劇場アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_05.htm">ヴィスティア　（chapter 05）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/7/20(水)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>野球観戦というイベントの中で、誰いうこともなく互いを知ろうとするのぞみたち。だが、そこへ現れたのは……<BR><B>【コメント】 </B>彼らの名字、元ネタわかる人は手を上げて。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200702/18234405/dislikes.html">『きらいなもの』シリーズ</A> <FONT SIZE="-1">(おもちばこさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なんとか球宴前に掲載出来てほっとしてます。本番はこれからですよね？　ちなみに予定より遅れたのは担当の責任……。げほげほ。<BR>
<b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01】</a><a href="./novel/201005/20141534/vistia_02.htm">【chapter 02】</a><a href="./novel/201005/20141534/vistia_03.htm">【chapter 03】</a><a href="./novel/201005/20141534/vistia_04.htm">【chapter 04】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 現代 ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_04.htm">ヴィスティア　（chapter 04）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/6/28(火)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高校に現れた、四人目の敵。圧倒的な力の差に、のぞみと梓は……<BR><B>【コメント】 </B>とにかく、”ない”んです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のぞみと梓。日常でも戦いでも、とっても息が合ってきました。<BR>
<b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01】</a><a href="./novel/201005/20141534/vistia_02.htm">【chapter 02】</a><a href="./novel/201005/20141534/vistia_03.htm">【chapter 03】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_03.htm">ヴィスティア　（chapter 03）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/5/16(月)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>様々な思いを背負い、高校へと初登校する二人に、新たな影が忍び寄る。<BR><B>【コメント】 </B>言うべきことと、言わずにおくべきこと。境界線は、どこにあるのでしょうか。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200604/21135117/holy_title.html">ホーリーメイデンズ</A> <FONT SIZE="-1">(流離太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>翼はのぞみとして、新しい日常を生きて行きます。平穏な毎日ではないけれど、いつかきっと……。<BR>
<b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01】</a>　<a href="./novel/201005/20141534/vistia_02.htm">【chapter 02】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代  アクション ライトファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_02.htm">ヴィスティア　（chapter 02） </a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/3/10(木)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>背負ってしまった運命。二人は未来を切り開くため、立ち向かうことを選ぶ。<BR><B>【コメント】 </B>どっかで見たような人が出てきますが……気のせいです（笑）<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/robot_triathlon/title.htm">『ロボＴＲＹ美少女っ』シリーズ</A> <FONT SIZE="-1">(MONDOさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>運命、そして、未来。目覚めし二人の力を合わせれば、あの強敵もこのとおりっ！<BR>
 <b><a href="./novel/201005/20141534/vistia_01.htm">【chapter 01 はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/vistia_01.htm">ヴィスティア　（chapter 01）</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2011/2/14(月)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>異世界からやってきた、小さな少女。彼女の頼みを叶えるべく、少年は走り出し……そして、非日常へと巻き込まれていく。<BR><B>【コメント】 </B>大切な人の豹変を目にした時、あなたはどう対応しますか？<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200703/16205836/saila_title.htm">戦乙女セーラ</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>強大な力を秘めた「エクセリュート」をめぐる戦いが幕を開ける！　新番組の始まりです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 現代 ライトファンタジー <BR>【種別】 魔法 変身<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/201005/20141534/the_fairy_of_rink.htm">リンクの妖精</a></B></TD><TD><B>ほたる</B> さん </TD><TD>(イラストなし)</TD><TD>2010/5/20(木)</TD><TD>58KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=hotaru">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>　少年が見た、一人の少女の夢。夢を叶えるため、約束を守るため、少年は少女として、舞台へと立つ。<BR><B>【コメント】 </B>　軽口には気をつけましょう。引き返せなくなります。<BR><B>【ほたる さんのオススメ作品】</B> <A HREF="./novel/200605/05101055/aozora1.htm">青空の魔法</A> <FONT SIZE="-1">(きりか進ノ介さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>　目が覚めると彼は……。ていねいな文章で爽やかに描かれる「ふたり」の新たな挑戦のお話です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 スポーツ <BR>【種別】 精神同居 人格転移<BR>【キーワード】  オレっ娘 露出？ 強制</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(174.129.228.67) , Competence : -1 -->
</BODY></HTML>
