<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/kumi01.htm">美少女組長奮戦記</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/2(金)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>抗争突入寸前のヤクザの組長が少女の姿に。それに対する組員。そして敵対組織の反応は……<BR><B>【コメント】 </B>今回はストレートで挑戦。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「ストップ！　ひばりくん」の関東大空組を思い出してしまった担当は……トシですか？（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 任侠（笑） 強制</TD></TR></TABLE><BR><BR>『城弾』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/tsukinuke.htm">突き抜け</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2014/6/18(水)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッチョな男子が幼女化。そしてその弟は重度のペドフィリア……<BR><B>【コメント】 </B>これ、無事皆さんのお目に留まっているんでしょうか（笑）。ＮＧくらってもすべて納得な作品なんで（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>己を阻む試練（笑）に打ち勝てば、貴方もきっと「突き抜け」ることができる……かも？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 ぺド マッチョ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit7.htm">とらぶる☆すぴりっつ　最後の一杯「呑まれたら大団円！？」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2014/4/22(火)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『酒』と『女』に違う形でおぼれた真澄は遂に……そしてその行く末は？<BR><B>【コメント】 </B>これにて完結です。時間のかかった作品にお付き合いくださった皆様に感謝です。乾杯！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>女体化依存症？になった真澄ちゃん。その行き着く先は？　「とらぶる☆すぴりっつ」最終章、極上の一杯をあなたに。<BR>
<b><a href="../novel/200209/19204751/t_spirit_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 酒</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/up_down.htm">ジャンプアップ　ジャンプダウン</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2014/3/23(日)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>初詣で参拝した神社で入れ替わってしまった１６歳の兄と１０歳の妹。戻れぬまま新しい体で新たな人脈が出来ていき……<BR><B>【コメント】 </B>同世代の男女でやろうとした話をアレンジしてこの形で。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>男子高校生と女子小学生、「年の差」入れ替わりの結末は……？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 入れ替わり<BR>【キーワード】 リリカル 年齢退行</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/trickstar.htm">とりすた〜いかにも第一話のような話〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2014/2/3(月)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自分を「変えたい」と願う少年は先輩女子に連れられて人生を変える部活に。<BR><B>【コメント】 </B>例によって「よくある話」にＴＳを絡めました（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200105/08212223/opencampus.htm">オープンキャンパス</A> <FONT SIZE="-1">(逃げ馬さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>廃部寸前の「とりすた部」にやって来た新入生。そして始まる新たなる伝説〜？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 部活 よくある話（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/twins03.htm">後天性ツインズ　第３話「狂想曲・真夏のビーチサイド」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2013/12/14(土)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>亜留葉と平太を加えて男女六人で泊りがけの海水浴。どこで騒動が巻き起こり。<BR><B>【コメント】 </B>まさか水着話で停滞するとは思わなかった……<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200907/19181916/s-plus.htm">エスプラス</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ヒーロー？バトルはちょっとお休み。しかしその間にも亜留葉ちゃんの女の子化は着々と進むのであった……（＾＾）<BR>
<b><a href="../novel/201212/18232308/twins01.htm">【第１話はこちら】</a><a href="../novel/201212/18232308/twins02.htm">【第２話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 パロディ コメディ <BR>【種別】 分裂 変身<BR>【キーワード】 おっさんホイホイ（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit6.htm">とらぶる☆すぴりっつ　六杯目「呑まれたら初体験！？」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2013/10/10(木)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「目覚めてしまった」真澄はまずは同僚ＯＬと。そしてついには女として……<BR><B>【コメント】 </B>同人誌で先行公開していた作品を、全年齢向けに直しての投稿です。つまりかなり……<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/201306/22214347/bloodywind_a.html">緋色の風１<a href="../novel/201306/22214347/bloodywind_b.html">／２</a><a href="../novel/201306/22214347/bloodywind_c.html">／３</a></A> <FONT SIZE="-1">(石積ナラさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>このままＴＳっ娘の暗黒面？に堕ちるのか……どうするどうなる真澄さんっ！？<BR>
<b><a href="../novel/200209/19204751/t_spirit_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 酒</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit5.htm">とらぶる☆すぴりっつ　五杯目「呑まれたら夜明けのコーヒー」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2013/7/31(水)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ビアガーデンで飲み足りなかったきららは意図的に男たちにナンパされ……<BR><B>【コメント】 </B>またまた間が空いちゃってごめんなさい。今回はきららがメインのちょっとセクスィー（笑）なお話です。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200112/18230553/saketitle.htm">ＳＡＫＥ</A> <FONT SIZE="-1">(龍酒さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>肉食系？ＴＳっ娘きららさん、一夜のアバンチュール（笑）。さて、その結末は──<BR>
<b><a href="../novel/200209/19204751/t_spirit.htm">【一杯目はこちら】</a><a href="../novel/200209/19204751/t_spirit2.htm">【二杯目はこちら】</a><a href="../novel/200209/19204751/t_spirit3.htm">【三杯目はこちら】</a><a href="../novel/200209/19204751/t_spirit4.htm">【四杯目はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 酒</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/twins02.htm">後天性ツインズ　第２話「荒れる学園」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2013/7/6(土)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「双子」の通う高校に来襲者。その修羅場に帰ってきた男。そして力をなくしたことを憂いた亜留葉に平太は一つの提案をする……<BR><B>【コメント】 </B>二話目が大暴走というのも「ＧＦ乙女」と一緒（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200606/27201201/ougi01.htm">奥義</A> <FONT SIZE="-1">(ｔｏｓｈｉ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おっさんな担当は元ネタのヒーローたちを見ていた時、子ども心に思った。「で、一番強いのは誰なんだろう──」。だけどここで一番強いのは……（＾＾；<BR>
<b><a href="../novel/201212/18232308/twins01.htm">【第１話はこちら】</a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 パロディ コメディ <BR>【種別】 変身（？）<BR>【キーワード】 おっさんホイホイ（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/twins01.htm">後天性ツインズ　第１話「分裂」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2013/5/25(土)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>謎の石を握りしめた状態でうっかり「望み」を口にした男が美少年と美少女に分裂し……<BR><B>【コメント】 </B>「ＧＦ乙女」と同じのりでもう一度。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200107/29145945/izumi.html">いずみちゃんと泉くんの１日</A> <FONT SIZE="-1">(ｍｋ８４２６さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おっさんな担当は元ネタのいがみ合う怪人を見て子ども心に思った。「ああ、これが同族嫌悪というやつか──」。そんなお話……？（＾＾；</TD></TR><TR><TD COLSPAN=6>【ジャンル】 パロディ コメディ <BR>【種別】 変身（？）<BR>【キーワード】 おっさんホイホイ（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/angelvoice.htm">Ａｎｇｅｌ　Ｖｏｉｃｅ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2013/3/24(日)</TD><TD>56KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男性声優が一年間１６歳の女性声優として活動することに。そしてその声は本人の望みと裏腹に……<BR><B>【コメント】 </B>随分と時間がかかってしまった作品で、一時はとん挫してました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>性転換システム実験の被験者たちを描いた<b><a href="../novel/200803/01214225/antena01a.htm">「アンテナショップ」</a></b>の姉妹編。城弾さんの「声優」に対する思いと愛が詰まったお話です。<BR>
<b><a href="../novel/200803/01214225/antena02.htm">【「アンテナショップ」中編はこちら】</a><b><a href="../novel/200803/01214225/antena03.htm">【後編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 リリカル <BR>【種別】 変身<BR>【キーワード】 「アンテナショップ」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/calendargirl.htm">カレンダーガール</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2013/2/3(日)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>背中をたたかれるとその女子と入れ替わってしまう主人公。意外に使える体を勝手に拝借され受難の日々…<BR><B>【コメント】 </B>少年マガジンの「山田くんと７人の魔女」にインスパイアされてできました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/201101/08222059/catfoods.html">ねこのえさ</A> <FONT SIZE="-1">(石積ナラさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>元に戻れることが確実ならば、他人（男の子）の身体を使ってあれやこれやをやってみたいっ！　“借りられる”方はたまったもんじゃないですが（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 入れ替わり<BR>【キーワード】 勝手な女たち（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201212/18232308/tigers2012.htm">ＴｉｇｅｒＳ２０１２</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2012/12/18(火)</TD><TD>57KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>阪神が勝つと女性化する呪いをかけられた青年。阪神ファンだが女の子になりたくないから負けを祈るがやがて……<BR><B>【コメント】 </B>「東京在住の巨人ファン」が「大阪を舞台に阪神ファン」を描きました。今までこれだけ資料を見たことはなかったです（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/extra/kayo_ex36.htm">巌流島？</A> <FONT SIZE="-1">(よしおかさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>たとえＴＳしようとも、阪神ファンはやめられないっ！　２０１２年の浮き沈みに一喜一憂しながら読むと、あなたも立派なトラ党かも？（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 阪神</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/suzuki&sato.htm">鈴木君と佐藤君</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2012/11/14(水)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「佐藤君と鈴木君」の鈴木勉／月姫視点の作品です。<BR><B>【コメント】 </B>「王道」と書いて「べた」と読む（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200907/19181916/shopping.htm">休日は母娘でショッピング？</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><b><a href="../novel/200209/19204751/sato&suzuki.htm">「佐藤君と鈴木君」</a></b>で、王道ＴＳっ娘な扱いを羨ましがられていた“月姫ちゃん”のお話♪　これはこれでいろいろと気苦労があるような……（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 お約束</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/sato&suzuki.htm">佐藤君と鈴木君</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2012/10/23(火)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ＴＳマニアの少年。佐藤孝は念願の女体化をしたのはいいけれど……<BR><B>【コメント】 </B>もう一人の視点で見た「鈴木君と佐藤君」と対になってます、合わせてお楽しみください。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/wanna_be_a_girl.html">女の子になりたいな…なれるかな？</A> <FONT SIZE="-1">(ＴＡＲＯＴＡさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あーなんと言いましょうか……ＴＳっ娘を着せ替え人形にするママンもたいがいですが、こーゆー扱いされるとリアル通り越して一回転しているような（笑）。「理想」と「現実」は別物──ということでしょうか。（＾＾；</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 お約束</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201207/16214435/sister01.htm">ＮＯ　ＳＩＳＴＥＲ　ＮＯ　ＬＩＦＥ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2012/7/16(月)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自他共に認める「イタイ」少年が「脳内妹」を愛ですぎた結果……<BR><B>【コメント】 </B>トゥルラーとしてはブラコン妹の名前は一つしかありませんでした（笑）。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200606/27201201/h_title.htm">戦え！　スウィートハニィ</A> <FONT SIZE="-1">(ｔｏｓｈｉ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>妄想が現実に侵食する──痛少年の持つ「大それた力（違）」とは……って、何処の非公認戦隊ですか？（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 入れ替わり？ 変身？<BR>【キーワード】 脳内妹 痛さは強さ（笑） リアル妹</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201203/14212103/okusama_s.htm">奥さまはＴＳ娘</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2012/3/14(水)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>かつては男だった「りん」は今では家庭の主婦。だが「女」への道は険しく遠い？<BR><B>【コメント】 </B>城弾初の夫婦ものです。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200802/18212014/bhr.htm">ヒーロー誕生！？１<a href="../novel/200802/18212014/bhr2.htm">／２</a><a href="../novel/200802/18212014/bhr3.htm">／３</a></A> <FONT SIZE="-1">(高居空さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＴＳっ娘としては、本来同性のはずである「男性」との結婚は抵抗感が先に立つ……はずなのですけど、さてさて「彼女」の場合は──</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 神秘 変身<BR>【キーワード】 夫婦</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit4.htm">とらぶる☆すぴりっつ　四杯目「呑まれたら小さな恋？」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2012/2/18(土)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>休日出勤の土曜日。早めに飲み始めて朝まで。そこで真澄に起こった出来事とは？<BR><B>【コメント】 </B>酔っての乱行も大概にしないと場合によっては他人にトラウマを！？<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200907/19181916/pinkranger.htm">ピンクの悲劇？</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶり、酔うとＴＳしちゃう会社員酒井くんのお話。……アルハラで訴えたら勝てると思います（乾笑）。<BR>
<b><a href="../novel/200209/19204751/t_spirit.htm">【一杯目「呑まれたら女の子？」】</a><a href="../novel/200209/19204751/t_spirit2.htm">【二杯目「呑まれたら外国人？」】</a><a href="../novel/200209/19204751/t_spirit3.htm">【三杯目「呑まれたら童女？」】</a></b>（←サブタイトル変更しました）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 神秘 変身<BR>【キーワード】 呪い 酒 「着せ替え少年」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/gfo04.htm">ゴッドファーザー乙女　Lesson4「さよなら乙女先生」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2012/1/14(土)</TD><TD>51KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>残った五人は男のままでいようと、乙女に勝負を挑み続けるが……<BR><B>【コメント】 </B>起承転結の「結」です。これで終わります。ここまでお付き合いくださった皆様に感謝。特に暴走パロディにつきあってくれた人に（笑）。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200705/20184554/AngelLife.html">えんじぇる・らいふ</A> <FONT SIZE="-1">(泉谷パームさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ひとり、またひとりと力尽きて倒れていく男たち。ただひとり生き残った者に去来する思いとは……？<BR>
　「ゴッドファーザー乙女」、完結です。　<b><a href="../novel/200803/01214225/gfo01.htm">【Lesson1はこちら】</a><a href="../novel/200803/01214225/gfo02.htm">【Lesson2はこちら】</a><a href="../novel/200803/01214225/gfo03.htm">【Lesson3はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 不良 元ヤン 教師</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/gfo03.htm">ゴッドファーザー乙女　Lesson3「ハンター・ミッション」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2011/10/3(月)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>乙女襲撃計画が立ち上がり、復讐心から参加した秋津だが……<BR><B>【コメント】 </B>今回は秋津の複雑な心境に注目で。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200611/21212001/lake.htm">湖のひみつ</A> <FONT SIZE="-1">(大原野山城守武里さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いつの間にやらクラスの半数が女子化！　起承転結の「転」で、ついに主人公も──？<BR>
<b><a href="../novel/200803/01214225/gfo01.htm">【Lesson1はこちら】</a><a href="../novel/200803/01214225/gfo02.htm">【Lesson2はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 不良 元ヤン 教師</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol12.htm">戦乙女セーラ Ｖｏｌ．１２</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2011/7/4(月)</TD><TD>124KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いよいよ将軍ガラ。そしてクイーンアマッドネス・ロゼとの戦いが迫る。<BR><B>【コメント】 </B>戦乙女セーラ。堂々完結です。皆様の応援のおかげでここまでたどり着けました。あつく御礼申し上げます。いくつかの番外は考えてますがとりあえずこれで区切りを。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自分自身の消失……その恐怖を乗り越え、セーラ──いや、清良たちは最後の戦いに赴く。<BR>
　「戦乙女セーラ」ついに完結っ！！　最後の戦いをその目に焼き付けよっ！！（掲載が遅くなりました）<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/gfo02.htm">ゴッドファーザー乙女　Lesson2「魔法先生オトめ」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2011/5/8(日)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>不良男子が次々と少女化していく中で秋津は一つの事に気がついて……そして語られる乙女の過去。<BR><B>【コメント】 </B>少々やりすぎだった気が（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200012/16230626/cloneb.html">マイ・ピュア・クローン・ドール</A> <FONT SIZE="-1">(八重洲二世さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>大原乙女はいかにして「乙女」となったのか？　……そして全てのネタが分かる人、前へ出なさいっ。（＾＾）<b><a href="../novel/200803/01214225/gfo01.htm">【Lesson1はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 不良 元ヤン 教師</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol11.htm">戦乙女セーラ Ｖｏｌ．１１</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2011/4/4(月)</TD><TD>75KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>タイガー。ジャッカルと強敵が続く。そんな中でスズのヨリシロが判明。<BR><B>【コメント】 </B>戦乙女たちの戦う姿が勇気につながれば幸いです。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>結末に向けてストーリーが加速する「戦乙女セーラ」。謎の女戦士──大賢者スズの正体はっ！？<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 転生 特撮パロディ 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/gfo01.htm">ゴッドファーザー乙女　Lesson1「GFO 〜god father otome〜」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2011/2/21(月)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>荒れた高校を建てなおすべく来たのは元・不良男子の現・女教師だった。<BR><B>【コメント】 </B>よくある設定にＴＳ風味をたすとこんな感じに（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200907/19181916/onsen.htm">秘湯</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>掃き溜めのような不良たちのクラスに現れた彼女の名は乙女。その不条理極まりないレッスン？が始まった。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 元ヤン 不良 教師</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/otorisousa.htm">おとり捜査</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2011/1/8(土)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>痴漢撲滅のおとり捜査のため女性化する主人公。女性の肉体で電車に乗り込んで視線が……<BR><B>【コメント】 </B>ちょっと意外な作品との繋がりがあります。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200606/27201201/gamia.html">警部さんは金髪がお好き</A> <FONT SIZE="-1">(ｔｏｓｈｉ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>城弾さん恒例の、新春お笑いＴＳ噺。皆さん、相手がＴＳっ娘でも痴漢は犯罪ですよっ！！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 リリカル コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201009/16215412/delayed05.htm">仮面ライターディレイド第５話「勇気」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2010/9/4(土)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=delayed">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「セーラの世界」後編。変身をためらうキヨシだがユウキが拉致されてしまい……<BR><B>【コメント】 </B>『文庫さん』でＴＳバトルヒロインを書いている皆さんが乗ってくれることを期待してシェアワールドにさせていただきました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/robot_triathlon/title.htm">ロボＴＲＹシリーズ</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>激突するセーラとミラージュホワイト！　ディレイドの存在は、本当に多元世界を破滅に導くのか！？<b><a href="../novel/200907/19181513/delayed04.htm">【第４話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 「仮面ライダーディケイド」パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201009/16215412/delayed04.htm">仮面ライターディレイド第４話「おびえるセーラ」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2010/8/28(土)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=delayed">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「少年少女文庫」のバトルヒロインの世界を渡り歩くディレイドこと鳩谷翼たち。ミラージュガールの世界の次に訪れたのは「戦乙女セーラ」の世界だった。<BR><B>【コメント】 </B>タイトルからしてわかるように「ディケイド」のパロです。「ミラージュガール」の名前を使わせていただいたライターマンさんに感謝。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>】いろいろ物議をかもした？あの特撮ヒーローのパロディ作品が登場！　我々の知る<b><a href="../novel/200703/16205836/saila_title.htm">『戦乙女セーラ』</a></b>とは少し違う世界での、彼──彼女の役回りとは？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 「仮面ライダーディケイド」パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200907/19181513/hitonoki02.htm">あたしの気も知らないで</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2010/8/10(火)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「人の気も知らないで」の静香から見たお話です。<BR><B>【コメント】 </B>同じエピソードの別視点と言うのは良くやってるんですが今回はてこずりました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200802/18212014/senyo.htm">専用車両</A> <FONT SIZE="-1">(高居空さん作)コミケのサークル参加祝いも兼ねて（笑）</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>もうひとりの主人公、静香ちゃんの一人称でおくる裏？のお話。彼女の恨み節（笑）が止まりませ〜ん。<BR>
<b><a href="../novel/200907/19181513/hitonoki_s.htm">【前作『人の気も知らないで』はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 双子</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200907/19181513/hitonoki_s.htm">人の気も知らないで</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2010/6/19(土)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>事故で女の子になってしまった少年。さらに女の子になりたい双子の弟の妬みを受け…<BR><B>【コメント】 </B>スターシステム第二弾（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200907/19181916/m-twins.htm">まじかるツインズ大迷惑</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>双子の兄弟が織りなす、愛憎の物語……って書くとドロドロしてそうですけど、そこは城弾さん、お話は明るく？繰り広げられていきます。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 双子</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol10.htm">戦乙女セーラ Ｖｏｌ．１０</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2010/5/1(土)</TD><TD>86KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第四の戦士現る？　そしてセーラの完全女性化？<BR><B>【コメント】 </B>前半は特撮的に。後半はＴＳ的に美味しくなるようにしました（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>悪魔の笛が、清良と礼を狂気へと誘う。（ｅｐ３７）／セーラたちの前に現れたのは、第四の戦乙女？（ｅｐ３８）／敵に「大切なもの」を奪われたセーラは……？（ｅｐ３９）／そしてついに登場する、アマッドネスの——（ｅｐ４０）<BR>
　「戦乙女セーラ」、絶好調っ！！<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/josou.htm">女装趣味</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2010/3/16(火)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女装を趣味としていた男が本当に…<BR><B>【コメント】 </B>今回はかなりの挑戦です。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200908/13230349/shout_a.html">シャウト！</A> <FONT SIZE="-1">(パレットさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あなたは女になりたいのですか？　それとも、女を演じる自分になりたいのですか？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 女装</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol09.htm">戦乙女セーラ Ｖｏｌ．９</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2010/1/26(火)</TD><TD>81KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>セーラ。ブレイザ。ジャンス。それぞれの場所でそれぞれの闘い。<BR><B>【コメント】 </B>今回は一話完結が四本のオムニバスです。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>セーラＶｏｌ．９は短編４本立て。シリアスあり、コミカルあり、リリカルあり……そして、個性的（？）なアマッドネスの登場で、隠れた彼らの特性が……<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit3.htm">とらぶる☆すぴりっつＥｐｉｓｏｄｅ３「変転」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/10/9(金)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人事異動でやってきた青年、山崎きららの正体は……そして酒井の新たなる変身（笑）<BR><B>【コメント】 </B>三年ぶり……飲んでないのに頭が痛い（笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>酒は飲んでも飲まれるな……「職場のオモチャ」酒井くんの前に現れた新人の正体は？<BR>
<b><a href="../novel/200209/19204751/t_spirit.htm">【Ｅｐｉｓｏｄｅ１はこちら】</a><a href="../novel/200209/19204751/t_spirit2.htm">【Ｅｐｉｓｏｄｅ２はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 神秘 変身<BR>【キーワード】 呪い 酒 「着せ替え少年」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_ex.htm">戦乙女セーラＥＰＩＳＯＤＥ　Ｘ「初陣」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/9/7(月)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>蘇える異形。立ちふさがる現代の戦乙女。そのファーストストーリー。<BR><B>【コメント】 </B>ジャンスを主役にした現代の戦いの幕開けの話です。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ジャンスちゃん、はじめてのへんしん（笑）。そしてあの「番長」との出会い。<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200907/19181513/pls_trance.htm">ＰＬＳ〜Ｃｈａｓｅ　ｉｎ　Ｌａｂｙｌｉｎｔｈ〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2009/7/19(日)</TD><TD>64KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子を愛する少年が女性化。ここぞとばかしに猛チャージ。苦悩するヒロインは……<BR><B>【コメント】 </B>自分のサイトで連載している作品の番外編です。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200702/27234954/yorishiro_01.htm">よりしろトランス第一話<a href="../novel/200702/27234954/yorishiro_02.htm">／第二話</a><a href="../novel/200702/27234954/yorishiro_03.htm">／第三話</a><a href="../novel/200702/27234954/yorishiro_04.htm">／第四話</a></A> <FONT SIZE="-1">(乾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>男の子が好きな美少年に恋した学園のアイドル。いやはや、恋とはままならぬもの……「城弾シアター」で連載中の小説番外編が「文庫」にお目見えです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 月 架空のギャルゲーノベライズ 同性愛の少年</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/oniwaban_tsn.htm">女の園のお庭番</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2009/5/16(土)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>現代の忍び、笠間次郎太は警護のため少女となって女子高に。<BR><B>【コメント】 </B>今回は直球勝負。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/corrector/foster19.html">次元管理人フォスター・シリーズ「レンジャー・オブ・パワー」</A> <FONT SIZE="-1">(高居空さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>光あるところに影あり。影の中に忍びあり。だが人よ、その名を問うなかれ。影に生き、影に死するが忍びの定め…………だけどやっぱりこれは嫌過ぎるっ！！（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 忍び 剣客 女子高</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol08.htm">戦乙女セーラ Ｖｏｌ．８</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/4/19(日)</TD><TD>87KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>アマッドネスの気配に誘われた三人が鉢合わせしたのはなんとプール？<BR><B>【コメント】 </B>今回は平成ライダーの夏の番外編のりです（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>夏だ！　プールだ！　水着だ萌えだ！　……掲載したのは４月だけど（おいおい）。<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/fukutsu_tsn.htm">不屈のスケベ（少年少女文庫バージョン）</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/3/9(月)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>容姿端麗、文武両道だがこの世のものとは思えないスケベな少年、篁 満は女子更衣室を覗きたい一念で……<BR><B>【コメント】 </B>『男なのに女になってしまった』なんて葛藤が欠片もありません（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/wanna_be_a_girl.html">女の子になりたいな…なれるかな？</A> <FONT SIZE="-1">(ＴＡＲＯＴＡさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>篁 満は悩んでいた……窓のない女子更衣室……立ちふさがる幼なじみ……そんな彼が手にしたものは……？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 スケベ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/antena03.htm">アンテナショップ 後編</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/2/15(日)</TD><TD>41KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>沙羅、衝撃の事実。そして男に戻った金太郎の心情は……<BR><B>【コメント】 </B>これでラストです。とても思いいれの強い作品になりました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200706/17105152/hikaru1.htm">ひかるめざめる 第１話<a href="../novel/200706/17105152/hikaru2.htm">／第２話</a><a href="../novel/200706/17105152/hikaru3.htm">／第３話</a><a href="../novel/200706/17105152/hikaru4.htm">／第４話</a></A> <FONT SIZE="-1">(きりか進ノ介さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>メイド喫茶で「臨床実験」を続ける六人。期間終了が近づき、彼女？たちが選んだのは……<BR>
<b><a href="../novel/200803/01214225/antena01a.htm">【前編はこちら】</a><a href="../novel/200803/01214225/antena02.htm">【中編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 メイド 臨床実験</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/antena02.htm">アンテナショップ 中編</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2009/1/16(金)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女としての日々を重ね、段々に自分が男であることを忘れてきている面々。そして沙羅は……<BR><B>【コメント】 </B>とんでもなく遅くなってごめんなさい。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200707/14133526/moehero.htm">萌える（？）ヒーロー</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>季節は春から夏へ。ＴＳっ娘メイド喫茶『Ｔｗｉｎｋｌｅ ☆ Ｓｔａｒ』の六人にも、さまざまな変化が……<BR>
<b><a href="../novel/200803/01214225/antena01a.htm">【前編はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 メイド 臨床実験</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol07.htm">戦乙女セーラ Ｖｏｌ．７</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/10/25(土)</TD><TD>69KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>クレームをつけるべくジャンスに会う清良だが翻弄されて。<BR><B>【コメント】 </B>今回の新キャラ。番長の台詞が全部わかる人。僕と特撮を語り合いましょう（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>第三の戦士、戦乙女ジャンス登場。でも今回一番目立っているのは…………ば、番長？（笑）<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 泣けるで 輝く太陽のエレメンツ 転生 特撮パロディ 俺は太陽の男</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol06.htm">戦乙女セーラ Ｖｏｌ．６</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/8/21(木)</TD><TD>62KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>互いに宿敵と知らず過ごす幼なじみ。幼なじみと殺し合いをしているとはしらずにいるセーラ。<BR><B>【コメント】 </B>今回はシリアスです。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回だけは、ジャンルのアクションコメディから「コメディ」が抜けています。清良と友紀、セーラとファルコンアマッドネス……その戦いの果てにあるのは！？<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 バトルアクション <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex62.htm">ハンターシリーズ「可憐バトラーセバ」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/7/26(土)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>過去編・西園寺家の門前に捨てられていた赤ん坊を引き取った執事・瀬場勝也は……／現代編・良磨が『美奈子』になってしまったその経緯とは？<BR><B>【コメント】 </B>運命の鎖を引きちぎれ！（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200404/08214842/m_rider01.htm">仮面ライダー・フォース</A> <FONT SIZE="-1">(ラウルさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「過去編」「現代編」とありますが、すけこまバイオリニストや「絶対正義」がどうたらとか言う御方は出てきませんので……（笑）<BR>
<b><a href="../novel/kayo_chan/extra/kayo_ex61.htm">【『君が主のごとく』はこちら】</a><a href="../novel/kayo_chan/title-ex.htm">【番外編シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 ハンターシリーズ 執事 お嬢様</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex61.htm">ハンターシリーズ「君が主のごとく」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2008/7/14(月)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新人ハンターは執事つきの元お坊ちゃまで現お嬢様。いちごが教育係となるが……<BR><B>【コメント】 </B>仮タイトルがそのまま本タイトルになってしまいました（笑）。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200307/19145539/title.html">鈴村君のＴＳ生活（半強制的）</A> <FONT SIZE="-1">(クラスターさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>執事——そのスペルはｂｕｔｌｅｒであって、決してｂａｔｔｌｅｒじゃありませんからっ！！（笑）<BR>
（運営委員の不手際で、掲載が大幅に遅れたことをお詫びします）<BR>
<b><a href="../novel/kayo_chan/title-ex.htm">【番外編シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 ハンターシリーズ 執事 お嬢様</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol05.htm">戦乙女セーラ Ｖｏｌ．５</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/5/7(水)</TD><TD>65KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>セーラに頼もしき援軍と、恐るべき強敵が。<BR><B>【コメント】 </B>まぁハカイダーというか、ホースオルフェノクというか（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＴＳっ娘が持つべきものは……やっぱ理解ある家族？（笑）<BR>
<b><a href="../novel/200703/16205836/saila_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ 理解ありすぎる家族（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex59.htm">ハンターシリーズ「ラスト・ファーストキス」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/3/30(日)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>半田双葉が華代被害者に向けた言葉は「女の子のままでいいじゃない？」<BR><B>【コメント】 </B>双葉の仕事振りを書いてみました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/kayo_chan/extra/kayo_ex57.htm">普通の麗人</A> <FONT SIZE="-1">(天欄さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>華代ちゃんに性転換された被害者を元に戻す秘密組織「ハンター」。そのイリーガルメンバーである双葉の“やり方”は……<BR>
<b><a href="../novel/kayo_chan/title-ex.htm">【番外編シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 ハンター・シリーズ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200803/01214225/antena01a.htm">アンテナショップ 前編</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/3/1(土)</TD><TD>54KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>実験で女性化した六人。続く実験はメイド喫茶でのメイドさん？<BR><B>【コメント】 </B>やり過ぎなのはいつものことで（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/pretty_devilish.html">悪魔でも天使</A> <FONT SIZE="-1">(真城悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>女性に変わった男性が実生活でどのように変化していくのか。壮大？な実験が始まった……って、大丈夫なんでしょうかこの被験者たち。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 メイド 臨床実験</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy13_ex.htm">着せ替え少年〜ＥＰＩＳＯＤＥ　ＦＩＮＡＬ〜卒業　アナザーバージョン</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2008/1/24(木)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>１２話ラストで男に戻れなくなった場合の展開です。<BR><B>【コメント】 </B>もう一つの最終回。それまでとのりが違うので自分のサイトだけで公開してましたが、単純に読んで貰いたくなり投稿しました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200207/03224430/overchange.html">かわりすぎ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「着せ替え少年ＦＩＮＡＬ」アナザーバージョン。「元に戻れない」を選ぶと（？）こうなりました。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol04.htm">戦乙女セーラ Ｖｏｌ．４</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/12/24(月)</TD><TD>65KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>礼と恩師の対決に助けに入ったのがきっかけで激突。そして明かされる真相。<BR><B>【コメント】 </B>一見シリアスですが、日曜朝八時テレ朝（関東）を見ている人には爆笑ものかと。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>セーラｖｓブレイザ！！　戦乙女バトルの結末は……！？<BR>
<b><a href="../novel/200703/16205836/saila_vol01.htm">【Ｖｏｌ．１はこちら】</a><a href="../novel/200703/16205836/saila_vol02.htm">【Ｖｏｌ．２はこちら】</a><a href="../novel/200703/16205836/saila_vol03.htm">【Ｖｏｌ．３はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy13.htm">着せ替え少年〜ＥＰＩＳＯＤＥ　ＦＩＮＡＬ〜卒業</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/11/9(金)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>卒業の日。司が選ぶのは男？　女？<BR><B>【コメント】 </B>長らくお読みいただいた「着せ替え少年」もこれにて完結。応援くださった皆様に感謝の意を。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200611/01223326/talk_in_sleep.html">寝言</A> <FONT SIZE="-1">(山田天授さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「着せ替え少年」フィナーレ。今までありがとう、つかっちゃんとラ〇ダーそっくりさんたち（……ってそっちか！）。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol03.htm">戦乙女セーラ Ｖｏｌ．３</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/8/15(水)</TD><TD>69KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>敵の連携に苦戦を強いられたセーラは、ブレイザに逢いに出向くのだが……<BR><B>【コメント】 </B>二人目登場。大方の予想通りの性格です（笑）。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ますます熾烈になるセーラ（清良）の戦い。そして、ついに登場する二人目の戦乙女——<b><a href="../novel/200703/16205836/saila_vol01.htm">【Ｖｏｌ．１はこちら】</a><a href="../novel/200703/16205836/saila_vol02.htm">【Ｖｏｌ．２はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy12.htm">着せ替え少年〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ１２〜Ｓｈｉｆｔ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/5/26(土)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>つかさ。男子復帰不能？<BR><B>【コメント】 </B>次回でラスト。そのための布石も。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200312/05062153/mlc_bgl_01.html">魔法のリップスティック</A> <FONT SIZE="-1">(Ｔａｉｋａ　Ｙａｍａｎｉ．さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>もはや笑っていられません（？）。つかっちゃん、いよいよ本格的に女子決定！？<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol02.htm">戦乙女セーラ Ｖｏｌ．２</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/4/24(火)</TD><TD>62KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>もう一つのフォーム登場。思わぬ変身の影響。そしてキャロルの秘密……<BR><B>【コメント】 </B>これでセーラの基本設定は出揃った感じです。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「戦乙女セーラ」Ｖｏｌ．２は、＃５「人魚」から＃８「天馬」までを収録。変身、バトル……そして萌えっ！！<BR>
<b><a href="../novel/200703/16205836/saila_vol01.htm">【Ｖｏｌ．１はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200703/16205836/saila_vol01.htm">戦乙女セーラ Ｖｏｌ．１</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2007/3/16(金)</TD><TD>65KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>太古の闘いが現代日本で再び……そして硬派気取りの男子は女物を着る羽目に（笑）。<BR><B>【コメント】 </B>ある意味では城弾の本領発揮。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「小〇女」でも「〇鋼女」でもありません（笑）。闇に巣くう異形どもに立ち向かえ、セーラっ！！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクションコメディ <BR>【種別】 変身<BR>【キーワード】 転生 特撮パロディ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy11.htm">着せ替え少年〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ１１〜Ｘ　Ｃｈａｎｇｅ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/12/19(火)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ふとしたことから新入生の男の子とデートする羽目になったつかさ。レイによって流されあげく……<BR><B>【コメント】 </B>そろそろ締めくくりたく思いまして。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200112/18123055/fms-p.html">ＦＭＳ：ｐａｔｔｅｒｎ　Ｐ</A> <FONT SIZE="-1">(夜夢さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おばあちゃんが言っていた……服に着られる者は、皆（みな）のおもちゃになるのがさだめ——（……笑）<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit2.htm">とらぶる☆すぴりっつＥｐｉｓｏｄｅ２「解明」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/11/13(月)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>呪いについて話をしようと思って実家に戻ったら、父と息子が母と娘に。さらには休日出勤をすることになり……<BR><B>【コメント】 </B>シリーズ化と言うことで今回は説明の回です。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200210/28213920/otome1.htm">乙女くん（前編）<a href="../novel/200210/28213920/otome2.htm">（後編）</a></A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>漢字で「諸星」と書くと、別のキャラクターを想像してしまう……じゃなくてっ！　飲めば飲むほどに色っぽいＴＳっ娘ＯＬ真澄ちゃんのお話第二話です。<b><a href="../novel/200209/19204751/t_spirit.htm">【Ｅｐｉｓｏｄｅ１「変身」はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 神秘 変身<BR>【キーワード】 呪い 酒 「着せ替え少年」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/t_spirit.htm">とらぶる☆すぴりっつ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/6/14(水)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>酒を呑むと女になる呪いをかけられた男。その末裔が起こす騒動<BR><B>【コメント】 </B>酒は呑んでも呑まれるな（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200112/18230553/saketitle.htm">ＳＡＫＥ</A> <FONT SIZE="-1">(龍酒さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>こんなＯＬさんが職場にいたら……気になって気になって仕事ができませ〜んっ（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 神秘 コメディ <BR>【種別】 変身<BR>【キーワード】 呪い 酒 「着せ替え少年」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex43.htm">ハンターシリーズ「ゴウゴウの奇妙な災難」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/6/3(土)</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ハンター５５号の奇妙な冒険（笑）…実際これくらいしかいえなくて。<BR><B>【コメント】 </B>こういうアプローチのハンターシリーズもたまにはいいかなと思いまして。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200408/24222853/invader.html">Invader's week</A> <FONT SIZE="-1">(黒白さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さすがは真城華代ッ！　私達に出来ないことを平然とやってのけるッッ！　そこにシビれる！　憧れるゥ！<br><b>■<a href="../novel/kayo_chan/title-ex.htm">シリーズタイトル一覧はこちら</a>■</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 来訪者 ハンターシリーズ ジョジョの奇妙な冒険 バオー 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/ikinari.html">いきなり「Ｆ」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/4/17(月)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女性の大きな胸の大好きな青年が念願かなって（？）巨乳の主に<BR><B>【コメント】 </B>女性読者のツッコミが恐い作品です（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200410/04203258/title.htm">仮面の♂</A> <FONT SIZE="-1">(あっぴぃさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なにはともあれ、その三日間が貴重な体験だったことは間違いないようで。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 入れ替わり<BR>【キーワード】 後ろ向きな性格 巨乳</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy10.htm">着せ替え少年〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ１０〜シスタープリンセス</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/2/24(金)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>同居を始めた従妹の洸。その願いで東京見物に出向いた先は…オタクの聖地！？<BR><B>【コメント】 </B>この作品はフィクションであり、実在の人物、団体、そして「地域」にはまったく無関係です（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200503/27150319/bear_hand.html">熊の手</A> <FONT SIZE="-1">(鈴忌紫さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>洸ちゃん再登場！　“あの”お店を舞台につかっちゃん、またまたコスプレ三昧（？）。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yodan.html">湯の街余談</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/2/14(火)</TD><TD>41KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「奇談」の後日談。翔といずみの息子の飛鳥が子宝の湯に…<BR><B>【コメント】 </B>こちらはコメディです。本当はこういう感じで行くつもりもありました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200308/20191205/angel.htm">俺に降りてきた天使</A> <FONT SIZE="-1">(ｆｕｎ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いずみの息子も巻き込まれてしまった。<BR>
<b><a href="novel/200209/19204751/yunomachi01.html">【第一話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi02.html">【第二話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi03.html">【第三話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi04.html">【第四話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi05.html">【最終話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身<BR>【キーワード】 リリカル 「湯の街奇談」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yunomachi05.html">『湯の街奇談・最終話』</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/1/28(土)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>念願の男への復帰。だが泉の心は晴れなかった…<BR><B>【コメント】 </B>長らくかかりましたが最終話をお届けすることが出来ました。応援してくださった皆様に感謝。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200112/19020205/idolboy1.htm">僕はアイドル</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いずみのココロのたどり着く先は。最終話です。<BR>
<b><a href="novel/200209/19204751/yunomachi01.html">【第一話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi02.html">【第二話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi03.html">【第三話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi04.html">【第四話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身<BR>【キーワード】 リリカル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy09.htm">着せ替え少年〜Ｄｒｅｓｓ　ｕｐ　ｂｏｙ９〜プリンセスナイン</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/7/12(火)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>自分の精神を鍛える目的で運動部に参加する司。しかしそれがことごとく女子のもので……<BR><B>【コメント】 </B>今回はスポーツウェア縛り。鍛えてます（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/extra/i_title.html">いちごちゃんシリーズ</A> <FONT SIZE="-1">(真城悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回のゲストは、“あの”おじさんの後輩の人と、元恒点観測員の理事長さん……そして、巷で話題の鍛えてる人（笑）。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/doukyo_g.htm">同居人・後日談</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/5/29(日)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>瀬奈と素直の性転換を見ていたクラスメイトの一人が、「自分も」と考えて……<BR><B>【コメント】 </B>一応「同居人」のその後ですが、続編とはいえないものに（汗）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200306/14163618/doki_01.htm">どきどき！　メガネっ娘くん</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ひとつの騒動がおさまって、あとに残ったものは三つの薬。男が女に、女が男に……さあお祭りの始まりだ（笑）。<BR>
<b><a href="../novel/200209/19204751/doukyo.htm">【「同居人」はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 薬品<BR>【キーワード】 ♀→♂ マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yunomachi04.html">「湯の街奇談」第四話</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/4/27(水)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに待望の妊娠。これで男に戻れる！　しかしいずみの心境は…<BR><B>【コメント】 </B>本当にお待たせし過ぎました。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200310/22200143/ts_club.htm">それいけＴＳ部</A> <FONT SIZE="-1">(土也紫緒さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どうしよう?!揺れるいずみの心。<BR>
<b><a href="novel/200209/19204751/yunomachi01.html">【第一話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi02.html">【第二話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi03.html">【第三話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 変身<BR>【キーワード】 リリカル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/kayo_chan92.html">華代ちゃんシリーズ「大きなおなか」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.com">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/3/4(金)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ダイエットのためにウォーキングをしていた青年に出会った華代ちゃんは…<BR><B>【コメント】 </B>人事じゃないです（笑）<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="novel/200210/28213920/m_title.htm">変身美少女戦士ミラージュガール</A> <FONT SIZE="-1">(ライターマンさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「ココロとカラダの悩み」は、華代ちゃんにまかせれば万事解決です！<BR>
<strong><a href="novel/kayo_chan/index.html">【華代ちゃんシリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/dup_boy08.htm">着せ替え少年 Ｄｒｅｓｓ Ｕｐ Ｂｏｙ８ 〜初恋バレンタイン〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/12/15(水)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>バレンタインデー。まことからのチョコ攻撃をかわすために女の子で登校したつかさに……<BR><B>【コメント】 </B>久しぶりの「着せ替え少年」お送りいたします。でも実はＴＳしてないときの方がメインだったりしますが（汗）。<BR><B>【城弾 さんのオススメ作品】</B> <A HREF="../novel/200303/17233027/akuma_title.html">悪魔を呼んでみよう！</A> <FONT SIZE="-1">(DEKOIさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶりのつかっちゃん。今回のゲストは、やたらと滑舌の悪い……あいつらです（笑）。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身<BR>【キーワード】 着せ替え コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/doukyo.htm">同居人</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/10/31(日)</TD><TD>43KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>北原誠治、彼を悩ませるのは大ぐらいの甥・素直。食欲を抑える相談を妹のマッドサイエンティスト、美里にしたら素直が性転換させられて……<BR><B>【コメント】 </B>ストレートに見えて手元で変化（笑）しかしただのエロ小説と言う気も（汗）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>確かに彼女ならこうするかも……（爆）。主人公の天然記念物級の“天然”さに、頭クラクラまちがいなし。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 薬品<BR>【キーワード】 ♀→♂（ほんの一瞬） 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/kumi01.htm">美少女組長奮戦記</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/2(金)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>抗争突入寸前のヤクザの組長が少女の姿に。それに対する組員。そして敵対組織の反応は……<BR><B>【コメント】 </B>今回はストレートで挑戦。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「ストップ！　ひばりくん」の関東大空組を思い出してしまった担当は……トシですか？（笑）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 任侠（笑） 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yunomachi03.html">「湯の街奇談」第三話</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/6/24(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに意を決したいずみは翔の元に。だが彼には断られてしまい…<BR><B>【コメント】 </B>ほんとにお待たせしました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>翔くんは、やさしいのかな。<BR>
<b><a href="novel/200209/19204751/yunomachi01.html">【第一話はこちら】</a></b><b><a href="novel/200209/19204751/yunomachi02.html">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】  水着・露出 親友萌え 理解ある姉妹</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/dup_boy_ex.htm">着せ替え少年番外編 〜Summer Days, and Yet〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/4/22(木)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>痴漢にあったつかさを助けた女の子と、一日一緒に「女友達」として過ごすことになり……<BR><B>【コメント】 </B>夏の話をもう一度。ちょっと雰囲気が違ったかも。それから文庫さんからウチのサイトに来てくれる人に対しての感謝も。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「Panic Panic」キャラクター乱入編。太字の部分にポイントすると、彼等のプロフィールがちょこっと分かります。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/dup_boy07.htm">着せ替え少年 Dress Up Boy７ 〜剣術小町〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/4/9(金)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>お正月。年始にやってきたおじさんがつかさの体質改善を図るが……<BR><B>【コメント】 </B>一月中投稿の筈が桜の季節に（汗）。新キャラも登場です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おじさん濃いっす（笑）。……もちろん「１号」の人の声で読むこと。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy6_5.htm">着せ替え少年 Dress Up Boy6.5 〜こみっくパーティー〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/2/12(木)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>年末の一大イベントに駆り出されたつかさ、さつき、まこと。しかし彼女たちはそのイベントについて知らなかった。<BR><B>【コメント】 </B>「７」の予定でしたがスピンアウトしてこちらをお送りいたします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>劇中出てきた同人誌、読んでみたい人手を挙げて〜っ（笑）。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yunomachi02.html">「湯の街奇談」第二話</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/1/31(土)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女になってしまったいずみは親友と再会。その一ヵ月後。大きな変化が。<BR><B>【コメント】 </B>公約破りで遅くなってしまいました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>だんだんと女性化していくいずみくん。そして。<BR>
<b><a href="novel/200209/19204751/yunomachi01.html">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 リリカル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy06.htm">着せ替え少年６　〜北へ。〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/11/30(日)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>スキー合宿に来た司たち。意外にスキーの上手い司だったが、そんな男らしい展開が許されるはずもなく（笑）。<BR><B>【コメント】 </B>とうとうやっちゃいました。そして今回はもっとスケールアップした「みんなのおもちゃ」ぶり。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>白銀がつかっちゃんを呼んでいる！　だからミントの言葉で……あれ？<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 コメディ <BR>【種別】 可逆 変身<BR>【キーワード】 コスプレ 着せ替え</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/yunomachi01.html">「湯の街奇談」第一話</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/11/23(日)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>都会暮らしに疲れて帰ってきた青年は実家で入った温泉のせいで運命を変えてしまった…<BR><B>【コメント】 </B>ワイルドピッチすれすれの変化球かも<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>不思議な温泉です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 <BR>【種別】 神秘 変身<BR>【キーワード】 リリカル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex28.html">華代ちゃんシリーズ番外編　ハンターシリーズ外伝「ハンターガイスト」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/11/16(日)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ハンター組織内部の粛清を任務とするハンターガイスト。彼がターゲットにしたのは・・・女子高生？<BR><B>【コメント】 </B>使えるようなら使ってください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いちごちゃんと正に対極的な存在のハンター28号。果たして彼(？)は報われるのか？<BR>
<a href="novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 ハンターシリーズ 年齢変化 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy05.htm">着せ替え少年５　〜プリンセスクエスト〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/10/19(日)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>金欠のつかさはとうとう学校のある日もバイトを。そしてある日曜日、さつきとのデート中に出会った少女は？<BR><B>【コメント】 </B>真城悠さん、この市場さん、ライターマンさんごめんなさい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そしてこちらは「つかっちゃん」サイド。どちらを先に読むかは貴方次第。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/alice_holiday.htm">ありすの休日</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/10/19(日)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>沙紀がもう一軒にかかりきりになり、臨時のメイドを雇うことに。そして休日に遊園地でありすとして遊んでいたら、ふとしたことから真彩香たちとはぐれて。<BR><B>【コメント】 </B>変化球としてはありふれているかも？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>城弾さんの二大なりきりＴＳっ娘が競演。まずは「ありす」サイドから。<BR>
<b><a href="../novel/200209/19204751/maid_of_fire04b.htm">【Ｍａｉｄ ｏｆ Ｆｉｒｅ Ｆ（Another Ending）はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200309/29193018/fms-n.htm">ＦＭＳ：ｐａｔｔｅｒｎ　Ｎ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/9/29(月)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ＦＭＳ発症者が三桁を超え隠蔽しきれなくなったころのニューヨーク。一人の青年がＦＭＳに。<BR><B>【コメント】 </B>魅力的な設定をお借りして僕なりにやってみました。夜夢さんにはこの場をお借りしてお礼申し上げます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>夜夢さんの<a href="../novel/200112/18123055/fms-r.html">「FMS：pattern R」</a>を元に、城弾さんが放つ新たなるFMSエピソード！！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 医療 <BR>【種別】 変身<BR>【キーワード】 ＦＭＳ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/bettabeta.htm">「ベッタベタ」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/8/30(土)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一定条件で入れ替わることの出来る男女の双子。それぞれにデートが舞い込むが…<BR><B>【コメント】 </B>「入れ替わり」は初挑戦。タイトルどおりのベッタベタな展開です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>思いっきり古典的なストーリーを利用した作品です。ですが、登場人物の各々の個性が存分に発揮されている作品でもあります。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 コメディ 恋愛 <BR>【種別】 入れ替わり<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy04.htm">着せ替え少年４　〜ときめきメモリアル〜＆サービスエンディング</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/7/21(月)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>体育祭のアクシデントから目覚めたつかさに異変が。<BR><B>【コメント】 </B>リクエストにお答えしましての第四話です。番外編もおまけ。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おおっ、あそこにいるのは某ミラーワールドなお二人……と思ったらこっちには「四つ葉」な連中が。<BR>
　ますます広がるライダー……もとい、つかっちゃんワールド（笑）。さて今回は……<BR>
<b><a href="novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/kayo_chan80.html">華代ちゃんシリーズ「老人と少女」</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/7/16(水)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>死期の近い老人は財産を狙われていた。そこに現れた華代ちゃんは…<BR><B>【コメント】 </B>予定では「着せ替え少年」でしたが変更して華代ちゃんシリーズ初挑戦です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回の華代ちゃんは可愛い孫娘モードかも。<BR>
<a href="novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 年齢変化 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/maid_of_fire04b.htm">Ｍａｉｄ　ｏｆ　Ｆｉｒｅ　Ｆ（Another Ending）</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/6/1(日)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンテストに女性化させられた俺。運命の選択が「あたし」を……<BR><B>【コメント】 </B>もうひとつのエンディングを公開させていただきます。リクエストに感謝です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶりの城弾さん。……“もしも”お風呂に入っていたら、こんなことになっていたのです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 着せ替え マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy03.htm">着せ替え少年 Ｄｒｅｓｓ ｕｐ ｂｏｙ３ 〜ファーストＫｉｓｓ物語〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2003/2/12(水)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>プールで出会った少年。若菜亮に気にいられてしまったつかさ。そして彼女の唇がピンチに。<BR><B>【コメント】 </B>ご無沙汰してます。久しぶりの「着せ替え少年」です。今回は新キャラ登場です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前回のお医者様に引き続き、今回は“主役”のお三方が特別出演（？）。そして、何やら波瀾の予感が……。<BR>
<b><a href="../novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/maid_of_fire04a.htm">Ｍａｉｄ　ｏｆ　ｆｉｒｅ F</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/12/17(火)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンテストに女性化させられた俺。運命の選択が『あたし」を…<BR><B>【コメント】 </B>『洗い物』で展開です。大差がついた今回。こちらに転んだ場合は予定したエピソードでしたが大多数の御希望に添えたでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>洗い物をするときは、気をつけましょうね。『洗い物』エンディングです。<BR>
<b><a href="novel/200209/19204751/maid_of_fire01.htm">【Vol1はこちら】</a></b><b><a href="novel/200209/19204751/maid_of_fire02.htm">【Vol2はこちら】</a></b><b><a href="novel/200209/19204751/maid_of_fire03.htm">【Vol3はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 強制 着せ替え マッドサイエンテスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/maid_of_fire03.htm">Ｍａｉｄ　ｏｆ　ｆｉｒｅ Vol3</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2002/12/4(水)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンテストに女性化させられた俺。今日１日は沙紀にメイド修行をさせられる羽目に。そのうちに気持ちが……オレの運命は……あんたにあずけた。<BR><B>【コメント】 </B>『少女メイドに成りすます』で展開です。ちょっと間があいちゃってごめんなさい。次がラストになります。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>城弾さんのインタラクティブノベル第三弾。いよいよ最後の洗濯……もとい、選択ですっ。<BR>
<b><a href="novel/200209/19204751/maid_of_fire01.htm">【第一話はこちら】</b></a><b><a href="novel/200209/19204751/maid_of_fire02.htm">【第二話はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 強制 着せ替え マッドサイエンテスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy02.htm">着せ替え少年 〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ２〜 Ｔｒｕｅ　Ｌｏｖｅ　Ｓｔｏｒｙ</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/11/2(土)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>さつきの誕生日祝いにプレゼントを贈ろうとしたが資金が足りない。そこで色々とアルバイトをするが……<BR><B>【コメント】 </B>調子に乗ってもう一回。今回は『着せ替え』の名にふさわしく嵐のようにコスプレです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回はとてつもない人がゲスト出演しています。お医者さんです。黒ずくめです。バイク乗ってます（笑）。<BR>
　……んでもって、つかっちゃんは相変わらず萌え萌えです。<BR>
<b><a href="novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/maid_of_fire02.htm">Ｍａｉｄ　ｏｆ　Ｆｉｒｅ Vol2</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/10/17(木)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンテストに女性化させられた俺。今日１日はメイド姿で過ごす羽目に。この先の行動は…あんたが決めてくれ。<BR><B>【コメント】 </B>『メイド服』で展開しました。さて投票くださった方の意向に添えることができたでしょうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>はてさて、メイド服を着て、メイド気分になってあれやこれやですが、このあとどのようになるかは？です。<BR>
<b><a href="novel/200209/19204751/maid_of_fire01.htm">【Vol1はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 強制 着せ替え マッドサイエンテスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/d_upboy.htm">着せ替え少年 〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ〜</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2002/10/6(日)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>流されやすい性格の少年。二村司は文化祭でウェイトレスをすることになったがそのせいでとんでもない体質が発覚。<BR><B>【コメント】 </B>どちらかと言うとこういうコメディの方が好きです。難しいけど。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>というわけで、超特異体質少年司くん受難の一幕。姉ちゃんがいい味出してます（笑）。<BR>
<b><a href="novel/200209/19204751/d_upboy_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 学園 <BR>【種別】 変身 可逆<BR>【キーワード】 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/maid_of_fire01.htm">Ｍａｉｄ ｏｆ Ｆｉｒｅ −１</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/10/1(火)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンテストに女性化させられた俺。この先の行動は……あんたが決めてくれ。<BR><B>【コメント】 </B>よそで失敗したのですがこちらで再挑戦の変則シリーズです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>城弾さんが放つ、インタラクティブノベル登場！　主人公の運命を決めるのは読者のあなたなのです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 強制 着せ替え マッドサイエンテスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200209/19204751/borderless.htm">ボーダーレス</a></B></TD><TD><B><A href="mailto:IZA00527@nifty.ne.jp">城弾</a></B> さん (<A href="http://homepage3.nifty.com/johdan">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/9/19(木)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=johdan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>１９９９年７月。『恐怖の大王』は確かに降りていた。そして世界は変わる。<BR><B>【コメント】 </B>はじめまして。城弾と申します。皆様に触発されて投稿しました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あの日、あの時……“あれ”がすべての「終わり」であり、そして「始まり」だった。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 変身<BR>【キーワード】 女性人格化 ♀→♂</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(184.73.45.9) , Competence : -1 -->
</BODY></HTML>


