<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu05.htm">星屑の旅人・第五話「秘密」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/6/29(土)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>コロニーを訪れた少女。ふとしたことから彼女と知り合ったクリスは、依頼を受けある人物のもとへ向うことになるが。<BR><B>【コメント】 </B>久々の星屑です。今回はあまり虐められていない様ですが（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>小惑星帯のコロニーに住むいわくありげな女性。彼女の元を訪れようとするひとりの少女……<BR>
隠しキーワードは、「お姉さま」です（笑）。<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 アクション <BR>【種別】 変身 テクノロジー<BR>【キーワード】 強制 メカ 理解ある姉妹／女友達</TD></TR></TABLE><BR><BR>『ｈ．ｈｏｋｕｒａ』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/ruberia.html">ルベリア王室補佐官　エピソード０：「新補佐官誕生す！」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2005/7/5(火)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>王女を庇って死にかけた王室警護官の青年は、王家に伝わる秘薬により王室補佐官の女性として蘇る。<BR><B>【コメント】 </B>あまり萌える部分は少ないかもしれません、むしろ周りの方があたふたしている？<BR><B>【ｈ．ｈｏｋｕｒａ さんのオススメ作品】</B> <A HREF="./novel/ladyguard.html">魔剣物語　～レディ・ガーディアン～</A> <FONT SIZE="-1">(ゴールドアームさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>クーデターの最中、刹那に燃え上がる王女と護衛官の悲恋…………だが、そうは問屋がおろさないのだ（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業 アクション <BR>【種別】 神秘 変身 薬品<BR>【キーワード】 年齢変化 コスプレ 理解ある姉妹／女友達</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/mad_like_pretty_girl.html">マッドサイエンティストは美少女がお好き？</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/12/1(水)</TD><TD>41KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>マッドサイエンティストの『由佳里先輩』と身体が入れ替わった『涼』は正義のヒロインをするハメになるが。<BR><B>【コメント】 </B>かなり久しぶりの投稿になります。入れ替わりものは初めてなんですがいかがでしょうか。<BR><B>【ｈ．ｈｏｋｕｒａ さんのオススメ作品】</B> <A HREF="./novel/robot_triathlon/title.htm">萌え燃えっ！　白塁学園高校女子ロボＴＲＹ部</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なんで、こうなるの？『由佳里先輩』のノリが良すぎです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】  ヒーロー SF <BR>【種別】 入れ替わり 薬品 人格転移 テクノロジー<BR>【キーワード】 特撮 理解ある姉妹／女友達 コスプレ マッドサイエンティスト</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu06.htm">星屑の旅人・第六話「結婚」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/1/8(水)</TD><TD>52KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>知人の結婚式に出る為に訪れたコロニーでクリスが出会った人物とは？<BR><B>【コメント】 </B>時間が掛かりましたが星屑・第六話です。今回のクリスの活躍と受難をお楽しみ下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>結婚……それは人生の転機。新たなる門出。お年頃（笑）のクリスくんにも、はたして春が来るのでしょうか？<BR>
<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 <BR>【種別】 変身 テクノロジー<BR>【キーワード】 親友萌え 花嫁 強制 メカ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/seirei02.htm">精霊戦記シルフィールド２</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/10/19(土)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>異世界から脅威に挑む亜衣（彰）……だがその前に伯母の脅威が（笑）。<BR><B>【コメント】 </B>女の子の生活に困惑する彰。果たしてうまくやっていけるのでしょうか。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前回のラストで、存在そのものが「女の子」になってしまった彰くん。「星屑」のクリスくんとはまたちょっと違う彼……彼女の戸惑いぶりにご注目ください（笑）。<BR>
<b><a href="./novel/200112/11103513/seirei.htm">【第一話はこちら】</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 脳天気な両親 女子更衣室</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/yugeki.htm">巫女遊撃隊</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/8/30(金)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>警察官の薫は妖が起こす様々な事件に挑む、市長直属の組織・妖対策課、通称『巫女遊撃隊』に出向を命じられるが。<BR><B>【コメント】 </B>伝奇ものというにはちょっと軽い感じです。はっきり言って、某巫女委員の影響を受けまくっています（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>巫女遊撃隊。妖という不可思議で常人に対抗できないような存在に対する組織。警察官の薫は妖に対抗する―――!! <BR>さあ、その力ですべてを守れ!?</TD></TR><TR><TD COLSPAN=6>【ジャンル】 伝奇 現代 職業 アクション <BR>【種別】 神秘 変身 コピー 可逆<BR>【キーワード】 年齢変化 強制 コスプレ 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu05.htm">星屑の旅人・第五話「秘密」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/6/29(土)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>コロニーを訪れた少女。ふとしたことから彼女と知り合ったクリスは、依頼を受けある人物のもとへ向うことになるが。<BR><B>【コメント】 </B>久々の星屑です。今回はあまり虐められていない様ですが（笑）。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>小惑星帯のコロニーに住むいわくありげな女性。彼女の元を訪れようとするひとりの少女……<BR>
隠しキーワードは、「お姉さま」です（笑）。<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 アクション <BR>【種別】 変身 テクノロジー<BR>【キーワード】 強制 メカ 理解ある姉妹／女友達</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/seirei.htm">精霊戦記シルフィールド</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2002/5/12(日)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>突然の異世界からの侵略が、平凡だった中学生彰の運命を変える。<BR><B>【コメント】 </B>星屑を書かずこんなものを作りました（笑）。自分のホームぺージでもＴＳ小説（女装物）掲載してますので読んでもらえると嬉しいです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ｈ．ｈｏｋｕｒａさんの新作は巨大ロボットもの。世界を食らう異形の悪意に立ち向かえ！　彰っ！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 メカ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu_04.htm">星屑の旅人・第四話「接触」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/2/8(金)</TD><TD>43KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>航行中の宇宙船で起こったトラブル。救難に向かったクリスが遭遇したものは。<BR><B>【コメント】 </B>秘密の花園（笑）に迷い込んでしまったクリスは、その状況に耐えられるか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>宇宙の海は～、乙女の海～っ♪　……というわけで、いよいよ最年少アストロノーツ・クリスくんの活躍（？）が始まります。<BR>
<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 宇宙 <BR>【種別】  テクノロジー 変身<BR>【キーワード】 メカ 着せ替え 女子更衣室 理解ある姉妹／女友達 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu_03.htm">星屑の旅人・第三話「変化・２」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/1/9(水)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ショッピングの前に食事に行くことになったクリス。だが、そこでも災難が待ち受けていて。<BR><B>【コメント】 </B>自分の身体にさらに困惑するクリス。ショッピングシーンはさらっと流しすぎたかもしれません。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>謎の遺跡の力で女の子になったクリスくん。パワフルなお姉様方（＆お母上）に囲まれて、彼……彼女の試練（？）はまだまだ続きそうです。<BR>
<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 宇宙 <BR>【種別】  テクノロジー 変身<BR>【キーワード】 着せ替え ショッピング 理解ある女友達 脳天気な親</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu_02.html">星屑の旅人・第二話「変化・１」</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2001/12/28(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>美少女に変身してしまったクリスに迫る女性陣。はたして彼（彼女）の運命は。<BR><B>【コメント】 </B>女性の身体に困惑するクリス。だが、周りはそんなクリスの気持ちなどお構いなし。<BR>
　クリスに安息の日はくるか。（来ないだろうな、周りがあれじゃ……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>あわれクリスくん八方塞がり。……観念して、美少女アストロノーツの道を歩みなさいってば（笑）。<BR>
<b><a href="./novel/200112/11103513/hosikuzu_01.html">第一話</a></b>も修正バージョンに差し替えました。<BR>
<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 宇宙 <BR>【種別】  テクノロジー 変身<BR>【キーワード】 鏡 理解ある姉妹／女友達 脳天気な親</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200112/11103513/hosikuzu_01.html">星屑の旅人-TSバージョン-</a></B></TD><TD><B><A href="mailto:fwix1264@mb.infoweb.ne.jp">ｈ．ｈｏｋｕｒａ</a></B> さん (<A href="http://homepage2.nifty.com/rakugaki-maimu/index.html">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2001/12/11(火)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=h_hokura">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>小惑星で発見された謎の遺跡、運送屋の宇宙艇パイロットのクリスは突如作動したその遺跡により美少女に変身させられてしまう。<BR><B>【コメント】 </B>自分のホームページに書いている小説の設定を使ったＴＳバージョンの作品です。できればそちらも読んでほしいです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>……TSっ娘が周りの女性達にいじり倒される(笑)のはもはや避けられない運命なのです。あはれクリス君。<BR>
<b><a href="./novel/200112/11103513/title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 宇宙 <BR>【種別】  テクノロジー 変身<BR>【キーワード】 鏡 アイテム 脳天気な両親 理解ある姉妹／女友達 強制</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.146.98.143) , Competence : -1 -->
</BODY></HTML>


