<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h07.html">Ａｎｇｅｌ・Ｈｙｐｅｒ -7th</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/24(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>キルの”理想郷”に連れ込まれた優たち。そこで出会う最強の４人組に優たちは悪戦苦闘！<BR><B>【コメント】 </B>主に戦いのシーンが多いです。果たして５人は無事に脱出出来るのでしょうか……。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>キルに分断され、異世界に閉じ込められた優ちゃんたち。襲いかかる刺客！！　脱出なるかっ！？<BR>
　……けど、日本人でもフランス人でも、ＴＳしたら普通混乱するってば（笑）。<BR>
<b><a href="../novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 猫剣士 異形 天使 異世界</TD></TR></TABLE><BR><BR>『驟雨』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h08.html">Ａｎｇｅｌ・Ｈｙｐｅｒ　The 8th story</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/2/16(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>理想郷に強制転移させられた６人。相対する刺客達を次々と撃破していく６人だったが、最強の刺客・スペイドの前に優＆ゼロは…（これまでのあらすじは本編を参照ください）<BR><B>【コメント】 </B>長く間が空いてしまいました。どうか、これからもよろしくお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>１年半のブランクを経て、驟雨さんが天使たちとともに帰ってきました。<BR>
異空間での戦いはますます熾烈を極める……優とゼロ、そして愛美たちの運命は！？<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 ファンタジー <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h07.html">Ａｎｇｅｌ・Ｈｙｐｅｒ -7th</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/24(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>キルの”理想郷”に連れ込まれた優たち。そこで出会う最強の４人組に優たちは悪戦苦闘！<BR><B>【コメント】 </B>主に戦いのシーンが多いです。果たして５人は無事に脱出出来るのでしょうか……。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>キルに分断され、異世界に閉じ込められた優ちゃんたち。襲いかかる刺客！！　脱出なるかっ！？<BR>
　……けど、日本人でもフランス人でも、ＴＳしたら普通混乱するってば（笑）。<BR>
<b><a href="../novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 猫剣士 異形 天使 異世界</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/haou_03.html">霸王　〜haou〜　後編</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/20(水)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>そして最後の任務に就く一秀。失敗は許されない。物語はいよいよクライマックス！<BR><B>【コメント】 </B>正直この小説は難しかったです。こんなに推敲したのも初めて・・？（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>敵地に乗り込む一秀たち。しかし、そこで彼らを待ち受けていたものとは……？<BR>
<strong><a href="novel/200401/04203552/haou_01.html">【前編はこちら】</a><a href="novel/200401/04203552/haou_02.html">【中編はこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 <BR>【種別】 変身<BR>【キーワード】 暗黒街 謎解き 裏世界 アイテム</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/haou_02.html">霸王　〜haou〜　中編</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/20(水)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>暗黒街で仕事をこなす一秀に、魔の手が忍び寄る。それを救った人物は一秀が一番・・・<BR><B>【コメント】 </B>今までで一番描写にこっていると思います。暗黒街なんて私、知りませんから(笑)<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>翠との出会い。そして、驚くべき事実。一秀は自分の中のある感情に気づく。<BR>
<strong><a href="novel/200401/04203552/haou_01.html">【前編はこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 <BR>【種別】 変身<BR>【キーワード】 暗黒街 謎解き 裏世界 理解ある男友達 アイテム</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/haou_01.html">霸王　〜haou〜　前編</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/20(水)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>若くして暗黒街の”霸王”と呼ばれるようになる主人公。暗黒街で生きる手段は１つを除けば選ばない。そういう生活を送っていた主人公に、ある夜１人の老人との出会いですべてが変わろうとしていた。<BR><B>【コメント】 </B>また変なのを書いちゃいました。３本くらいで済ませようかと。（っていうなにしてんだ驟雨！）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>暗黒街に生きる男、霸王。そんな彼が、初めて「友」という存在を知る。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 学園 <BR>【種別】 <BR>【キーワード】 暗黒街 謎解き 裏世界 理解ある(今は)男友達</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h06.html">Ａｎｇｅｌ・Ｈｙｐｅｒ - 6th</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/9/14(火)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>助けに来たつもりが逆にピンチに！２度あることは・・<BR><B>【コメント】 </B>大会を挟んで全然執筆出来ませんでした。やっと完成しましたので・・これからの展開、発展にご期待ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法が使えない世界。魔法を使う者としては、地獄とも言える世界でもある。<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 猫剣士 異形 天使 異世界</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/the_othello.html">The Othello</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/8/25(水)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「彼」の登場にクラスの生徒は振り回される？それとも自分から動き出す？<BR><B>【コメント】 </B>現実にこんなゲームもアリ？たまには短編もいいかなと思いまして。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>目の付け所がなんとも斬新です。さぁ、あなたは黒を選ぶ？それとも白？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 不思議 学園 <BR>【種別】 変身 アイテム<BR>【キーワード】 ♀→♂ オセロ 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h05.html">Ａｎｇｅｌ・Ｈｙｐｅｒ - 5th</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/8/19(木)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>謎に包まれる複数の人物。そして明らかになる真の敵。<BR><B>【コメント】 </B>とりあえず２人目——とでも言っておきましょうか（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>優、初の作戦は失敗。だが、貴重な情報を入手することとなった。<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 猫剣士 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h04.html">Ａｎｇｅｌ・Ｈｙｐｅｒ - 4th</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/8/11(水)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>優に課せられる初めての任務。なぜそうなってしまうかは本編参照……。<BR><B>【コメント】 </B>潜入系です。（意味不明）新キャラも登場の「４ｔｈ　ｓｔｏｒｙ」お楽しみください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>初の任務はシティホテルへの侵入作戦。任務は無事成功するのか！？<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 猫剣士 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h03.html">Ａｎｇｅｌ・Ｈｙｐｅｒ - 3rd</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/24(土)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>優は謎の２人組（？）のことを知りたくてたまらない。首を突っ込む優に再び悪夢が……？　そして久しぶりの彼も登場。<BR><B>【コメント】 </B>え〜読んでくださった方も分かるように、『Ａｎｇｅｌ・Ｈｙｐｅｒ』は一話一話が短いです。私としては長からず短からずが目安なのですけど・・。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>愛美に久しぶりにあう健一。彼は、何を伝えたかったのか……。<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h02.html">Ａｎｇｅｌ・Ｈｙｐｅｒ - 2nd</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp ">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/19(月)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>今まで語られる事の無かった優の生活。部活に打ち込む夏の風景、そして新たな影。<BR><B>【コメント】 </B>小説の起承転結のうち、「起」がやっと完成しました。 １ｓｔの内容は本当にプロローグみたいなものでしたので。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>学校生活の醍醐味のひとつ挙げよと言われれば、部活でしょう。大会を勝ち抜くためにコーチも必死だったり。<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_h01.html">Ａｎｇｅｌ・Ｈｙｐｅｒ</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/11(日)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>優視点ではじまる新版第一作目をお楽しみください……。<BR><B>【コメント】 </B>前作『Ａｎｇｅｌ最終話』から２年半後。それぞれの人物が成長した姿をご覧ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>主役は優ちゃん！！　もちろん愛美たちも元気です。<BR>
<b><a href="novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_ex03.html">Ａｎｇｅｌ 続・番外編『潜入！　朝布学園』</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/26(水)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>学校の七不思議、いろいろな事件、そして潜入する理由と言ったら！？<BR><B>【コメント】 </B>久しぶりに帰って参りました、健一と愛美です。この番外編は本編とちょっと離れた視点で見て欲しいです。設定は同じですが、キャラクターの出てくる時期などは本編と違っています。<BR>
　早い話、「番外編最終以後、２人が魔法を使える」と考えていただければ良いわけです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>帰ってきました愛美＆健一。ひょんなことから夜の学校を訪れた彼女たちが体験する、摩訶不思議な出来事とは？<BR>
<b><a href="../novel/200401/04203552/angel_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/ts_sunshine.htm">T.S. Sunshine</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/21(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>町行く男性は皆白ずくめ。けっして肌を露出しない。それには理由があった……<BR><B>【コメント】 </B>実際にこの世がこんな風だったら人間の子孫は絶えていたでしょうね（笑）。ややコメディタッチな学園ものをご覧ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>異世界の日本。ここではいつの頃からか、太陽の光で珍奇な現象が起きていた……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/seven_keys_1.htm">Seven Keys　第１話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/14(金)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>妖精として、『能力者』として使命を果たすことになったルーフ。新たな仲間も加わり、宇宙の旅は続く・・<BR><B>【コメント】 </B>設定を何度も何度も変えて書き上げるのに苦労しましたが、そんなに良い出来ではないですね・・。描写はかなり書き加えましたので長くなり＆遅くなりました。こんな作品ですが、読んでくださればありがたいです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>旅の始まりです。<BR>
<b><a href="novel/200401/04203552/seven_keys_pro.htm">【プロローグはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 宇宙 アクション <BR>【種別】 変身<BR>【キーワード】 メカ （オレっ娘）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/seven_keys_pro.htm">Seven Keys　プロローグ</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/1(土)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>広大な宇宙にある３つの楔。その楔を守る３人の「能力者」。そして能力者の１人に重大な危機がせまる・・。<BR><B>【コメント】 </B>長編を前提にこのＳｅｖｅｎ　ｋｅｙｓを作成しました。宇宙のことについてはよくわからないのですが・・（爆　とにかくがんばりました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>驟雨さんの新しい長編?の始まりです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 アクション <BR>【種別】 変身<BR>【キーワード】 コメディ（ほんのちょっと） メカ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/desire.htm">Ｄｅｓｉｒｅ</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/25(日)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>通う学校は元女子高。そんな環境では考えてしまうかもしれない願い。<BR><B>【コメント】 </B>私もこんな環境ですので思ったことも少なからずあったりします。（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>女の子たちの中に男ひとり。だったらハーレム状態？　……いえいえとんでもない（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_ex02.html">Angel 番外編最終話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/23(金)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B>Ａｎｇｅｌシリーズ最後の最後となりました。最後まで読んでいただき、まことにありがとうございます。いろいろなアドバイス、意見を聞きました。それによって成長していけたらいいと思います。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>二人の気持ち、言葉では表しきれない気持ち。それが、永遠に続くよう——。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_ex01.html">Ａｎｇｅｌ 番外編 第１話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/11(日)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新年の訪れとともにひと足早い桜が咲く。そして・・・<BR><B>【コメント】 </B>その後の展開をご覧ください・・<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>初もうでに出掛ける人々。それぞれ複雑な気持ちを胸に秘めているわけですよ。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_12.html">Ａｎｇｅｌ 最終話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/10(土)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついにゼロとの最終決戦。愛美と健一は守ることができるのか……そしてついに！<BR><B>【コメント】 </B>と、ついに終わりですね。ここまで続いたＡｎｇｅｌ、読んでくださった皆さまに感謝感謝！！♪<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法界とゼロとの戦争が終わり、平穏が訪れた。二人は、言いたくても言い出せなかった言葉を、今——。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_11.html">Angel 第11話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/28(日)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ゼロの攻撃を必死に防ぐ愛美達。そして新たな仲間と出会って愛美の気持ちは大きく変わっていく……<BR><B>【コメント】 </B>仲間の大切さを覚えてくださればいいと思います。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ついに始まる、ゼロと魔法界との全面戦争。指揮官となった愛美は、仲間と一緒に戦場に躍り出る。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_10.html">Angel 第10話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/25(木)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>亡くなった幸二の蘇生を試みる愛美たち。そして魔法界に重大な事件が——<BR><B>【コメント】 </B>終焉までのつなぎがとんでもない展開になってしまいました。こんな小説ですが、読んでくだされば幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法界への宣戦布告。神と呼ばれたその人物。それが、地球を侵略しようとしていた……。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_09.html">Angel 第9話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/18(木)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>季節の移り変わりとともに事件事故が大連発！ 愛美と健一の距離もぐっと近くなって・・・<BR><B>【コメント】 </B>初めに比べてだいぶ進み方が早くなってしまいました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>駅前の『シュール』に車が突っ込んだ。そこには健一が……！<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_08.html">Angel 第8話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/3(水)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>だんだんと女の子化、男の子化が進む２人。心の変化も現れたようです。<BR><B>【コメント】 </B>こういうシーンを描くのは難しかったのでもっと修業したいと思います。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>サッカーの大会に、全校あげての応援。愛美は健一を応援する。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_07.html">Angel 第7話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/3(水)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>咲香を愛美のバティクスにするために魔法大聖堂へ向かった愛美と健一。聖兵との戦いの行方は・・！<BR><B>【コメント】 </B>舞台が一気に広がってヨーロッパのある地まで飛びました。ちょっと行きすぎました・・・<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>聖兵との戦いは楽ではなかった。愛美と健一は傷を負いつつも——。<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_06.html">Ａｎｇｅｌ 第6話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/2/17(火)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>修了式の日、不思議な生物に出会った健一と愛美。その出会いによってまた大きく２人の生活は変わっていく……<BR><B>【コメント】 </B>今回よりジャンルのファンタジーについていた（？）は消えました。本格的なファンタジーなストーリーになってきました。魔法生物やらモンスターやらがいろいろ出てきます。（アララ）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>学校に一本しかないＥ♭クラリネットを壊したのは、なんと——<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_05.html">Ａｎｇｅｌ 第5話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/2/9(月)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>健一の素直になれない気持ちと愛美の望みの入れ違い。そして女の子として初めての水泳の授業に健一は苦労の連続！<BR><B>【コメント】 </B>途中から呼び方が逆転して分かりにくいかもしれないですがすみません。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いくら精神の女性化が進んでいても、思考が女の子になってきているといえども、やはり着替えは恥ずかしい……？<BR>
<B>【お知らせ】</B>作品設定資料が公開されました！<BR>
<B><A HREF="novel/200401/04203552/angel_title.html">【シリーズタイトル＆設定資料集はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー（？） 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_04.html">Ａｎｇｅｌ 第4話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD><B>画</B>(<B>田代憂</B>さん)</TD><TD>2004/1/29(木)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>文化祭に向けて練習に励む俺、石垣愛美。それをサポートする本物の愛美。しかし文化祭直前に悲劇が・・（？）<BR><B>【コメント】 </B>全体的に悲しい内容です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>文化祭の最後を飾る部活の演奏で起こる、２つの悲劇。<BR>
<a href="novel/200401/04203552/angel_title.html"><strong>【シリーズタイトル＆設定資料集はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー（？） 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_03.html">Ａｎｇｅｌ　第3話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/1/16(金)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>石垣愛美によって魔法をかけられて自分が石垣愛美になってしまった七瀬健一。<BR>
しかも元の体にはその愛美の意識が入り込んで、しかも天使化していた。魔法も使える天使に。<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>初めてじゃないのに初めて。身の回りの環境が変わって、学校を新鮮に感じる……か？<BR>
<a href="novel/200401/04203552/angel_title.html"><strong>【シリーズタイトル＆設定資料集はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー（？） 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_02.html">Ａｎｇｅｌ　第２話</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/1/10(土)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>石垣愛美によって魔法をかけられて自分が石垣愛美になってしまった七瀬健一。しかも元の体にはその愛美の意識が入り込んで、しかも天使化していた。魔法も使える天使に。とりあえずよくわかってない健一君のためによくよく説明する愛美だったが急に倒れてしまう。机に置いてあったメモに書いてあったのは———<BR><B>【コメント】 </B>ちょっと萌え？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>魔法使いとしての素質を持つ妹。<BR>
<a href="novel/200401/04203552/angel_title.html"><strong>【シリーズタイトル＆設定資料集はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー（？） 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200401/04203552/angel_01.html">Ａｎｇｅｌ</a></B></TD><TD><B><A href="mailto:gensan@k8.dion.ne.jp">驟雨</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/1/4(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_sakuhin_no115.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高校１年生の七瀬健一は同じクラスの石垣愛美に恋心を抱いていた。しかしある事件から愛美の事実を知ってしまう。その代償（つぐない）として……。<BR><B>【コメント】 </B>休みを利用して前々から書きたかった少年少女文庫第１作目です。がんばりましたつもりです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さわらぬ神に祟りなし……なーんてね。<BR>
<a href="novel/200401/04203552/angel_title.html"><strong>【シリーズタイトル＆設定資料集はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー（？） 恋愛 学園 <BR>【種別】 入れ替わり 魔法 変身<BR>【キーワード】 異形</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(34.229.131.116) , Competence : -1 -->
</BODY></HTML>


