<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/d_hunter03.htm">デビルズ・ハンター 第３話</a></B></TD><TD><B><A href="mailto:m-mako.s6346@k8.dion.ne.jp">キング</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/12/4(水)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>た、田辺に見られてしまった！？どうしよう・・・俺・・・何もいえない・・・　<BR><B>【コメント】 </B>どうも！キングです！おかげさまで３話に突入です！どんどんかっこいい作品にしていきたいと思います！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>封印されているとこを、見事に見られてしまった……が、ひょんな事からその学校に通うことに……。<BR>
<a href="./novel/200211/29202848/d_hunter01.htm"><strong>【第一話はこちら】</strong></a><a href="./novel/200211/29202848/d_hunter02.htm"><strong>【第二話はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR>『キング』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/badmin_girl01_2nd.html">BADMINTON　GIRL　第1話（訂正版）</a></B></TD><TD><B><A href="mailto:m-mako.s6346@k8.dion.ne.jp">キング</a></B> さん (<A href="http://f6.aaacafe.ne.jp/~kinngu/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/2/15(土)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>俺は、その日まで普通の男子中学生だったが、あるやっかいな幸せ妖精によって女子に変えられてしまった。元に戻れる方法は・・・女子バドミントン部で全国大会！？　これから長い女子生活が始まりそうだ。<BR><B>【コメント】 </B>久しぶりに投稿しました。訂正版ですみません。前のは失敗作だったので。というわけで、これからもよろしくお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><A HREF="/novel/200211/29202848/badmin_girl01.html">第１話</A>の訂正版です。色々変わっているので、よく見てみてはいかが？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 スポーツ <BR>【種別】 変身<BR>【キーワード】 バドミントン</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/badmin_girl01.html">BADMINTON　GIRL　第１話</a></B></TD><TD><B><A href="mailto:m-mako.s6346@k8.dion.ne.jp">キング</a></B> さん (<A href="http://www.geocities.co.jp/AnimeComic-Name/6693/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2003/1/11(土)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>風間裕樹は、「浜崎学園」男子バドミントン部レギュラーだ。彼のスマッシュは、男子バドミントン部一だった。だが、そこに見知らぬ妖精が現れて……<BR><B>【コメント】 </B>どうも、読者の皆さん！　キングです。「デビルズ・ハンター」もまだ途中ですが、新作を書きたくなって投稿しました。こちらの方も応援よろしくお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>キングさんの新作は、自称「幸せ妖精」が引き起こすトラブル・ストーリー。……果たして風間くんの運命は？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 スポーツ 学園 <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/d_hunter04.htm">デビルズ・ハンター 第４話</a></B></TD><TD><B><A href="mailto:m-mako.s6346@k8.dion.ne.jp">キング</a></B> さん (<A href="http://www.geocities.co.jp/AnimeComic-Name/6693/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2002/12/20(金)</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ピンチの俺の前に現れた謎の男！　……こいつ……何者なんだー！？<BR><B>【コメント】 </B>どうも！　キングです！　４話です！　そこで、皆様からの『悪魔』を大募集したいと思います！　もしこんな悪魔を出して欲しいという方があれば、名前や体長、特徴など、いろいろ書いて私にメールで送ってください。お願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>正体不明な謎の助っ人（？）に、怒り心頭のキロくんですが……。<b><a href="../novel/200211/29202848/d_hunter01.htm">【第１話はこちら】</b></a><b><a href="../novel/200211/29202848/d_hunter02.htm">【第２話はこちら】</b></a><b><a href="../novel/200211/29202848/d_hunter03.htm">【第３話はこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/d_hunter03.htm">デビルズ・ハンター 第３話</a></B></TD><TD><B><A href="mailto:m-mako.s6346@k8.dion.ne.jp">キング</a></B> さん </TD><TD>(イラストなし)</TD><TD>2002/12/4(水)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>た、田辺に見られてしまった！？どうしよう・・・俺・・・何もいえない・・・　<BR><B>【コメント】 </B>どうも！キングです！おかげさまで３話に突入です！どんどんかっこいい作品にしていきたいと思います！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>封印されているとこを、見事に見られてしまった……が、ひょんな事からその学校に通うことに……。<BR>
<a href="./novel/200211/29202848/d_hunter01.htm"><strong>【第一話はこちら】</strong></a><a href="./novel/200211/29202848/d_hunter02.htm"><strong>【第二話はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/d_hunter02.htm">デビルズ・ハンター 第２話</a></B></TD><TD><B>キング</B> さん </TD><TD>(イラストなし)</TD><TD>2002/12/2(月)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>女の子に変身し、人間界へ旅立とうとする俺だったが、人間界へ行くには、『魔法駅』に入らなくてはいけないらしい。さあ、俺にどんな試練がまちかまえているのか！？<BR><B>【コメント】 </B>どうも！　キングです！　どうやらみなさまから某作品に似てきたという感想があるみたいですね！　まあ、パクろうなどとはぜんぜん思っていませんし、そのところはよろしくお願いします。あと、こっちにはこっちの楽しさがあると思います。ってなわけで、これからも応援よろしくお願いします！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>第２話の公開に伴って、第１話も大幅に改定されました。まずはそちらからお読みください。<BR>
<a href="./novel/200211/29202848/d_hunter01.htm"><strong>【第一話はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200211/29202848/d_hunter01.htm">デビルズ・ハンター 第１話</a></B></TD><TD><B>キング</B> さん </TD><TD>(イラストなし)</TD><TD>2002/11/29(金)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=king">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>謎の『悪魔箱』を開けてしまったキロは、女の子に変身して悪魔退治をすることに……さあ！　どうなる！？<BR><B>【コメント】 </B>どうも！　男なので、女子が登場の小説を書くのは難しいけど、がんばります！　よろしく！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>初登場キングさんの作品は、ちょっとした好奇心から災厄を招いた少年のお話。まずはプロローグから……<BR>
（修正版と差し替えました）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.226.36.60) , Competence : -1 -->
</BODY></HTML>


