<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld3-2.html">デュアルワールド第３楽章　『ストラグル』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp ">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/7/14(火)</TD><TD>56KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに始まった、ジェーンたちと四大天使の衝突。試されるのは、戦いの力だけじゃない。<BR><B>【コメント】 </B>次です、次！　待ってください！（何を）<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200703/23200707/sary_index.html">救世主サリーエンジェル</A> <FONT SIZE="-1">(ＮＡＴＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>圧倒的な筆力で紡がれる戦い。勝利した者たちも深く傷つき、別れ……そして意外な展開。<BR>
　デュアルワールド、佳境へ。<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】  ボクっ娘 フルメタルワイルドの歌のフレーズ</TD></TR></TABLE><BR><BR>『バレット』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw05.html">デュアルワールド・リライト　『アウトロダクション』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/4/15(木)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその５つ目です。ＡＧ２をベースとし、新展開でジェーンの萌えシーンをお届けしたいと思います。ジェーンはやっぱり、おもちゃにされる運命なのかな？<BR><B>【コメント】 </B>ここまで読んでくださった皆様に、感謝の意を込めてお礼を申し上げます。ありがとうございました、そしてお疲れ様でした。そんな皆様に、フリューゲルの夜這いという大特典がついて（爆<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200703/16205836/saila_title.htm">戦乙女セーラ</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>デュアルワールド・リライト全五章完結。おつかれさまでした。そしておまけは不幸な？勇者様の……おっと、それは読んでのお楽しみ♪<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 「これも仕事って事で。」 ボクっ娘 水着</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw05.html">デュアルワールド・リライト　『アウトロダクション』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/4/15(木)</TD><TD>36KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその５つ目です。ＡＧ２をベースとし、新展開でジェーンの萌えシーンをお届けしたいと思います。ジェーンはやっぱり、おもちゃにされる運命なのかな？<BR><B>【コメント】 </B>ここまで読んでくださった皆様に、感謝の意を込めてお礼を申し上げます。ありがとうございました、そしてお疲れ様でした。そんな皆様に、フリューゲルの夜這いという大特典がついて（爆<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200703/16205836/saila_title.htm">戦乙女セーラ</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>デュアルワールド・リライト全五章完結。おつかれさまでした。そしておまけは不幸な？勇者様の……おっと、それは読んでのお楽しみ♪<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 「これも仕事って事で。」 ボクっ娘 水着</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw04.html">デュアルワールド・リライト　『リフレイン』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/3/20(土)</TD><TD>44KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその４つ目です。しぶとさと恐ろしさを第３楽章から継承しているイロウルを、ジェーンとクリシュナが迎え撃ちます。<BR><B>【コメント】 </B>パロディもここまでくると自分で自分に真っ黒な拍手を送りたいです。あの技はあんなにも輝いているのに。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200604/21135117/medarot_m01.htm">メダロットＭ１<a href="../novel/200604/21135117/medarot_m02.htm">・２</a><a href="../novel/200604/21135117/medarot_m03.htm">・３</a></A> <FONT SIZE="-1">(流離太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>互いに譲れないものがあるから、全力で戦う。そして、醜い大人は目先のことしか見えていない。<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 魔砲少女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw04.html">デュアルワールド・リライト　『リフレイン』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/3/20(土)</TD><TD>44KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその４つ目です。しぶとさと恐ろしさを第３楽章から継承しているイロウルを、ジェーンとクリシュナが迎え撃ちます。<BR><B>【コメント】 </B>パロディもここまでくると自分で自分に真っ黒な拍手を送りたいです。あの技はあんなにも輝いているのに。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200604/21135117/medarot_m01.htm">メダロットＭ１<a href="../novel/200604/21135117/medarot_m02.htm">・２</a><a href="../novel/200604/21135117/medarot_m03.htm">・３</a></A> <FONT SIZE="-1">(流離太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>互いに譲れないものがあるから、全力で戦う。そして、醜い大人は目先のことしか見えていない。<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 魔砲少女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw03.html">デュアルワールド・リライト　『インタールード』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/3/4(木)</TD><TD>52KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその３つ目です。満月の夜、そして天使たちとの直接対決となります。<BR><B>【コメント】 </B>いよいよ、戦いの火蓋は切って落とされます。うまく描けていればいいのですが。誰より、魔法少女フリューゲルを。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200206/05220532/leaf01.htm">魔法少女リーフ１〜５話</A> <FONT SIZE="-1">(優さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＶＳ怪盗・満月の夜。だが、イロウルやイスラフェル——ドゥンケルリッターの乱入で、事態は混迷を極めていく……<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘 イスラフェルが倒せないから降参だけは最後まで取っておく</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw03.html">デュアルワールド・リライト　『インタールード』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/3/4(木)</TD><TD>52KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその３つ目です。満月の夜、そして天使たちとの直接対決となります。<BR><B>【コメント】 </B>いよいよ、戦いの火蓋は切って落とされます。うまく描けていればいいのですが。誰より、魔法少女フリューゲルを。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200206/05220532/leaf01.htm">魔法少女リーフ１〜５話</A> <FONT SIZE="-1">(優さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＶＳ怪盗・満月の夜。だが、イロウルやイスラフェル——ドゥンケルリッターの乱入で、事態は混迷を極めていく……<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘 イスラフェルが倒せないから降参だけは最後まで取っておく</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw02.html">デュアルワールド・リライト　『ブリッジ』</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2010/2/17(水)</TD><TD>33KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその２つ目です。ジェーンが湖でライブを繰り広げるシーンは、今回のイチオシです！<BR><B>【コメント】 </B>実は『ジークフリード』は英雄に送られる称号だったのです。オリジナルのデュアル作成当初から予定していたジークフリードの本当の名前を、今回になってやっと発表できました。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan84.html">華代ちゃんシリーズ『落ちこぼれ』 </A> <FONT SIZE="-1">(逆流人さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>デュアルワールド・リライト第二弾。萌え度二割増しで、ＴＳっ娘の不幸？は密の味（笑）。<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 とんでもないものを盗んで行きました ボクっ娘 水着</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw01.html">デュアルワールド・リライト　『プレリュード　〜　バース』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/2/8(月)</TD><TD>45KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその１つ目です。ジーク旅団と満月の夜が出会う日からはじまります。<BR><B>【コメント】 </B>単なるリニューアルにならないよう、みんなの見せ場を多くしてみました。今回から始まる『リライト』は、満月の夜事件の流れの中に第１楽章から第３楽章までのみんなの魅力をギュッと詰めて煮込んだ「てんこ盛り」となっている……　はずです？<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200712/22231343/dualworld2-5.html">デュアルワールド第２楽章・怪盗クリシュナ編１／<a href="../novel/200712/22231343/dualworld2-6.html">２／</a><a href="../novel/200712/22231343/dualworld2-6.html#half">３／</a><a href="../novel/200712/22231343/dualworld_ex2.html">ＡＧ２</A> <FONT SIZE="-1">(バレットさん作)（僕です）汗</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自作品を書き直す……それって大変なことだと思います。はたしてどんな風にグレードアップされているのでしょう？<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘 フリューゲルの暗黒面</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualrw01.html">デュアルワールド・リライト　『プレリュード　〜　バース』</a></B></TD><TD><B>バレット</B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2010/2/8(月)</TD><TD>45KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二楽章第中盤のリライトバージョン、今回はその１つ目です。ジーク旅団と満月の夜が出会う日からはじまります。<BR><B>【コメント】 </B>単なるリニューアルにならないよう、みんなの見せ場を多くしてみました。今回から始まる『リライト』は、満月の夜事件の流れの中に第１楽章から第３楽章までのみんなの魅力をギュッと詰めて煮込んだ「てんこ盛り」となっている……　はずです？<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200712/22231343/dualworld2-5.html">デュアルワールド第２楽章・怪盗クリシュナ編１／<a href="../novel/200712/22231343/dualworld2-6.html">２／</a><a href="../novel/200712/22231343/dualworld2-6.html#half">３／</a><a href="../novel/200712/22231343/dualworld_ex2.html">ＡＧ２</A> <FONT SIZE="-1">(バレットさん作)（僕です）汗</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自作品を書き直す……それって大変なことだと思います。はたしてどんな風にグレードアップされているのでしょう？<BR>
<b><a href="../novel/200712/22231343/dualrw_title.html">【新シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘 フリューゲルの暗黒面</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld_ex5.html">デュアルワールドＡＧ　『はじまりのステージ』 </a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2009/12/23(水)</TD><TD>45KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>リンドワームの戦いから１年。ミミルを元気にしようと、大陸初のロックバンドが結成される。ガールズバンド『カールスフェルト』が奏でる大爆音は、人々の心に響くのだろうか！（『フロンティアに響く歌』）／　自宅に帰ってきた出版社帰りのロロの下宿先に、パートシュクレが何故か待ち構え、ポルックスに取材をねだりだす。その取材内容とは……？（『ロロの受難　ツヴァイ』）／　一足早い受験勉強に取り組んでいた翔と柳。そんな彼らのアパートに、軽音楽部の仲間たちが押し寄せてくる。ボケ担当と変人しかいない軽音楽部に付き合わされる２人だが、これはこれで楽しい思い出になるんじゃないかな♪（『夏は海でしょう』） 　……ほか数話（数えろよ作者）。<BR><B>【コメント】 </B>全体的にとんでもなくバカ臭く、かつ『デュアル』には珍しく若干……？　いや、かなり色気のあるシーンが（以下自粛）。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200112/19020205/angelterm1.html">天使の携帯端末（前編）／<a href="../novel/200112/19020205/angelterm2a.html">（後編・パターンＡ）／</a><a href="../novel/200112/19020205/angelterm2b.html">（後編・パターンＢ）</a></A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>バレットさんお得意の、ショートショートつるべ撃ちっ！　何故か<a href="../novel/200908/13230349/shout_a.html">『シャウト！』</a>の面々も登場して、賑やかな後日談（？）です。<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート コメディ <BR>【種別】 薬品 変身<BR>【キーワード】 ロックバンド ♀→♂ 強制 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld4.html">デュアルワールド第四楽章　『ヴェステンに萌えた芽』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/10/18(日)</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>リンドワームとの戦いも終わり、日常が戻った。だが、すべてが元通りになったわけじゃない、すべてはここから始まる。大陸の歴史も、フルメタルワイルドの未来も。そして、モニカの愛の形は……<BR><B>【コメント】 </B>ここまで読んでくださった方がいらっしゃれば、その方には感謝してもし尽くせません。ありがとうございました。 （いつかどこかでコンクルードさせることができるといいなぁ……）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「デュアルワールド」まずはひとときのお別れ……旅の仲間たちの行く末に希望あれ。そしてジェーン——ジョニーとモニカは……<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200908/13230349/shout_b.html">シャウト！　−Ｄｉｓｃ　２−</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/9/4(金)</TD><TD>48KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>軽音楽部バンド『シャウト』のステージがはじまり、人々はロックの爆音の応酬に沸き立つ。そして、ばらばらだった人々の想いは、やがて１つの和音となれるのだろうか。＆ボーナストラック２曲収録。<BR><B>【コメント】 </B>僕、アメリカのロックバンドのとある曲を聞いて泣いたのですが、腐っているでしょうか……？（爆）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>未来を信じているから、今を力一杯生きていける。柳ちゃんと両親の仲は？　軽音楽部『シャウト』の行く末は？　そして入れ替わったままの二人は……？<b><a href="../novel/200908/13230349/shout_a.html">【−Ｄｉｓｃ　１−はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 学園 <BR>【種別】 入れ替わり<BR>【キーワード】 「騙された気分はどうだい？」 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200908/13230349/shout_a.html">シャウト！　−Ｄｉｓｃ　１−</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/8/13(木)</TD><TD>47KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>無趣味な軽音楽部員・新穂翔は、毎朝一緒に登校している少女、青島柳と入れ替わってしまう。すべてにおいて極度に消極的な柳に笑顔を取り戻すべく、翔は軽音楽部員とともに文化祭で一緒に歌おうと柳にもちかけ、その中で自分も目標に向かいはじめる。＆ボーナストラック１曲収録。<BR><B>【コメント】 </B>ローラーブレードでの登校というと、ある魔法少女を思い起こさせますがいかがです？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自分じゃない“自分”と向き合う……入れ替わりストーリーの王道です。でも、まわりの人たち、納得力ありすぎゃしないか？（＾＾；</TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 学園 <BR>【種別】 入れ替わり<BR>【キーワード】 ロックバンド ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld3-4.html">デュアルワールド第三楽章　『フルメタルワイルド再起動！』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp ">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/7/26(日)</TD><TD>28KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>愚かな人々とのせいで繰り返される悲しみ。戦争の上に成り立つ平和。その真実なんて捻じ曲げてやる！　反社会を掲げた少女は、仲間とともにゲリラライブの舞台へと臨む。……その前にちょっと、ひと騒動♪<BR><B>【コメント】 </B>でも、だいっきらいなものが１つだけ。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200702/18234405/dislikes.html">きらいなもの→＊<a href="../novel/200802/15232641/sundaes.html">／スイーツ魔法少女シュガー☆サンデー</a></A> <FONT SIZE="-1">(おもちばこさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>最後の戦い……いや、「戦い」に行くんじゃない。だってジェーンたち三人は——<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 "きらいなもの→注射"</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld3-3.html">デュアルワールド第三楽章　『大好きです』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/7/19(日)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ブルーティアに帰ってきたジェーン。だが、彼女は残酷な真実と向き合うことができるのだろうか。そして、ジョニーを想い続けたモニカは。<BR><B>【コメント】 </B>↓城弾さんの『アンテナショップ』はすべて拝読させていただきました。感想つけずにすみません。僕は、城弾さんの作品の中でこれが一番好きです。今更かつ場違いですが、この場を借りてコメントさせていただきます。「最高だぜ！」<BR>
  ジェーン：デュアルに関するコメントってナイナイなんですか？<BR>
  バレット：オニメンゴ。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200803/01214225/antena01a.htm">アンテナショップ前編<a href="../novel/200803/01214225/antena02.htm">／中編</a><a href="../novel/200803/01214225/antena03.htm">／後編</a></A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>壮絶なバトルの果てに訪れた再会。そして彼女たちの選択は……<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 幻想 ファンタジー 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 "………………百合？"</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld3-2.html">デュアルワールド第３楽章　『ストラグル』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp ">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/7/14(火)</TD><TD>56KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに始まった、ジェーンたちと四大天使の衝突。試されるのは、戦いの力だけじゃない。<BR><B>【コメント】 </B>次です、次！　待ってください！（何を）<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200703/23200707/sary_index.html">救世主サリーエンジェル</A> <FONT SIZE="-1">(ＮＡＴＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>圧倒的な筆力で紡がれる戦い。勝利した者たちも深く傷つき、別れ……そして意外な展開。<BR>
　デュアルワールド、佳境へ。<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】  ボクっ娘 フルメタルワイルドの歌のフレーズ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld3-1.html">デュアルワールド第三楽章　『未来色の夢』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/6/22(月)</TD><TD>58KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いよいよフルークツォイクに乗り込み、空に浮かぶ国ヴァイスガルテンを目指すジェーンたち。そして、普段から世話になっている人に自分たちの覚悟を示すレイヴンとモニカ。２つの世界ではそれぞれが、大きく動き出そうとしている。<BR><B>【コメント】 </B>本編に萌えがないとサンダバ・ラジオに逃げ込むという僕の困ったクセが全開。そしてとうとう……！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200607/02124625/yaoma_top.html">ヤオヨロヅ物語</A> <FONT SIZE="-1">(天爛さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>空へのツバサを手に入れ、いざ空中都市を目指す勇者一行。いよいよ世界が、動きます。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘 フルメタルワイルドの歌のフレーズ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200901/30231222/uta4.htm">くろす・あこーど　episode 4</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/6/4(木)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_utanotsuki.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>唐突に開催されることとなったロードレース。盛り上がって全校１位を目指す覇雄に対し、途中でリタイアを考える稔、そんな２人を心配する和音。さてさて、３人はリタイアすることなく、４キロという道のりを走りきることができるのか！　覇雄ちゃん、まずは完走することを考えようね？<BR><B>【コメント】 </B>実は、僕の母校でやっていたイベントがモデルだったりします。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200901/30231222/uta_title.htm">くろす・あこーど</A> <FONT SIZE="-1">(リレー小説「くろす・あこーど」制作協議会さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>こういったイベントの最後に出てくる〇〇って、めっさウマいんだよね〜ってなお話？<BR>
　リレー小説「くろす・あこーど」第４話。乗り遅れるなっ！<BR>
<b><a href="../novel/200901/30231222/uta_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 原因不明 変身<BR>【キーワード】 オレっ娘 ボクっ娘 ロードレース 理解ある女友達 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld_ex4.html">デュアルワールドＡＧ　『鴉の翼と一輪の花』 </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/11/24(月)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>レイヴンが新たに結成したバンド『ディテクティヴ』。それはひと癖もふた癖もあるまとまりのないバンドだった。そんな彼らはそれぞれの目的のために、秋葉原へとやってきたのだが。……早速金欠の危機！？<BR><B>【コメント】 </B>フルメタルワイルド時代のまとまりのよさはどこへやら。枷が外れたハードロッカーと、ジョニー（＝ジェーン）以上のオタク少女と、本の虫にして無気力リーダーの３人による、自己中心的な大騒動を、ぜひ楽しんでいただければと思います！　<font color="#666666">……次は渋谷の話を書きたい。</font><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回のお話は、いつもと趣向を変えて、ほんのちょっとだけ甘酸っぱいです。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション コメディ <BR>【種別】 薬品 変身<BR>【キーワード】  オレっ娘 メイド ウマウマ 強制 入浴（それっぽくないけど）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld_ex3.html">デュアルワールドＡＧ　『修羅場・ラ・バンバ 』</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/11/1(土)</TD><TD>54KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>日本からやってきた、少年稲葉龍一。彼の夢は、やがて脱退するレイヴンの穴埋めとして、フルメタルワイルドのメンバーとして活躍することだった。しかし、食品混入物事件の影が彼らにそっと這い寄るのだった。そのほか、世界各地で大騒ぎ。<BR><B>【コメント】 </B>萌えて笑っていただければいいのですが。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200308/23164956/multi.htm">マルチエンディングストーリー</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>世界全国津々浦々（異世界も含めて）、古今東西南北左右、今日も今日とてみんな<b>無駄に</b>賑やかなのです。<s>ちょっと落ち着いたらどうだい？</s><BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート ファンタジー 幻想 コメディ <BR>【種別】 薬品 変身 仮性半陰陽<BR>【キーワード】 鏡 コスプレ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-b.html">デュアルワールド第二楽章『フルークツォイク机上から空へ』</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/10/9(木)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>最後の四大天使イスラフェルとの接触と、ポルックスの研究の最先端との出会いによって導き出される希望の光。道はいよいよ、拓けるか。<BR><B>【コメント】 </B>役者は、すべてそろいました。第３楽章以降も、応援よろしくお願いします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ぇええええええ！？　ちょ、おま、イスラフェルちゃん、それはないー！<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b><BR>
</TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】  魔法 変身 バイオテクノロジー（？）<BR>【キーワード】 サッカーとキツネと重火器（？）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-a.html">デュアルワールド第二楽章『虹色の翼』</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/9/23(火)</TD><TD>62KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ドリームレジデンスへとやってきたジェーンたちは、そこでフリューゲルの過去を知る人物と出会う。だがその時、空の上では……　今、フリューゲルの勇気が試される！<BR><B>【コメント】 </B>２０世紀の悪夢が繰り返されようとしていますが、フリューゲル、クリシュナ、そしてあのコが、そんなことはさせません！<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>彼女たちの行く先に平穏はないのか。感傷に浸ってはいられません。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 入浴</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-9.html">デュアルワールド第二楽章　『衝突』</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/9/4(木)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>四大天使最強を誇るゼルエル。その難関に、英雄は立ち向かう！　そしてサンダバ・ラジオには、とうとうあの子が登場します。っつーか、インディーの毒舌はどうにかならないのか。<BR><B>【コメント】 </B>ジェーン、何気にショッキング〜。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200803/01214225/antena01a.htm">アンテナショップ</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ピザまん？　いいえ違います。それはもっとふかふかであったかくて夢の詰まった……<font size=-1>……</font><font size=-2>あんまり力説してると白い目で見られそうなので自主規制。</font><BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b><BR>
</TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ピザまん（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-8.html">デュアルワールド第二楽章　『逃げろ！』</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/8/22(金)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>クリシュナを新たなる仲間に向かえ、次の管理局にやってきたジークフリードパーティ。難なく２つ目のエメラルド・タブレットを獲得できたまではいいが、その直後に悪夢が遅い来る！　どうやって切り抜ける！？<BR>
そして、ジョージによって大破したサンダバ・ラジオ局も復活。インディーの容赦ない毒舌が、炸裂するーっ！<BR><B>【コメント】 </B>お久しぶりです。テラ緊張気味です。デュアルワールド再開をきっかけに、『新しいデュアルワールド』として皆さんに認知していただけるようがんばりたいと思います。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200803/09200702/yuuki0.html">Ｙｕｕｋｉ</A> <FONT SIZE="-1">(Ｚｏｃｋさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>用意周到に準備したつもりでも、なかなか楽はできません。どころか危機だらけっ<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b><BR>
</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld_ex2.html">デュアルワールドＡＧ　旅の途中</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/4/19(土)</TD><TD>56KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>クリシュナによるゲヒルン襲撃は終わり、ジェーンたちの旅は再開する。これは、そこから少し未来と、それまでにいたるまでの語られざる物語だ。<BR><B>【コメント】 </B>騒動に巻き込まれるジェーン＆ロロ、ツンデレるヘレン、はしゃぐフリューゲル、不可抗力にさいなまれるジークフリード、少女の一面を見せるクリシュナ、弄られるレイヴン、キレるモニカ、のんきなフェブルアール＆プーリー、ラジオ局崩壊に頭を抱えるインディー＆ひとみ。みんなそろって何やってんだよ……<BR><B>【バレット さんのオススメ作品】</B> </a><a href="../novel/200302/10213812/baka.htm">馬鹿たちの挽歌</a>＆<a href="../novel/200305/21170557/ldrive.htm">ランボルギーニ・ドライブ</a><a> <FONT SIZE="-1">(丑寅さん作)アイテムが共通しているのです。</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>冒険の、合間合間の物語。約８本（ちゃんと数えろ）。のんびりくつろいでお楽しみください。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート ファンタジー 幻想 コメディ <BR>【種別】 薬品 変身<BR>【キーワード】 オレっ娘 着せ替え 年齢変化 ボクっ娘 鏡（キャンプ） 入浴 強制 水着</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-6.html">デュアルワールド第二楽章　満月の大捕り物</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/3/22(土)</TD><TD>48KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いよいよ始まる、怪盗・満月の夜＝クリシュナの大捕り物大作戦。だが彼女の前にはジェーン、ラング、そして新たなる刺客が立ちふさがる。この危機、どう乗り切る！？ <BR><B>【コメント】 </B>今回も２話連続仕立てです。またしてもジェーンは爆弾発言を！？<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/fullmoon.html">ＦＵＬＬ　ＭＯＯＮ　ＮＩＧＨＴ</A> <FONT SIZE="-1">(ＢＡＣＫＢＯＮＥさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><s>ついでに作者も爆弾発言を！？</s>とうとうやってきました満月。自警団長と怪盗、英雄と為政者、勇者と魔族（だよな……）、彼らの思惑が交わる。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 幻想 ファンタジー 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-5.html">デュアルワールド第二楽章　怪盗クリシュナ</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/3/11(火)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ミミルまでやってまいりましたジェーンたち。しかし、そこでは今大事件が発生していた？　闇夜に潜む脅威の正体とは。<BR><B>【コメント】 </B>萌えも燃えもない、ガーゴイルの登場もない、当然バトルシーンもない。見所なのはやっぱり、あんなことになっちゃってるヘレンがゲストとして登場する、サンダバ・ラジオ？　「新宿〜渋谷」って……<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan84.html">華代ちゃんシリーズ「落ちこぼれ」</A> <FONT SIZE="-1">(逆流人さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>次なる街ミミルに着いた一行。静かにドラマが展開する、その一方でブルーティアでも……ところで、音響魔法って、どんな魔法なんだろう？<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-4.html">デュアルワールド第二楽章　怒号するレイヴン</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/2/25(月)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>モニカの様子がおかしい？　そんな彼女が気がかりなレイヴン。そしてジークフリードは、過去の思い出をジェーンたちに語りだす。２つの世界の物語は、いよいよシンクロし始めた。<BR><B>【コメント】 </B>今回の見せ場は、サンダバ・ラジオです（爆）。皆さん、５２枚のカードをお手元に置いて、読み進めてください。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200209/19204751/d_upboy_title.htm">着せ替え少年〜Ｄｒｅｓｓ　Ｕｐ　Ｂｏｙ〜</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>異界に渡ったジョニー（ジェーン）の力になろうと必死のモニカですが、モヤモヤしてるのがもう一人……<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 幻想 ファンタジー 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-2.html">デュアルワールド第二楽章　緋色の騎士</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/2/2(土)</TD><TD>57KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>エメラルド・タブレットを入手すべく、一同は遺失技術管理局へ。そこに待っていたのは、お宝だけではなかった！？<BR><B>【コメント】 </B>全然ＴＳキャラが出てこないので、作者たる僕自身が業を煮やして２話連続スペシャルです！<BR>
（編注：今回は『<a href='../novel/200712/22231343/dualworld2-2.html'>エメラルド・タブレット</a>』『<a href='../novel/200712/22231343/dualworld2-2.html#half'>それでも俺の牙は折れない！</a>』の二本立てです）<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200303/17233027/brother.htm">愚痴</A> <FONT SIZE="-1">(DEKOI＆Dattaさん作)こういう実録集もとても楽しいと思います</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今日のTSはかっこいいです、ダークヒーロー（ヒロイン？）です。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 オレっ娘 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld2-1.html">デュアルワールド第二楽章　モニカの覚悟</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/1/21(月)</TD><TD>26KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イマジネシアとブルーティア、それぞれで何が起ころうとしているのだろう。そして、自ら戦地へ足を踏み出す覚悟を決めたモニカは、とある英雄の形見を手にする。<BR><B>【コメント】 </B>暴走するフリューゲルに恐怖するジェーンとロロ。錬金術師と先輩小説家、ただいま見参。そして１７年前の英雄の１人も復活。ここから、物語は大きく動き出す。……ハズ。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前回、大胆な告白をしたモニカですが、彼女はその後どうなったかと言うと……<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ファンタジー 幻想 戦記 <BR>【種別】 変身<BR>【キーワード】 ショッピング 着せ替え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld_ex1.html">デュアルワールドＡＧ　サンダバ・ラジオＳｐｅｃｉａｌ</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2008/1/6(日)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>本編第一楽章に登場した、湖上都市フルート。今回は、サンダーバードの２人が、その魅力に迫ります。本編よりも魅力的なフルートを、是非満喫していってください。……ちょっと待て、インディーくん食い意地張りすぎだ！<BR><B>【コメント】 </B>これ作るの夢でした！　もしよろしければ、おまけまで楽しんでいってください。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200209/19204751/kumi01.htm">美少女組長奮戦記</A> <FONT SIZE="-1">(城弾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>デュアルワールドの番外編と銘打って、サンダバ・ラジオのお正月スペシャル（？）です。<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 （戦記はおあずけ？） ファンタジー 幻想 <BR>【種別】 毒？ 変身<BR>【キーワード】 オレっ娘 サンダバ・ラジオ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld1-6.html">デュアルワールド第一楽章　砦の決戦</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/12/30(日)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>衝突するタブリスとジェーン。そして物語は、エメラルド・タブレット集めへ。デュアルワールドの本当のスタートは、ここからだ！<BR><B>【コメント】 </B>ビートリックスとフリューゲル、本当だったらこんなに影の薄い存在じゃなかったんだけど、ジェーンがお騒がせ過ぎなのでしょうか。とっ、とにかくっ！　今日は温泉でゆっくりくつろごう！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/extra/kayo_ex53.html">ジゴラがやってきた</A> <FONT SIZE="-1">(流離太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ジェーンvsタブリス。決戦の行方はっ<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 変身<BR>【キーワード】  ボクっ娘 入浴</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld1-5.html">デュアルワールド第一楽章　微風×自由×聖戦</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/12/22(土)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>旅の文学少女ロロ・ルフトハウホ、闇の天使タブリス・フライハイトの出現。オススメなのは学問よりも、相手と己をまずは知ること。そしてジェーン・デツェンバーは、両手に再び銃を取る！<BR><B>【コメント】 </B>もしデュアルワールドを読み飽きましたら、絶対にこの『デュアルワールド＃５　サンダバ・ラジオ』を開いてください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>世の中には、かつての英雄は弱くなるという法則があるみたいですが、それにしたってジークさんあんた……<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld1-4.html">デュアルワールド第一楽章　湖上都市フルート</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/12/9(日)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>目的地に向かう前に立ち寄った、湖上都市フルート。みんなそろって完全に遠足気分。そこでジェーンは、運命的な出会いを果たす。<BR><B>【コメント】 </B>あのコの本、出たら絶対に読みたい！　デュアルファンじゃない人も、イマジネシアに行く機会がありましたらフルートの本屋に立ち寄ってみてください。<BR><B>【バレット さんのオススメ作品】</B> </a>ヒーローのいる世界で<a href="../novel/200609/08003735/wwh0.html">プロローグ</a>・<a href="../novel/200609/08003735/wwh1.html">第一話</a>・<a href="../novel/200609/08003735/wwh2.html">第二話前編</a> <FONT SIZE="-1">(クロガネさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>初めて踏み入る街で、平和なひととき……と思いきやっ<BR>
あそうそう、今回から、アノ作品のアノ娘をモデルにした、新たな仲間？が登場します。<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 微妙なあのコ ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld1-3.html">デュアルワールド第一楽章　神々の大陸</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/11/24(土)</TD><TD>21KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新しい出会いと、これからの不安。いろんなことがありすぎたけど、本当にいろいろなことが待っているのはこれからだ。<BR><B>【コメント】 </B>バトルなしです、あしからずご了承ください。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200306/09214854/rena_01.htm">レナリム</A> <FONT SIZE="-1">(ＢＡＦさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自分の引き受けたものの重責を今更ながらに知る、ジョニー改めジェーン。しかし、挫けはしない。彼女には仲間がいて、勝利を信じて祈る者がいて、帰りを信じて待つ者がいるのだから。<BR>
<b><a href="../novel/200712/22231343/dw_index.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】  ボクっ娘 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200712/22231343/dualworld1-1.html">デュアルワールド第一楽章　運命の歯車は回りだす（前編＆後編）</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/11/10(土)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>バトルにロックにグルメにファンタジー、何でもかんでもチャンプルー！　その手に２つの銃を持って、２つの未来に希望の種を撒くべく立ち上がった、ジョニー・デツェンバーの物語が、幕を開けます。<BR><B>【コメント】 </B>今回だけ、２話連続です。また変なことを始めちゃいましたが、長い目で見守ってくださいませ。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200306/14163618/doki_01.htm">どきどき！　メガネっ娘くん</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>きっと帰ってくると誓って、少年（？）は死地へと旅立ちます。さぁ冒険のはじまりはじまり〜<BR>
<b><a href='../novel/200712/22231343/dw_index.html'>【タイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  ファンタジー 幻想 戦記 <BR>【種別】 魔法 変身<BR>【キーワード】 イマジネシア＆ブルーティア（アナログ所さんマスケッティアーズ） ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/kayo_chan109.html">華代ちゃんシリーズ「華代ちゃん　酷い目にあう」</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/10/11(木)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_kayo_chan.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イタズラ好きの少年・亞久真と、パン屋志望の大学生が、ひょんなことから華代ちゃんと出合うことになる。４人の少年少女たちが交差する、ポップな展開と豆知識が豊富な、おバカ全開物語！　……ちなみに、華代ちゃんの今日のパンツは、くまさんプリントです（萌）。<BR><B>【コメント】 </B>皆さんにもありませんか、やめられない趣味と、叶えたい夢が。そして、大切な人が。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200702/18234405/dislikes.html">きらいなものシリーズ</A> <FONT SIZE="-1">(おもちばこさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>華代ちゃんの〇〇シーンって、初めて見た……（笑）<BR>
<b><a href="../novel/kayo_chan/index.html">【華代ちゃんシリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 青春 <BR>【種別】 アイテム（オレンジジュース） 変身<BR>【キーワード】 ♀→♂ 親友萌え ボクっ娘 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_hop02.html">アナログ所さん最終回　超危機的ハプニングオンパレード（後編） </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/9/17(月)</TD><TD>61KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新しく携帯電話を買ったインディー。それ一台で、友達との想いは通じるのであるッ！　他、合計５本＋おまけ２本収録。<BR><B>【コメント】 </B>今までご声援、ありがとうございました。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200101/14013415/title.html">らいか大作戦</A> <FONT SIZE="-1">(かわねぎさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>出会いがあれば別れもまた。『アナログ所さん』堂々のグランドフィナーレ！！　……でもいつもとおんなじノリだと思うのは、担当だけ？（＾＾；<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 ショートショート SF コメディ <BR>【種別】 変身<BR>【キーワード】 電話 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_hop_ex.html">アナログ所さん最終回　超危機的ハプニングオンパレード（特別編） </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/9/2(日)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>民間機構ケンプファーは、悪の組織ヴァイオレイターズからの世界侵略を阻止すべく動き出す！　他、合計２本収録。<BR><B>【コメント】 </B>あのセーレが復活！　マスケッティアーズ後編では消えたバカッ振りが大炸裂します。コイツ、本当に『健全な男児』なのか……？<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200606/01233508/darklord0.html">漆黒の魔王第０話<a href="../novel/200606/01233508/darklord1.html">／第１話</a><a href="../novel/200606/01233508/darklord2.htm">／第２話</a><a href="../novel/200606/01233508/darklord3.htm">／第３話</a><a href="../novel/200606/01233508/darklord4.htm">／第４話</A> <FONT SIZE="-1">(バンテツさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>特別編はアナトコメンバー出演の特撮ドラマ？と、鋼＆美時が繰り広げるウェスタンドタバタ劇？です。ご賞味あれ。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート 二次創作 近未来 コメディ <BR>【種別】 薬品？ 変身<BR>【キーワード】 特撮ヒーロー 西部劇 着せ替え ジンギスカンヤキソバ アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_hop01.html">アナログ所さん最終回　超危機的ハプニングオンパレード（前編） </a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/8/14(火)</TD><TD>42KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第２掲示板に載せた『アナログ所さん　狂言クロスオーバー』が、ある意味パワーアップして帰ってまいりました。インディーくんとひとみが新たに考え出した言い訳とは？　他、合計５本収録。<BR><B>【コメント】 </B>いろんな意味でぶっ壊れています。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/free/free.html">ワンスモア　フリースロー</A> <FONT SIZE="-1">(ことぶきひかるさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前編は毎度おなじみアナトコメンバーの非日常的（？）日常。……ところでキャラ紹介のところに、どこかで見た（読んだ）ような方々がちらほらと——<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 ショートショート SF コメディ <BR>【種別】 アイテム 変身<BR>【キーワード】 狂言『附子』 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_m02.htm">アナログ所さん the Chronicle of Musketeers（後編）</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2007/6/3(日)</TD><TD>115KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>インディーのもとに集まるマスケッティアーズ。セーレの強大な力の前に、銃士たちは絆の強さを力に変えて立ち向かう。北海道の雪祭り、いや世界の運命は、インディーたちの手に託された！　……他、おまけストーリーとテーマソングも収録しています。最後の最後まで、是非お楽しみください！<BR><B>【コメント】 </B>自転車引きずって、次の町まで歩いてゆこうか。またいつか、インディーくんと会える日まで……　そんなお話になっています！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200401/04203552/angel_title.html">Ａｎｇｅｌ </A> <FONT SIZE="-1">(驟雨さんさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>マスケッティアーズ後編は、世界の命運を賭けたバトル＆バトル！　そしてインディーくんはひとつの決意をする……<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a><a href="../novel/200512/06000905/anatoko_m00.htm">【登場人物紹介はこちら】</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 アクション コメディ レーシング （異世界？） テーマソング <BR>【種別】 トラップ（！？） 変身<BR>【キーワード】 アイテム 魔法少女 オレっ娘 親友萌え ボクっ娘 入浴 コスプレ アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_m02.htm">アナログ所さん the Chronicle of Musketeers（後編）</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2007/6/3(日)</TD><TD>115KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>インディーのもとに集まるマスケッティアーズ。セーレの強大な力の前に、銃士たちは絆の強さを力に変えて立ち向かう。北海道の雪祭り、いや世界の運命は、インディーたちの手に託された！　……他、おまけストーリーとテーマソングも収録しています。最後の最後まで、是非お楽しみください！<BR><B>【コメント】 </B>自転車引きずって、次の町まで歩いてゆこうか。またいつか、インディーくんと会える日まで……　そんなお話になっています！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200401/04203552/angel_title.html">Ａｎｇｅｌ </A> <FONT SIZE="-1">(驟雨さんさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>マスケッティアーズ後編は、世界の命運を賭けたバトル＆バトル！　そしてインディーくんはひとつの決意をする……<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a><a href="../novel/200512/06000905/anatoko_m00.htm">【登場人物紹介はこちら】</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 アクション コメディ レーシング （異世界？） テーマソング <BR>【種別】 トラップ（！？） 変身<BR>【キーワード】 アイテム 魔法少女 オレっ娘 親友萌え ボクっ娘 入浴 コスプレ アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_m01.htm">アナログ所さん the Chronicle of Musketeers（前編）</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/5/25(金)</TD><TD>81KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>グルメ旅行と映画撮影のために、北海道札幌市にやってきたインディーたち。しかし、そのお祭りムード一色の町を、異世界からやってきた侵略者に脅かされることに。果たして、インディーたちは魔の手から、世界を救うことができるのか！？<BR><B>【コメント】 </B>アナログファミリー大集合！　北海道の味覚も、ちょっぴり紹介。美味しさを文章で現すって、難しいです……<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200702/27234954/yorishiro_01.htm">よりしろトランス</A> <FONT SIZE="-1">(乾さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いつもお気楽なインディーくんとその愉快な仲間たち（笑）が、今度は現実世界の命運をかけて大活躍……するのか？　まずは前編を堪能しよう。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a><a href="../novel/200512/06000905/anatoko_m00.htm">【登場人物紹介はこちら】</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 アクション コメディ （異世界？） <BR>【種別】 薬品（錠剤）<BR>【キーワード】 魔法少女 アイテム オレっ娘 親友萌え ボクっ娘 入浴 コスプレ アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_c04.htm">アナログ所さん電脳大冒険 Special Extra Episodes</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2007/5/6(日)</TD><TD>98KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>もとの世界の戻ってきた、電脳大冒険参加者。あれからみんなどうしているのか、少しだけ覘いてみることにしよう。新たなるキャラクターも追加されているぞ！　……って、あの人が？<BR><B>【コメント】 </B>自分でザバイオーネを作ってみたのですが、ちょっとしょっぱかった気がします。ザバイオーネは少量の材料でできますので、是非作ってみてくださいね♪（そして、すっかり遅くなりまして、すみません！）<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200308/20191205/sleep.htm">お隣さん宅の小悪魔</A> <FONT SIZE="-1">(ｆｕｎ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>長い容量ですが、その分いろんなものが「てんこ盛り」に詰まっております（笑）。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 アクション ファンタジー コメディ <BR>【種別】 仮想現実 アバター（自作キャラクター）<BR>【キーワード】 アニメ『デジタル所さん』他 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_c04.htm">アナログ所さん電脳大冒険 Special Extra Episodes</a></B></TD><TD><B><A href="mailto:alleydog_bowwow@yahoo.co.jp">バレット</a></B> さん </TD><TD><B>画</B>(<B>バレット</B>さん)</TD><TD>2007/5/6(日)</TD><TD>98KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>もとの世界の戻ってきた、電脳大冒険参加者。あれからみんなどうしているのか、少しだけ覘いてみることにしよう。新たなるキャラクターも追加されているぞ！　……って、あの人が？<BR><B>【コメント】 </B>自分でザバイオーネを作ってみたのですが、ちょっとしょっぱかった気がします。ザバイオーネは少量の材料でできますので、是非作ってみてくださいね♪（そして、すっかり遅くなりまして、すみません！）<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200308/20191205/sleep.htm">お隣さん宅の小悪魔</A> <FONT SIZE="-1">(ｆｕｎ９さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>長い容量ですが、その分いろんなものが「てんこ盛り」に詰まっております（笑）。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 アクション ファンタジー コメディ <BR>【種別】 仮想現実 アバター（自作キャラクター）<BR>【キーワード】 アニメ『デジタル所さん』他 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/cometline.htm">Ｋｉｃｋ！　〜彗星の軌道（コメットライン）〜</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/9/20(水)</TD><TD>72KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「陽介、見てる？　わたしは、絶対に夢、つかむから」<BR>
　……ずぼらを極めた少女・柊木美時は、サッカーを通じて大きな夢を抱く。<BR><B>【コメント】 </B>４年後の日本代表を応援します！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200207/03224430/roromi_title.html">微妙存在ろろみ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ものぐさ少女に訪れた、奇跡の出会いと運命の転機。ＴＳもの（異性変身奇譚）というよりは、ハートフルな精神同居物です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 スポーツ 現代 学園 <BR>【種別】 精神同居<BR>【キーワード】 入浴</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_a.htm">アナログ所さん　留守番天使</a></B></TD><TD><B><A href="mailto:k_saiyuuki@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/25(金)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>旅人・悠里は、とある事故に巻き込まれて所さん家にお世話になることになった。日常の中に点在する非日常が、インディーを襲う。<BR><B>【コメント】 </B>大事件です！　僕はショートショートの書き方を忘れてしまいました！（無関係）　いや、それは置いといて、ボケとツッコミの要素が通用しない新キャラクター・悠里の（非）日常冒険を、お楽しみに。変なところでかなり萌えます（？）。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200511/06220214/shinyu.html">親友</A> <FONT SIZE="-1">(セルさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>新キャラクター、聖悠里クン登場！　……え？　ジュディは？（笑）<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 コメディ？ ＳＦ <BR>【種別】 事故 テクノロジー 変身<BR>【キーワード】 女性人格化 アニメ『デジタル所さん』ボクっ娘 入浴</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_c03.htm">アナログ所さん　電脳大冒険Ｓｐｅｃｉａｌ（後編）</a></B></TD><TD><B><A href="mailto:k_saiyuuki@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/18(金)</TD><TD>53KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いよいよ魔王の城にたどり着いたインディーたち。戦いの行方は？　そして、旋がこのゲームの先に導き出した答えとは？<BR><B>【コメント】 </B>いよいよ登場です、最後の人材！　今回の話で、バーチャルゲームのお話は幕を閉じます。出演者のみんな、ありがとう！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200512/22203201/zhvts_top.html">ＺｗｅｉｈａｎｄｅｒＶＴＳ</A> <FONT SIZE="-1">(華村天希さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>たかがゲーム、されどゲーム。忘れがちになるのですが、今、貴方の見ているこの画面の「向こう側」にも、大勢の人たちがいるのですよ。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 二次創作 ファンタジー コメディ？ <BR>【種別】 仮想現実 アバター（自作キャラクター）<BR>【キーワード】 アニメ『デジタル所さん』『若葉色の怪盗』『落雷』『ホーリーメイデンズ』『ＺｗｅｉｈａｎｄｅｒＶＴＳ』 ハンター３０号</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_c02.htm">アナログ所さん　電脳大冒険Ｓｐｅｃｉａｌ（中編）</a></B></TD><TD><B><A href="mailto:k_saiyuuki@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/12(土)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>光の羅針盤（ラバン）を完成させ、いよいよ海を渡ろうと意気込む３パーティーたち。しかし、旋だけは違った。そして、旋とほかのメンバーの間に亀裂が……？<BR><B>【コメント】 </B>完全にギャグが消えました。でもアクションはてんこ盛りにしたつもりです。８人全員が活躍する、海の上での大激戦をお楽しみに！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200604/22210708/m_title.htm">めいぷる！─ザ・インセクト─</A> <FONT SIZE="-1">(Ｋ．伊藤さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>大海戦！　でも、そのやり方はちょっとずるくないか……？<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 二次創作 ファンタジー コメディ？ <BR>【種別】 仮想現実 アバター（自作キャラクター）<BR>【キーワード】 アニメ『デジタル所さん』『若葉色の怪盗』『落雷』『ホーリーメイデンズ』 ハンター３０号</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_c01.htm">アナログ所さん　電脳大冒険Ｓｐｅｃｉａｌ（前編）</a></B></TD><TD><B><A href="mailto:k_saiyuuki@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/4(金)</TD><TD>77KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>バーチャルリアリティを駆使したゲーム『ダーク・キングダム』がスタートする。４パーティー、計１１人の冒険が、今始まる！　……でも、こんな足取りで大丈夫なんだか。<BR><B>【コメント】 </B>作品作りに当たって、きりか進之助さん、流離太さん、天爛さん、そしてずっと先に出したいキャラを作った某監査さん、人材を派遣してくださってありがとうございます！　うまく作れたかどうかが心配で、冷や汗かいております。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/extra/kayo_ex44.htm">ハンターシリーズ「未来への手紙」</A> <FONT SIZE="-1">(天爛さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>バーチャルオンラインゲームのテストプレイに挑む、インディーくんと愉快な仲間たち（笑）。……え？　君たちが主役じゃないの？<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作  アクション コメディ？ ファンタジー <BR>【種別】 仮想現実 アバター（自作キャラクター）<BR>【キーワード】 『落雷』 『若葉色の怪盗』『ホーリーメイデンズ』 アニメ『デジタル所さん』 ハンター３０号</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_w.htm">アナログ所さん　戦争茶会</a></B></TD><TD><B><A href="mailto:k_saiyuuki@yahoo.co.jp">バレット</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/7/7(金)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『拾ってください』　そう書いてあるダンボールの中に取り残されていたシベリアンハスキーをジョージが拾って、１５年が経った。今日は、彼女の誕生日。<BR><B>【コメント】 </B>ちょっと心の温まるギャグの連発を、どうぞ！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200604/21135117/holy_title.html">ホーリーメイデンズ</A> <FONT SIZE="-1">(流離太さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>電波ネコ、愛と青春の旅立ち（違）。……どうしても「あの」声で読んでしまいます、こいつのセリフ（笑）。<BR>
<b><a href="../novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 コメディ？ ＳＦ <BR>【種別】 女装……なのか？<BR>【キーワード】 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_m.htm">アナログ所さん　ＴＨＥ　ＭＯＶＩＥ（嘘）</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/30(金)</TD><TD>25KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>お笑いコンビ”サンダーバード”は、人気アイドル”ハリケーン”とドラマの共演をすることになった。しかし、ロケの翌日、ひとみの様子がおかしなことに。どうする、ジュディ＆インディー！？<BR><B>【コメント】 </B>ギャグ控えめです。今回はひとみにのみ焦点が向けられています。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="novel/200603/06014840/kimidori_title.html">キミドリ</A> <FONT SIZE="-1">(ユタさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「アナトコ」も三作目。今回はちょっと趣向が違います。<BR>
<b><a href="novel/200512/06000905/ana_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 コメディ？ ＳＦ <BR>【種別】 <BR>【キーワード】 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/kayo_chan106.htm">華代ちゃんシリーズ『Ｓｉｌｖｅｒ』</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/23(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_kayo_chan.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>廃屋に住まう青年は、雨ざらしになって倒れている少女を助けた。その子こそ、旅するセールスレディー・真城華代だった。<BR><B>【コメント】 </B>華代ちゃん公式作品・初挑戦です！　原作者・真城悠さんには、恐れ多くてビクビクガタガタ（震）。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200605/05101055/nijiiro_title01.htm">虹色のトレイル</A> <FONT SIZE="-1">(きりか進之介さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>銀の弾丸は人獣を葬り去る唯一の武器。バレットさんの「華代ちゃん」は、やはり硝煙の匂いがします。<BR>
<b><a href="../novel/kayo_chan/title06.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 アクション <BR>【種別】 変身（転生？）<BR>【キーワード】 オレっ娘（一部） 年齢変化 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko_f.htm">アナログ所さん　Ｅｐｉｓｏｄｅ　ｃｏｄｅ：Ｆ（Ｆｕｎｋｙ）</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/24(水)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>若返りマシーンの心臓部をスパークたけしに壊されたジュディは、マシーンを修復する。修復が一段落してビスケットを食べようとしたら……<BR><B>【コメント】 </B>やや無理して作ったってことが見え隠れする作品です（から残念！）。それと、この文庫内で大人気のあの『三図川』が登場します。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200502/01114354/he_is_mother_01.html">Ｈｅ　ｉｓ　ｍｏｔｈｅｒ！</A> <FONT SIZE="-1">(神姫・緋威羅さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ＴＳっ娘の背負った“業”のひとつに、「まわりからオモチャにされる」というのがあります（笑）。<BR>
<b><a href="../novel/200512/06000905/anatoko.htm">【アナログ所さんはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 ショートショート コメディ？ SF <BR>【種別】 冥界の川 テクノロジー 変身<BR>【キーワード】 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/seed.htm">Ｓｅｅｄ　−　たった一つの種</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/20(土)</TD><TD>61KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>科学者・薬師丸緑茶は、大の植物好き。彼の研究が完成したその日、彼は目の前で少年が乗用車に跳ね飛ばされたのを目撃した。<BR><B>【コメント】 </B>今回もパクれるものは散々パクっています。この作品の数々、皆さんはご存知でしょうか。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200508/27023833/al_title.htm">あるけみすと☆さーが　〜ティルミットの冒険記〜</A> <FONT SIZE="-1">(マコトさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「緑の親指」を手に入れた少年改め少女の冒険記。個人的には「お坊っちゃま」から「お嬢様」と言いなおされて照れる（？）あたりが萌え（笑）。<BR>
（運営委員の不手際で、掲載が大幅に遅れたことをお詫びします）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション SF <BR>【種別】 テクノロジー 変身<BR>【キーワード】 オレっ娘 オマージュ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/gekisen.html">激戦</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/3/26(日)</TD><TD>88KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>悟空とキノは、双子の姉弟。彼らの日課は、格闘技の訓練と早朝ランニング。ある朝、交差点で彼らが目撃したものは、ふらふらと走るタンク車だった。<BR><B>【コメント】 </B>お久しぶりのバレットです。間が空いてすみません。作品制作に当たって、パクれるものはパクってます。知ってる人はきっと知ってる！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="novel/200202/03004409/heart01.html">ハートのペンダント１</a>＆<a href="novel/200202/03004409/heart02.html">２</a> <font size="-1">(Ｍａｒｉｅさん作)</font> <a href="novel/200112/19020205/l_title.htm">超装甲機動兵器ライトニング</a> <font size="-1">(ライターマンさん作)</font> <a href="novel/200503/27150319/machina00.html">エクス・マキナ</A> <FONT SIZE="-1">(鈴忌紫さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「落雷」のヒロインの子供たちが大活躍します。おまけも付いてお得感バッチリ！<BR>
<a href="../novel/200512/06000905/lightning.html"><strong>【「落雷」はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション SF <BR>【種別】 薬品（？）<BR>【キーワード】 いろんな作品からのパクリあり 親友萌え 理解ある姉妹 シェアキャラクターがこそっと…</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/anatoko.htm">アナログ所さん</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2006/3/12(日)</TD><TD>20KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>有名なミュージシャンにしてマッドサイエンティストの所常時＝ジョージは、『若返りマシーン』を発明し、大学教授にしてジョージの助手の印梯＝インディーをその実験台にしてしまう。<BR><B>【コメント】 </B>皆さんは、『デジタル所さん』ご存知ですか？　さあ、大騒動は近所さえ取り巻いてしまうぞ！　ショートコント風のあとがきににもご注目！<BR><B>【バレット さんのオススメ作品】</B> <A HREF="../novel/200409/16020158/princess_01.html">Ｐｒｉｎｃｅｓｓ前編／<a href="../novel/200409/16020158/princess_02.html">後編</a></A> <FONT SIZE="-1">(ミスター長崎さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ポップな感覚が楽しいショートショートの連作です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 ショートショート コメディ？ SF <BR>【種別】 テクノロジー 変身<BR>【キーワード】 アニメ『デジタル所さん』</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200512/06000905/lightning.html">落雷</a></B></TD><TD><B>バレット</B> さん </TD><TD>(イラストなし)</TD><TD>2005/12/6(火)</TD><TD>66KB</TD><TD BGCOLOR="#E0D0C0"><A href="../~ts/kansou/bbs@log_baretto.cgi">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>雨に打たれていた子ギツネを助けた、銃技を得意とする青年・荒野鋼は、その帰り道に雷に打たれてしまう。彼の葬儀から帰ってきた家族、そして獣医が目にしたのは。<BR><B>【コメント】 </B>初投稿です。駄作の塊ですが、よろしくお願いします。<BR><B>【バレット さんのオススメ作品】</B> <A HREF="novel/200504/04081500/I_and_MyTime_01.html">僕と僕の今</a> <font size="-1">(ガソダムさん作)</font> <a href="novel/200209/19204751/doukyo.htm">同居人</a> <font size="-1">(城弾さん作)</font> <a href="novel/200010/20224827/mizuho.html">みづほの駒音</A> <FONT SIZE="-1">(水谷秋夫さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>子ギツネを助けたことで始まる、ハートフルストーリーです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション ウェスタンアームズ 不思議 <BR>【種別】 転生（？） メスの子狐＋青年＝キツネ耳の少女<BR>【キーワード】 オレっ娘 年齢変化 男性化キャラあり 入る？ 百合は……</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(207.241.229.215) , Competence : -1 -->
</BODY></HTML>
