<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel02.htm">機動アイドル　ミルキー・エンジェル　２</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/17(土)</TD><TD>53KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>士官学生「沖田優希」が乗り込んだ艦は、連邦軍のアイドル部隊「ミルキー・エンジェル」の乗務艦「シルフィード」だった。<BR><B>【コメント】 </B>正統派スペースオペラを書くつもりだったのに、出来上がったらこんな作品になってました。＾＾；<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>連邦宇宙軍のアイドル部隊「ミルキー・エンジェル」の臨時（？）メンバーになった美“少年”優希くんの、明日はどっちだあああっ！？<BR>
<b><a href="../novel/200308/07074715/m_angel01.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 <BR>【キーワード】 女装</TD></TR></TABLE><BR><BR>『よっすぃー』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/201004/02215640/akazukin.htm">二代目は赤ずきん</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2010/4/19(月)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=2daime">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>就職した僕のもとに、突然現れたのは……<BR><B>【コメント】 </B>え〜なんと申しましょうか……旅行帰りの車中でのネタ話から生まれたお話です。（＾＾）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>執事ふたたび。豪快に展開される不条理をどうぞ。<b><a href="../novel/201004/02215640/blazer.htm">【「女子高生っ！？」はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ 不条理 <BR>【種別】 変身<BR>【キーワード】 セバスチャン 着せ替え 執事 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/megami.htm">ああっ、女神さまっ</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん (<A href="http://www.h6.dion.ne.jp/~yossuli/top.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2006/12/6(水)</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>街中で女を引っかけて××をやっちゃったら……<BR><B>【コメント】 </B>自称「１７歳」の方が主役を務めるあの作品ではありません。念のため……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お久しぶりのよっすぃーさん。……そ、そんな強引な解釈ありですか？　女神さまっ！？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200109/21002626/red_buruma_ex.htm">学園戦士レッドブルマー番外編　私たちをスキーに連れてって♪</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん (<A href="http://www.h6.dion.ne.jp/~yossuli/top.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/5/22(日)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>スキーに行くには面子が必要。ドタキャンされたら、さぁどうする？<BR><B>【コメント】 </B>ＭＯＮＤＯさん、南文堂さん、ありがとうございました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>よっすぃーさんからは、<b><a href="../novel/robot_triathlon/robotryex-s04.htm">『私たちをスキーに連れてって♪』</a></b>の前日談。ウィンタースポーツには、いろいろな準備や気苦労が必要なのです……（笑）<b><a href="../novel/200109/21002626/gakuen_red_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 スキー スキー場は物価が高い（笑）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel00.htm">機動アイドル　ミルキー・エンジェル番外編　ぐらでゅえいしょん</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん (<A href="http://www.h6.dion.ne.jp/~yossuli/top.htm">Homepage</a>)</TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2005/3/15(火)</TD><TD>32KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>学生生活最後のイベント「卒業式」。ところが優希は出席禁止を言い渡されてしまう。一体どうして？<BR><B>【コメント】 </B>季節ネタです。本編とちょっと食い違いがあるかもしれませんが、その辺は愛嬌で（笑）。<BR><B>【よっすぃー さんのオススメ作品】</B> <a href="../novel/200104/09010648/title.htm">魔法少女　ラスカル☆ミーナ</a>（南文堂さん） <a href="../novel/robot_triathlon/title.htm"> ロボＴＲＹシリーズ</a> <FONT SIZE="-1">(ＭＯＮＤＯさん作)<BR>
</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>新しい門出を迎える皆様に、よっすぃーさんからご卒業祝いの番外編です。<BR>
<b><a href="../novel/200308/07074715/m_angel01.htm">【第一話はこちら】</a><a href="../novel/200308/07074715/m_angel02.htm">【第二話はこちら】</a><a href="../novel/200308/07074715/m_angel03.htm">【第三話はこちら】</a><a href="../novel/200308/07074715/m_angel04.htm">【第四話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 学園 <BR>【種別】 女装<BR>【キーワード】 卒業式</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel04.htm">機動アイドル　ミルキー・エンジェル　４</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん </TD><TD><B>画</B>(<B>よっすぃー ＭＯＮＤＯ</B>さん)</TD><TD>2004/8/3(火)</TD><TD>53KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>超巨大戦艦の出現で劣勢に追い込まれた地球連邦軍。それを跳ね返す優希のアイデアとは？<BR><B>【コメント】 </B>お付き合いいただいてありがとうございます。これで最終話です。ＭＯＮＤＯさんからも大量にイラストを戴き感謝感激です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なんであそこまで強気に出ることができるのに、女装を拒めないのだろう？　……それはね、優希クンだからだよ（笑）。<BR>
<b><a href="../novel/200308/07074715/m_angel01.htm">【第一話はこちら】</a><a href="../novel/200308/07074715/m_angel02.htm">【第二話はこちら】</a><a href="../novel/200308/07074715/m_angel03.htm">【第三話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 <BR>【キーワード】 女装</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel03.htm">機動アイドル　ミルキー・エンジェル　３</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/22(木)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>運行クルーが全滅し、孤立無援となったシルフィード。一方、ディラングの大艦隊は一路地球を目指していた。<BR><B>【コメント】 </B>うにゃーっ。どんどん正統派スペースオペラから離れていくような気が……<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>生き残った者は、生き延びなければならない。礎となって散っていった者たちのため……そして自分自身の明日のために。<BR>
優希、今こそ君の「漢」を見せる時！！　……見た目女の子だけど（笑）。<BR>
<b><a href="../novel/200308/07074715/m_angel01.htm">【第一話はこちら】</a><a href="../novel/200308/07074715/m_angel02.htm">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 <BR>【キーワード】 女装</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel02.htm">機動アイドル　ミルキー・エンジェル　２</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/17(土)</TD><TD>53KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>士官学生「沖田優希」が乗り込んだ艦は、連邦軍のアイドル部隊「ミルキー・エンジェル」の乗務艦「シルフィード」だった。<BR><B>【コメント】 </B>正統派スペースオペラを書くつもりだったのに、出来上がったらこんな作品になってました。＾＾；<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>連邦宇宙軍のアイドル部隊「ミルキー・エンジェル」の臨時（？）メンバーになった美“少年”優希くんの、明日はどっちだあああっ！？<BR>
<b><a href="../novel/200308/07074715/m_angel01.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 <BR>【キーワード】 女装</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/m_angel01.htm">機動アイドル　ミルキー・エンジェル　１</a></B></TD><TD><B><A href="mailto:yossuli@r4.dion.ne.jp">よっすぃー</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＮＤＯ</B>さん)</TD><TD>2004/7/16(金)</TD><TD>73KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>士官学生「沖田優希」が乗り込んだ艦は、連邦軍のアイドル部隊「ミルキー・エンジェル」の乗務艦「シルフィード」だった。<BR><B>【コメント】 </B>正統派スペースオペラを書くつもりだったのに、出来上がったらこんな作品になってました。＾＾；<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>『文庫』の路線からは外れる「女装」ものですが、主人公の見事なまでのいじられっキャラぶりを堪能してください（笑）。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 <BR>【キーワード】 女装</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/muma.htm">夢魔</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2003/11/8(土)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>虐められっ子のボクは、憧れの高木紗耶香さんを見つめるだけで満足していた。でもある日を境に……<BR><B>【コメント】 </B>ちょっとダークですかね？　観念的な描写になったので読みにくいのはご勘弁をm(__)m<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>最後の「逃避」場所を失った少年に、囁かれる誘惑の言霊。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ホラー <BR>【種別】 人格転移 テクノロジー<BR>【キーワード】 人格転移？</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200308/07074715/steel_heroine.html">鋼鉄のひろいん……？？</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2003/8/7(木)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>宇宙船と接触事故をしてしまった長沢博史。瀕死の重傷を背負った彼を救うために人工知能体のアーカスはある秘策に出た。<BR><B>【コメント】 </B>お暇なとき、お目汚しにでもして頂ければ幸いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お約束ですが、ギャグ満載で楽しい作品です。“あの娘”の反応が意外でした。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ SF <BR>【種別】 テクノロジー 変身<BR>【キーワード】 スーパーヒロイン 巨大ロボット</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200304/22211202/souiumonka.htm">そーいうもんか？</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2003/4/22(火)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>朝起きたら「オレ」はいきなり女の子になっていた。<BR><B>【コメント】 </B>タイトルのまんまです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>人間、いざとなるとけっこうタフなものではありますが…。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200109/21002626/gakuen_red06.htm">学園戦士・レッドブルマー　VOL6　THE FINAL OSHIMAIDESSE</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2002/11/15(金)</TD><TD>27KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついにレッドブルマーの正体をみんなに明かすときが来た！　って？<BR><B>【コメント】 </B>ＴＨＥ　ＦＩＮＡＬ　ＯＳＨＩＭＡＩＤＥＳＳＥ　ついに最終決戦の時が来た！　こんな間抜けなヒロインにお付き合い下さりありがとうございました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さんざん引っ張った「ニセブルマー」の正体とは？　身体の変調に苦しむ愛美。そして、ついに自らの手で全ての決着をつけんとするイーン・ベイダー！<BR>
　……今、最後の戦いの幕が上がる。<BR>
<b><a href="novel/200109/21002626/gakuen_red_title.htm">【シリーズタイトルはこちら】</b></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex12.htm">華代ちゃんシリーズ番外編 「ある噂」</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2002/11/3(日)</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ネットサーフィンの末、あるチャットにたどり着いて…<BR><B>【コメント】 </B>こんなの書いちゃっていいのかなぁ〜<BR>
七斬さん、南文堂さんと、新阪急ホテルのティールームで閉店まで雑談していたときに出てきた一発ネタです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>やはり外国でしかできないことというのはあるもんですがこれは…<BR>
<a href="../novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 不条理 <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200109/21002626/gensou.html">幻想空間</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2002/9/20(金)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>なにかにつけて俺に敵意を剥きだす小野寺が、バーチャルゲームで決闘を挑んできた……<BR><B>【コメント】 </B>思いつきの拙作です。勢いだけで書いちゃいました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>前半は、バーチャルゲームですが、最後が意外かも。</TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 変身<BR>【キーワード】 バーチャルリアルティー</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200109/15004009/slope2-2.html">続・坂道（よっすぃー版）</a></B></TD><TD><B>よっすぃー</B> さん </TD><TD>(イラストなし)</TD><TD>2002/6/22(土)</TD><TD>34KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yosswih">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>入れ替わって１０年の年月を経て、またあの入れ替わりが起きてしまった！<BR><B>【コメント】 </B>ふらっと様との競作です。はーとふりゃーをを目指して自爆しました（苦笑）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ある意味、これはパラレルワールドなんでしょう。ふらっとさんの続編とはまた違った味わいが楽しめます。<a href="novel/200109/15004009/slope1.html"><strong>【坂道はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ハーフコメディ <BR>【種別】 入れ替わり<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.145.38.157) , Competence : -1 -->
</BODY></HTML>


