
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb04.html">少年以上、少女未満　第四話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/12/26(火)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の四ヶ月目（六月）<BR><B>【コメント】 </B>初めての課外授業（遠足）でアクシデントが発生します。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="http://www.novels.jp/~ts/bbs/2ndbbs/bbs.cgi?action=html2&key=20041002162808&log=2004101004">南回帰戦線・銃機動祝祭日//Grenadable=>feast（グレネイダブル・フィースト）</A> <FONT SIZE="-1">(神城めぐみさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>心のなかで変わっていくものはなんでしょうね。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 イジメ 恋愛 コメディー（？） 学園 <BR>【種別】  医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR>『いとう』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb12.html">少年以上、少女未満　第十二話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/10/11(木)</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の十二ヶ月目（二月）<BR><B>【コメント】 </B>最終話です。王道なハッピーエンドです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>意外な真実。そして、睦月さんは女の子になったのでした。おしまいです。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 恋愛 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb11.html">少年以上、少女未満　第十一話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/10/1(月)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の十一ヶ月目（一月）<BR><B>【コメント】 </B>お姫様は魔法を求めて、もう一度あの場所へ向かいます。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200606/28222647/kinsyu_index.html">錦繍の夢</A> <FONT SIZE="-1">(英雄さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>素直にならない睦月さんに必要な魔法はあの場所で見つかでしょうか？<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 恋愛 コメディー（？） 学園 <BR>【種別】  医術 不可逆 変身<BR>【キーワード】 女性人格化（？） 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb10.html">少年以上、少女未満　第十話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/9/19(水)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の十ヶ月目（十二月）<BR><B>【コメント】 </B>最終話に向けて、そろそろ収束のストーリーへ入ります<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>圭に嫌われて落ち込む睦月さん。しかし、お話は意外な展開に。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 コメディー（？） 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 女性人格化（？） 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb09.html">少年以上、少女未満　第九話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/9/11(火)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の九ヶ月目（十一月）<BR><B>【コメント】 </B>難題は、ひとつ片付けたら続いて次がやってくるものです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>一難去ってまた一難です。ガーン、今度のは手ごわい。睦月さんの試練は続きます。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 学園 <BR>【種別】 医術 不可逆<BR>【キーワード】 女性人格化 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb08.html">少年以上、少女未満　第八話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/8/25(土)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の八ヶ月目（十月）<BR><B>【コメント】 </B>実はＴＳ娘だったあの娘はツンデレだったりします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>睦月くんとあの子は、ツンデレ?<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 コメディー（？） 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 女性人格化（？） 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb07.html">少年以上、少女未満　第七話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/4/2(月)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の七ヶ月目（九月）<BR><B>【コメント】 </B>ちょびっとだけ、ミステリーの要素が入ってたりします。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200310/31212238/isoro_index.html">居候はレヴァの王子様</A> <FONT SIZE="-1">(Plantainさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>実はそういうことなんですよー。ミステリーなんですよー。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 イジメ 恋愛 コメディー（？） 学園 <BR>【種別】  医術 不可逆 変身<BR>【キーワード】 女性人格化（演技） 親友萌え ボクっ娘 オレっ娘（今回のみ）</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb06.html">少年以上、少女未満　第六話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/3/1(木)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の六ヶ月目（八月）<BR><B>【コメント】 </B>少年が少女に変わっても、お話は嵐の前の静けさなのです。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200605/05101055/nijiiro_title01.htm">虹色のトレイル</A> <FONT SIZE="-1">(きりか進之助さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>とうとう、睦月くんにも訪れたもの。それは嵐の前の静けさなのか？<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 コメディー（？） 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb05.html">少年以上、少女未満　第五話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2007/2/13(火)</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の五ヶ月目（七月）<BR><B>【コメント】 </B>申し訳ありません。前回の投稿から一ヶ月経ってしまいました。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="http://www.novels.jp/~ts/bbs/2ndbbs/bbs.cgi?action=html2&key=20050220003105&log=2005031012">エムフ　登校</A> <FONT SIZE="-1">(Plantainさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>もう男の子ではない睦月。女の子にはいろんなヒミツがあるものです。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 コメディー（？） 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb04.html">少年以上、少女未満　第四話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/12/26(火)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の四ヶ月目（六月）<BR><B>【コメント】 </B>初めての課外授業（遠足）でアクシデントが発生します。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="http://www.novels.jp/~ts/bbs/2ndbbs/bbs.cgi?action=html2&key=20041002162808&log=2004101004">南回帰戦線・銃機動祝祭日//Grenadable=>feast（グレネイダブル・フィースト）</A> <FONT SIZE="-1">(神城めぐみさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>心のなかで変わっていくものはなんでしょうね。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 イジメ 恋愛 コメディー（？） 学園 <BR>【種別】  医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb03.html">少年以上、少女未満　第三話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/11/28(火)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子に変わっていく一年間の三月目（五月）<BR><B>【コメント】 </B>イジメの構造が見えてきます。反撃の準備は仲間集めから。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/itagaki.html">美少女指揮官ジュン＝イタガキ</A> <FONT SIZE="-1">(矢治浩平さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>徐々に反撃開始？ということなのだけれども、睦月くん、冷静すぎないかな？<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 イジメ 現代 恋愛 コメディー（？） 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/hankonka.html">反魂香</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/11/1(水)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>幼なじみの急な訃報が届き、大樹は故郷へと戻る。<BR><B>【コメント】 </B>続きものの方をお読みいただいている方には申し訳ありません。次回は戻らせていただきます。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200112/19020205/l_title.htm">超装甲機動兵器ライトニング</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>不思議なファンタジーです。最後まで読まないと判らないかも。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 不思議 <BR>【種別】 変身<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb02.html">少年以上、少女未満　第二話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/10/27(金)</TD><TD>16KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子へと変わっていく一年間の二月目。<BR><B>【コメント】 </B>本格的に物語が動き出します。最初の試練は、イジメです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>周りから排斥される睦月くん。さらに、体調不良でへたります。そんな中で、少しずつ周りに受け入れられていきます。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 恋愛 コメディ 学園 <BR>【種別】 医術 不可逆 変身<BR>【キーワード】 イジメ 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/lgmb01.html">少年以上、少女未満　第一話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/10/15(日)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>男の子が女の子へと変わっていく一年間の一月目<BR><B>【コメント】 </B>よくある男の子が女の子に変わっていくお話です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>突然の事態に、翻弄される主人公。<BR>
なお、第二掲示板にあったものが再構築されていますので、ストーリーが大幅に異なります。<BR>
<b><a href="novel/200504/26204417/lgmb_title.html">【シリーズタイトルはこちら】</a></b><BR>
</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 恋愛 コメディ 学園 <BR>【種別】  医術 不可逆 変身<BR>【キーワード】 親友萌え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg06.htm">機動天使軍ガブリエル　インタールード</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/10/11(火)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>第二部に入る前の幕間劇です。ＸＮＸのお話です。<BR><B>【コメント】 </B>大変遅れてしまい、待っていてくれていた方には申しわけ御座いません。ガブリエル再開致します。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>別の視点からの話の流れはこの後の流れにどう結びついていくのか。<BR>
<b><a href="novel/200504/26204417/mafg_title.htm">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 戦記 メカ <BR>【種別】 医術 変身 可逆<BR>【キーワード】 オレっ娘 陰謀劇 アニメ 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/gs.htm">少女症候群</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/7/19(火)</TD><TD>41KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>四百字詰め原稿用紙換算で、十数枚程度の短編で構成されたオムニバス。全四編。<BR><B>【コメント】 </B>夏なので、一応、怖い系の話かなぁと思うものを。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200112/20002028/vemale.html">Ｖｅ−ｍａｌｅ</A> <FONT SIZE="-1">(ＫＥＢＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>一粒で四度美味しく、さらに夏向けのヒンヤリ感。これはオススメです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 神秘 変身 <BR>【種別】 現代 病気 ホラー<BR>【キーワード】 オムニバス 年齢変化 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg05.htm">機動天使軍ガブリエル　第五話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/7/10(日)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>宇宙空間に燦然と百合が花開くお話です。<BR><B>【コメント】 </B>キーワードに百合が入ってない時点で、既にダブルミーニングで引っ掛けようって腹積もりがバレバレです（泣）。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200010/20224827/mizuho.html">みづほの駒音</A> <FONT SIZE="-1">(水谷秋夫さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>戦いの中に咲く百合。しかし、それは悲しい。<BR>
<b><a href="novel/200504/26204417/mafg00.htm">【プロローグはこちら】</a></b><b><a href="novel/200504/26204417/mafg01.htm">【第一話はこちら】</a></b><b><a href="novel/200504/26204417/mafg02.htm">【第二話はこちら】</a></b><b><a href="novel/200504/26204417/mafg03.htm">【第三話はこちら】</a></b><b><a href="novel/200504/26204417/mafg04.htm">【第四話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 宇宙 戦記 メカ <BR>【種別】 医術 変身 可逆<BR>【キーワード】 ちょっぴり百合？） （そろそろダーク？ アニメ 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg04.htm">機動天使軍ガブリエル　第四話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/6/22(水)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『お姉さま』が『お姉さま』になるための通過儀礼のお話です。<BR><B>【コメント】 </B>最近、五年ぐらい前に書いた小説をＨＤＤ内から発掘して見直していました。それが今よりも遥かに良い出来だったので、本気で凹みました。ブランクって怖いなぁ。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200203/23203640/ame_title.html">雨時々時雨シリーズ</A> <FONT SIZE="-1">(日比野さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>『お姉さま』もつらいです。ほんとうに。<BR>
<b><a href="novel/200504/26204417/mafg00.htm">【プロローグはこちら】</a></b><b><a href="novel/200504/26204417/mafg01.htm">【第一話はこちら】</a></b><b><a href="novel/200504/26204417/mafg02.htm">【第二話はこちら】</a></b><b><a href="novel/200504/26204417/mafg03.htm">【第三話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 戦記 <BR>【種別】  医術 変身 可逆<BR>【キーワード】  オレっ娘 強制 アニメ 露出</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg03.htm">機動天使軍ガブリエル　第三話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/6/7(火)</TD><TD>48KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『わたくし』と『お姉さま』に踊らされる天使と、『わたくし』と『お姉さま』を躍らせる男の話です。<BR><B>【コメント】 </B>第三話です。少し、足踏みしています。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200308/07074715/m_angel01.htm">機動アイドル　ミルキー・エンジェル</A> <FONT SIZE="-1">(よっすぃー さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>時には、予想を超えることもあります。<BR>
<b><a href="novel/200504/26204417/mafg00.htm">【プロローグはこちら】</a></b><b><a href="novel/200504/26204417/mafg01.htm">【第一話はこちら】</a></b><b><a href="novel/200504/26204417/mafg02.htm">【第二話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 戦記 <BR>【種別】  医術 変身 可逆<BR>【キーワード】  オレっ娘 強制 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg02.htm">機動天使軍ガブリエル　第二話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/5/23(月)</TD><TD>49KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『わたくし』と『お姉さま』の再会と、『お姉さま』に降りかかる試練のお話です。<BR><B>【コメント】 </B>第二話です。少し、シリアスが増えてきました。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="novel/200203/12200339/d_title.htm">紅の装甲竜騎兵</A> <FONT SIZE="-1">(YZAさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>小夜里と『お姉さま』は再会した。それは少し、いつもとは違った。<BR>
<b><a href="novel/200504/26204417/mafg00.htm">【プロローグはこちら】</a></b><b><a href="novel/200504/26204417/mafg01.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 戦記 <BR>【種別】  変身 忍術 可逆<BR>【キーワード】  オレっ娘 着替え 強制 水着・露出 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg01.htm">機動天使軍ガブリエル　第一話</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/5/9(月)</TD><TD>47KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>『お姉さま』と『わたし』が出会います。<BR><B>【コメント】 </B>第一話です。ストーリーの展開が遅いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>出会いは突然始まる。<BR>
<b><a href="novel/200504/26204417/mafg00.htm">【プロローグはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  SF 戦記 <BR>【種別】 医術 変身<BR>【キーワード】  オレっ娘 強制 アニメ 鏡</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200504/26204417/mafg00.htm">機動天使軍ガブリエル　プロローグ</a></B></TD><TD><B><A href="mailto:gpmgxp@yahoo.co.jp">いとう</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/4/26(火)</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=itou">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>主役が居ないプロローグです。<BR><B>【コメント】 </B>ええっと、初投稿になります。遥か昔に、第二掲示板で予告したお話です。待っていてくれた方がいらしたら、「遅くなってしまって、ゴメンなさい」。<BR><B>【いとう さんのオススメ作品】</B> <A HREF="../novel/200207/03224430/roromi_title.html">微妙存在ろろみ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>謎の侵略者、その魔の手に落ちた殖民惑星。そんな緊迫する情勢の中、何故か「にょうん」なできごとが……（笑）<BR>
　第二掲示板で話題になったあのストーリーが、今始まる……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 戦記 <BR>【種別】 変身 可逆 テクノロジー<BR>【キーワード】 親友萌え ボクっ娘 操り 洗脳 異形 強制 特撮</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.224.108.238) , Competence : -1 -->
</BODY></HTML>


