<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights09.html">新世紀アラビアンナイト９</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/7/16(日)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ジェルピ学園にイラク娘のサミアがやってきた。<BR><B>【コメント】 </B>新世紀アラビアンナイトの第１章は今回で最終回です。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/mashiro/nemesis_corp.html">仕事</A> <FONT SIZE="-1">(真城悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どうやら、サミアはハイアットよりも一枚上手だったようです。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 旧約聖書</TD></TR></TABLE><BR><BR>『雅良生』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights09.html">新世紀アラビアンナイト９</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/7/16(日)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ジェルピ学園にイラク娘のサミアがやってきた。<BR><B>【コメント】 </B>新世紀アラビアンナイトの第１章は今回で最終回です。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/mashiro/nemesis_corp.html">仕事</A> <FONT SIZE="-1">(真城悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>どうやら、サミアはハイアットよりも一枚上手だったようです。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 旧約聖書</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_09.html">見えない生物バイトン９</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/29(木)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>メリッサは、ＩＢＭの追求を逃れて、女から男へ、男から女へと変身を繰り返しながら逃亡を続ける。<BR><B>【コメント】 </B>これで最終回です。草葉の陰から見守っていただいた皆様がた、本当に有難うございました。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/kayo_chan/extra/ichigo01.htm">いちごちゃんシリーズ01「いちごちゃん誕生！」</A> <FONT SIZE="-1">(真城悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>バイトンの存在は悪だったのか善だったのか、真実はきっと誰にも分からない……。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次作品 「見えない生物バイトン」ラッセル作 <BR>【種別】 変身<BR>【キーワード】 天使</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_08.html">見えない生物バイトン８</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/22(木)</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>娘のメリッサが、バイトンと人間の混血児であることをつきとめたグレアムは、ＩＢＭの再建のために彼女をかくまっている自分自身の母親を手にかけることになる。<BR><B>【コメント】 </B>巷は「ダビンチ・コード」の噂で持ちきりです。１５年も前に同じネタで同人誌に「ルパン３世あばかれた封印」を上梓した身としては、悔しくて転げまわっています。でもけっこう古いネタですしキリスト教に遠慮して内容をかなり自主規制している印象があります。たとえば「トマスによる福音書」にはイエスの本妻とともに２号さんも登場するのですが、そのあたりはカットしてますしね。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200502/01114354/experience_title.html">Experience</A> <FONT SIZE="-1">(ゆぐどらしるさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>グレアムはけっこうなやんちゃ少年だったようですね。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 「見えない生物バイトン」ラッセル作 <BR>【種別】 脳移植手術<BR>【キーワード】 家族</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life09.html">グッド・ライフ９</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/13(火)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>人気のＴＶシリーズ「男前の彼女」の撮影のために来日したジャニスには、異母妹のゆかりと出会う計画があったのだが…<BR><B>【コメント】 </B>ジャニスの子役時代の話は、これで終わりです。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/robot_triathlon/episode01/robot_triathlon.html">放課後は美少女っ</A> <FONT SIZE="-1">(ＭＯＮＤＯさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ジャニスの周りは、本当にいい人たちばかりだったようです。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 女優 <BR>【種別】 性転換手術<BR>【キーワード】 １９７０年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life08.html">グッド・ライフ８</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/31(水)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>１９７０年北アフリカの港町タンジール。俳優というあだ名の漁師とその彼をじっと見つめる少年がいた。後にオスカークイーンを獲得した女優ジャニス誕生の秘密が今あかされる。<BR><B>【コメント】 </B>ＳＦマガジン４月号リーダーズストーリー入選作の安藤繁の「どうしてＮＡＮＯ？」は読まれましたか？ＴＳ小説にこの手があったかと悔しいことしきりです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ついに明らかになる、ジャニスが「彼」から「彼女」になった理由。そこには、ジャニスなりの信念があったのだ。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 女優 <BR>【種別】 性転換手術<BR>【キーワード】 １９７０年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights08.html">新世紀アラビアンナイト８</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/4/26(水)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>１０日間も不登校をつづけていたタスクが、ジェルピ学園に久しぶりに顔を出した。見ず知らずの少女が出産するのに立会い、行きがかりで生まれた赤ん坊を引き取ることにしたという話を聞いて、バリーは、「お前がそんなお人好しだから、俺達は女なんてつまらないものに変身してしまったのだ。」と言ってしまう。<BR><B>【コメント】 </B>花見のお誘いがかかるのに、忙しくていけない状態なのが癪です。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200303/17233027/hunter24.html">狩人 - 勇者と聖女 -</A> <FONT SIZE="-1">(DEKOIさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>感情にまかせて口にしてしまったことって、あとで後悔すること多いですよね。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 ギルド</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights07.html">新世紀アラビアンナイト７</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/4/7(金)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ジェルピ学園のお風呂場では、アメリカ娘のハイアットと中国娘の馬秋嵐の無差別級格闘技戦の幕が開こうとしていた。<BR><B>【コメント】 </B>雪の季節が終わって、一息ついています。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200105/21013225/oume.html">お梅ちゃん漫遊記</A> <FONT SIZE="-1">(かわねぎさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>同じイスラムでも、国の違う二人から見たイスラムの在り方は大きく異なるようだった。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights06.html">新世紀アラビアンナイト６</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/3/16(木)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>アレキサンドリアの海岸通にあるスーパー銭湯クブラカーンで働いている元気いっぱいの女の子タミヤには、とんでもない秘密があった。<BR><B>【コメント】 </B>雪が降ってきました。春はいつになったらきてくれるのかしら、ああ<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200512/13211922/saikai.html">幼なじみとの再会</A> <FONT SIZE="-1">(テンメイさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>タミヤの行動は秘密の潜入捜査みたいで、なんだかワクワクしてきます。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights05.html">新世紀アラビアンナイト５</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/3/3(金)</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ユネスコ反主流派のリーダーであるジェルピ本人から学園の寮母になってくれるよう慫慂されたカピタンであったが、彼女には容易に引き受けられない理由があった。<BR><B>【コメント】 </B>会社の同僚たちと沖縄旅行をしてきました。那覇の「ナヴィのかまど」で食事をした際に、店長のおすすめということでマングローブをいただきました。内地のワタリガニにそっくりでおいしかったですよ。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200303/17233027/akuma_title.html">悪魔を呼んでみよう！</A> <FONT SIZE="-1">(DEKOIさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>話は徐々に核心へ。カピタンの目に映る現在の欧米社会の姿が、本人の口から語られる。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights04.html">新世紀アラビアンナイト４</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/2/18(土)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>生まれたばかりの息子を抱えたカピタンは、アレキサンドリアで、かつて愚か者の霊廟で共に男から女に変身した２人と再会する。<BR><B>【コメント】 </B>雪は峠を越しましたが、寒さは厳しさを増したような気がします。風邪は万病の元といいます。皆さんもお気をつけて。<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200112/19020205/prince.htm">王を継ぐ者</A> <FONT SIZE="-1">(ライターマンさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>久々にカピタン、バリー、タスクの３人が集結！<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life07.html">グッド・ライフ７</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/1/29(日)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>シスター・ジルの好意で、サンタマリア教会の応接室でマリーと出会うことの出来たジャニスは、何とかして仲直りしようと努力するのだが‥‥‥<BR><B>【コメント】 </B>窓の外は吹雪です。明日は会社で安全運転講習会があります。会社に行く途中で事故らないかと心配です。皆さんもお気をつけて<BR><B>【雅良生 さんのオススメ作品】</B> <A HREF="./novel/200312/05062153/mlc_bgl_01.html">魔法のリップスティック</A> <FONT SIZE="-1">(Taika Yamaniさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>のっけからいきなり驚きの展開。次話が楽しみです。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 性転換手術<BR>【キーワード】 ハリウッド １９７０年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life06.html">グッド・ライフ６</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/1/22(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ハリウッドの人気女優のジャニスと、ロックスターのマリーが、ペガサス監督の一人息子で少年スタントマンとして有名なグリンをとりあいをして世界一の食料品スーパーの店内で大暴れ？１９７４年当時タブロイド紙の格好のネタとなった「ジャニス・マリー戦争」の真実とは？<BR><B>【コメント】 </B>年末以来、やっと自宅に戻ってきましたが、明日の朝からまた大雪だとのことですので着替えを持って今からまた会社に向かいます。皆さんも身体に気をつけてがんばってくださいね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>マリーと仲直りするため、ジャニスはとある場所へと向かう。そこは……。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 性転換手術<BR>【キーワード】 ハリウッド １９７０年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights03.html">新世紀アラビアンナイト３</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/1/6(金)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>射殺された父親の死体をハイヤーで死者の街に運んで葬儀を終えたバリーには、その後につらい仕事が待っていた。<BR><B>【コメント】 </B>窓の外は一面の銀世界です。職場まで無事に行き着けるかなと思ったりしています。皆さんも気をつけて行ってくださいね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>その日は、バリーにとって非常に慌ただしく過酷な日となった。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights02.html">新世紀アラビアンナイト２</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/12/21(水)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いかなる神のいたずらか？女の子に変身させられた３人のイスラム過激派の物語。今回はかわいそうなバリー君のお話です。<BR><B>【コメント】 </B>寒さが急激に迫ってきました。皆さんお風邪を召しませんように。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>神様はどうやら、バリーに平凡な人生を送らせる気はないらしい。<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 変身<BR>【キーワード】 ユネスコ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/arabian_nights01.html">新世紀アラビアンナイト１</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/12/8(木)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いかなる神のたくらみか？女の子に変身させられた３人のイスラム過激派の物語。今回は３人が女の子に変身した発端のお話です。<BR><B>【コメント】 </B>アラビヤ語でオ○ン○ンを何というのかについては、白水社の「パスポート辞典」から苦労して拾い上げましたが、間違っているようならご教示ください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>それは神の慈悲か、それとも試練か……？<BR>
<strong><a href="./novel/200404/07211628/arabian_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 <BR>【種別】 神秘 変身<BR>【キーワード】 イスラム過激派 ユネスコ 旧科学技術庁</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life05.html">グッド・ライフ５</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/11/19(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>幼くして性転換手術を受け、映画女優として成功したジャニスの物語。今回は撮影途中で降板させられた映画の主役の座を持ち前の行動力で奪還するお話です。<BR><B>【コメント】 </B>映画「奥様は魔女」を家内に引きずられるようにして見にいきました。冒頭でハリウッドの全景を空から見せてくれ、たたみかけるようにあの、映画女優たちが買い物をしにいくことで有名なスーパーマーケットのラフルズでの買い物する様子を見せてくれたのには唸りました。ハリウッド大好き人間ならはまると思いますよ。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>幾度と無くくり返される失敗に、さすがのジャニスも気落ちした様子だが……。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】  青春 映画女優 <BR>【種別】 現代医学 性転換手術<BR>【キーワード】 ハリウッド １９７０年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life04.html">グッド・ライフ４</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2005/11/12(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>幼くして性転換手術を受け、女優として成功したジャニスの物語。今回はハフナー監督の「傷つくことなんか怖くない」に主演の少女を演じる途中で解雇されたエピソードです。<BR><B>【コメント】 </B>リンジー・ローハンとヒラリー・ダフの大喧嘩を検索中に地雷に触れて再起不能の状態からようやく立ち直ることができました。初心に戻った気持ちで投稿します。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>主役に抜擢されたジャニスがなぜ途中で降板させられてしまったのか？<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】  青春 映画女優 <BR>【種別】 現代医学 性転換手術<BR>【キーワード】 ハリウッド 1970年代</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/uganda_04.html">ウガンダの小公女探偵団・要塞学園の巻１</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/5(火)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>内戦の激化で子供たちを守るために要塞化した学校に子供たちを寝泊りさせて勉強させる特別措置がとられているウガンダ北部のズールーに、国王マイケル・ムテサ二世陛下がお忍びで訪問された。はてさて、その目的とは？<BR><B>【コメント】 </B>アニメの「Ｒｅキューティーハニー」を３回も見てしまいました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>バリー、ジャリ、サンセ、ビビたちの４人は、カンパラを出てとあるところに来ていた。<BR>
<strong><a href="./novel/200404/07211628/uganda_01.html">【第１話はこちら】</a><a href="./novel/200404/07211628/uganda_02.html">【第２話はこちら】</a><a href="./novel/200404/07211628/uganda_03.html">【第３話はこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業 後宮 ミステリ <BR>【種別】 変成女子 仮性半陰陽<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/uganda_03.html">ウガンダの小公女探偵団・悪質な落書きの巻３</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/10/5(火)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>一夜の冒険の後、小公女たちも無事に王宮にご帰還。さて事件の結末は？<BR><B>【コメント】 </B>解決編が遅くなってごめんなさい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>事件は無事解決を迎えます。そして……<BR>
<strong><a href="./novel/200404/07211628/uganda_01.html">【第１話はこちら】</a><a href="./novel/200404/07211628/uganda_02.html">【第２話はこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業 後宮 ミステリ <BR>【種別】 変成女子 仮性半陰陽<BR>【キーワード】 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_07.html">見えない生物バイトン７</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/9/25(土)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>失明して病院で療養中のグレアムのところへ、女の身体のドナーであるナディアの１３歳の娘メリッサが看病をしにやってきた。<BR><B>【コメント】 </B>ブッシュ政権初期の財務長官、ポール・オニールのエピソードは、「忠誠の代償」ロン・サスキンド日本経済新聞社刊を参考にしました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>グレアムが療養している間に、IBMは大変なことになっていた。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作「見えない生物バイトン」ラッセル <BR>【種別】 脳移植手術<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_06.html">見えない生物バイトン６</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/8/14(土)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>重傷を負ったグレアムの輸血用の血液を受け取りにバグダッド市内の病院に向かったマッケイ特務曹長たちは何者かの襲撃を受ける。<BR><B>【コメント】 </B>イラク戦争において米軍兵士に支給されるべき物資に不足が生じた状況については「イラク戦争従軍記」野嶋剛・朝日新聞社刊を参考にさせていただきました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>物資不足により輸血用血液まで満足に手に入らない。果たして血液は無事グレアムの元に届くのだろうか。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作「見えない生物バイトン」ラッセル <BR>【種別】 脳移植手術 医術 変身<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_05.html">見えない生物バイトン５</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/28(水)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イラク戦争が事実上終結。会議に出席する為に空港に赴いたグレアムは何者かに狙撃される。<BR><B>【コメント】 </B>終戦後のバグダッドの状況については、朝鮮日報のカン・インソン先生の著作「砂漠の戦場にもバラは咲く」毎日新聞社刊を参考にさせていただきました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>バイトンより人間の方がたちが悪いのかもしれない。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 脳移植手術 医術 変身 <BR>【種別】 二次創作「見えない生物バイトン」ラッセル<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_04.html">見えない生物バイトン４</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/24(土)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イラク戦争に従軍中のグレアムは、米本土のウオールとの国際電話の中で、ドナーであるナディアが横領した金を何に使ったかを知らされる。<BR><B>【コメント】 </B>イラク戦争緒戦の状況については、「軍事解説　湾岸戦争とイラク戦争」　河津幸英著　アリアドネ企画三修社刊を参考にさせて頂きました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>この世界のどこかで、戦争は続いている。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 「見えない生物バイトン」 ラッセル <BR>【種別】 脳移植手術 医術 変身<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_03.html">見えない生物バイトン３</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/7/10(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>国務省でのブリーフィングの後、ショップでイラクに持っていく装備の買い物中にグレアムは尾行者の存在に気がついた。<BR><B>【コメント】 </B>アメリカ政府内の非戦派と開戦派の対立については、「ブッシュの戦争」・ボブ・ウッドワード・日本経済新聞社刊を参考にさせていただきました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>多くの問題を抱えている組織、それがIBM。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作「見えない生物バイトン」ラッセル <BR>【種別】 脳移植 医術 変身<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_02.html">見えない生物バイトン２</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/27(日)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「見えない生物バイトン」に操られて、残忍なテロを繰り返すアジア人たちの目を覚まさせるためのイラクへの侵攻が秒読み段階に入り、脳移植で女の身体になったグレアムもペンタゴンでの作戦会議に参加にすることになる。<BR><B>【コメント】 </B>文中の詩「千の風になって」は、詩人の新井満先生の訳詩をほんの少し変えたものです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>劣化ウラン弾。唯一、"見えない生物"と対抗できる手段と目されている。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 作ラッセル 訳 二次創作 昭 矢野徹 「見えない生物バイトン」 <BR>【種別】 脳移植 医術 変身<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/baiton_01.html">見えない生物バイトン１</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/27(日)</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「同時多発テロの実行犯たちは、見えない生物によって操られていた？」９月１１日のテロによって同時に殉職した同僚の女性科学者の身体に脳移植されることによって蘇った男グレアムは、見えない生物バイトンと戦う目的で設立された合衆国政府組織ＩＢＭ（Invisible Barrier Mission）を再建するが、それは新たな悪夢の始まりでもあった。<BR><B>【コメント】 </B>１９３９年に雑誌連載され、後に単行本化されて大ベストセラーになったＳＦ揺籃期の傑作をベースにした少年少女小説です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>2001年9月11日。バイトンと呼ばれる見えない生物と戦う組織、IBM。<BR>
<strong><a href="./novel/200404/07211628/baiton_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作 訳・矢野徹 作・ラッセル 「見えない生物バイトン」 <BR>【種別】 脳移植 医術 変身<BR>【キーワード】 女性人格化  親友萌え 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/nuts_01.html">おんなにナッツ　１</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/6/25(金)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>世界帝国アメリカの首都ワシントンＤＣ。ダウンタウンではストリートキッズたちの抗争によって連日のように犠牲者を出ていた。そんな対立するストリートキッズの２つの組織を美容師と高等検察官が間に入って手打ちをさせて、その後は土木施設課の下請けの職員としようという話が持ち上がった。そんな折も折、組織の１つナッツ団のリーダーのナッツが、正体不明の送り主から送られてきたナッツを食べて女の子に変身してしまった。<BR><B>【コメント】 </B>ウガンダで内乱が起きてしまいました。でも小公女たちは健在です。おっつけ最近の状況をお知らせしますので、もうしばらくお待ちください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>雅良生さんお得意の、実写のような雰囲気を持つ作品です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 二次創作（「おとなにナッツ」フクシマハルカ 講談社コミックなかよし） <BR>【種別】 変身 テクノロジー<BR>【キーワード】 美少年 アニメ ナッツ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/uganda_02.html">ウガンダの小公女探偵団　悪質な落書きの巻２</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/25(火)</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ウガンダ国王の後宮に仕えるカラマージョの公女たちは、男性に生まれて後に女性に変身する変成女子。２１世紀のウガンダ王宮を舞台に勇敢な少年の心を持つ少女たちの活躍を描く探偵談。<BR><B>【コメント】 </B>２０世紀初頭のウガンダを舞台にした傑作長編小説「人喰鉄道」を書かれた戸川幸夫先生がつい先日お亡くなりになりました。謹んでご冥福をお祈り申し上げます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>謎だらけの落書き事件。その謎解きが始まります。<BR>
<a href="./novel/200404/07211628/uganda_01.html"><strong>【第１話はこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ミステリー 職業 <BR>【種別】 変成女子 変身 仮性半陰陽<BR>【キーワード】 後宮 ボクッ娘 アニメ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/uganda_01.html">ウガンダの小公女探偵団　悪質な落書きの巻１</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/9(日)</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ウガンダ国王の後宮に仕えるカラマージョの公女たちは、男性に生まれて後に女性に変身する変成女子。２１世紀のウガンダ王宮を舞台に勇敢な少年の心を持つ少女たちの活躍を描く探偵談。<BR><B>【コメント】 </B>グッド・ライフは、しばらくお休みをいただいての新作です。まだまだ未熟者ですが、よろしくお願い申し上げます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>雅良生さんの新シリーズがスタート。５人の小公女たちの楽しげな雰囲気が漂っています。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ミステリー 職業 後宮 <BR>【種別】 変成女子 仮性半陰陽 変身<BR>【キーワード】 アニメ ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life03.html">グッド・ライフ３</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/30(金)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>性転換手術を受けて女優としてハリウッドで活躍し、後にオスカークイーンを獲得したジャニスの波乱の生涯。今回で映画ダウンタウン・ブルース撮影時のエピソードは、完結します。<BR><B>【コメント】 </B>エマのモデルは、映画タイタニックのヒロインを演じたケイト・エリザベス・ウインスレットのお師匠様です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>映画「ダウンタウン・ブルース」完成の裏には、様々な人たちの努力が存在した。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業 現代 芸能界 <BR>【種別】 性転換手術 医術 変身<BR>【キーワード】 オレッ娘 強制 人生ドラマ</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life02.html">グッド・ライフ２</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/30(金)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>性転換手術をして女優となりオスカークイーンを獲得したジャニスの波乱の生涯。今回は映画ダウンタウン・ブルース撮影時のエピソードの続き<BR><B>【コメント】 </B>ご存知の方も多いと思いますが、更衣室が破壊された事件は、映画ダウンタウン物語の撮影中に起こった実話です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ジャニスは意を決し、皆にとある告白を始める。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業  青春 <BR>【種別】 性転換手術 医術 変身<BR>【キーワード】 オレっ娘 ハリウッド 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200404/07211628/good_life01.html">グッド・ライフ</a></B></TD><TD><B><A href="mailto:garyosei@agate.plala.or.jp">雅良生</a></B> さん </TD><TD>(イラストなし)</TD><TD>2004/4/7(水)</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=garyosei">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>複雑な事情で幼くして性転換手術を受けさせられて、ハリウッド映画の子役俳優としてデヴューし、名子役から名優は生まれないというジンクスを破ってオスカー・クイーンを獲得した女優ジャニス・イアンの波乱に満ちた生涯。<BR><B>【コメント】 </B>はじめまして、雅良生は「がりょうせい」と読んでください。よろしくお引き回しのほど、お願い申し上げます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>映画の撮影は、きれい事だけではない。よりリアルな撮影には、外道とも呼ばれても仕方ない手段を取る。<BR>
<strong><a href="./novel/200404/07211628/good_life_title.html">【シリーズタイトルはこちら】</a></strong></TD></TR><TR><TD COLSPAN=6>【ジャンル】 職業  芸能界 青春 <BR>【種別】 性転換手術 医術 変身<BR>【キーワード】  オレっ娘 強制 人生ドラマ</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.237.183.249) , Competence : -1 -->
</BODY></HTML>
