<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200608/14075115/allgreen2.html">オール・グリーン　第２話</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/24(木)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>回り始めた陽介の新しい生活。そして、「彼女」が現れた。<BR><B>【コメント】 </B>さて、彼女は今後どう使ってくれようか？　勢いで出したので、あんまり気にしないでね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いえいえ気になりますです。文庫古参のファンとしては。（<b><a href="../novel/concerto/concerto_1.html">ここも見てねっ</a></b>）<BR>
　というわけで、突然女の子になっちゃった陽介くんの、新しい生活が始まります。もちろん最初は――<BR>
<b><a href="../novel/200608/14075115/all_green.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 青春 <BR>【種別】 医術<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR>『矢治浩平』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200608/14075115/allgreen2.html">オール・グリーン　第２話</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/24(木)</TD><TD>29KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>回り始めた陽介の新しい生活。そして、「彼女」が現れた。<BR><B>【コメント】 </B>さて、彼女は今後どう使ってくれようか？　勢いで出したので、あんまり気にしないでね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いえいえ気になりますです。文庫古参のファンとしては。（<b><a href="../novel/concerto/concerto_1.html">ここも見てねっ</a></b>）<BR>
　というわけで、突然女の子になっちゃった陽介くんの、新しい生活が始まります。もちろん最初は――<BR>
<b><a href="../novel/200608/14075115/all_green.htm">【第一話はこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 青春 <BR>【種別】 医術<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/tr_gals_no13.html">生命戦隊トランスギャルズ第十三話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2001/7/10(火)</TD><TD>39KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B> 花火大会の後、亜紀の婚約者である英嗣が何者かに襲われた。そしてノーマの戦闘員が直接英嗣を襲う。ノーマの目的は何なのか？　その背後に恐るべき陰謀が控えていた。<BR><B>【コメント】 </B> 十一話や十二話と比べると、印象薄いと思います。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B> 二重三重のからめ手で戦乙女たちに迫る鬼沢。千々に乱れる亜紀の心。そしていさみの身体の変調……<BR>
　トランスギャルズ、佳境へっ！<BR>
<b><a href="novel/tr_gals/title.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 近未来 <BR>【種別】 変身 超科学<BR>【キーワード】 オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ第12話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2001/5/6(日)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>戦いに意味を見いだせぬまま漂泊する戦乙女。そんな彼女を『呪われし運命の巫女』と呼ぶ黒い影。そして……。<BR><B>【コメント】 </B>前回はなんか評判良かったんですが、話がどんどん深みにはまっていって、自分の能力の限界を超えていくのを感じます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>たとえどんなことがあっても、いさみちゃんはいさみちゃんです。確固たる意志と覚悟を持つ真の敵に、一歩も引かない彼女の決意を見てください。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 近未来 <BR>【種別】 変身 超科学<BR>【キーワード】 オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ 第11話「復活の翼」</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>2001/1/7(日)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>信じるものを失って漂流する少女。自分の中に芽生えた少女としての想い。さまざまな想いが交錯する中、非情にも時は過ぎていく。真琴の想いは戦友(とも)に届くのか？<BR><B>【コメント】 </B>前回の重苦しい雰囲気をそのまま引きずってます。読むのがつらい人もいるかもしれませんね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いさみたちも、生身の少年・少女なわけで、迷ったり傷ついたり逃げちゃったりもします。どん底であがくいさみちゃんは、そこでいったい何を見て何を掴むのでしょうか……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ヒーロー アクション SF <BR>【種別】 テクノロジー 変身<BR>【キーワード】 マッドサイエンティスト オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ第１０話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2000/10/12(水)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>夏休みがもう始まろうとするころ、新タイプのノーマの怪人が現れる。ノーマの正体がいよいよ明らかになる。<BR><B>【コメント】 </B>次回予告から若干ずれていますね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ソフトムードの乙女心シリーズ(勝手に命名)から一転、シリアス＆ハードな新展開。信じる正義を失って、戦乙女の心は揺れる……。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 近未来 <BR>【種別】 変身 超科学<BR>【キーワード】 オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ第９話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2000/9/8(金)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>生智学園の近所にある、私立星命小学校のスクールバスが真琴たちの目の前でノーマに襲われた。実は星命小学校には脅迫状が届いていたが、ただの悪戯として処理をしていなかった。そこで真行寺は一計を案じた。<BR><B>【コメント】 </B>ツボにはまった人は正直に手を上げてください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>トランス・ギャルズもとうとう９話目。今回はいさみちゃんがちょっとしたハプニングに見舞われます。さてその状況で彼女たちはどういった行動を取るのでしょうか？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション SF 近未来 <BR>【種別】 超科学<BR>【キーワード】 オレっ娘 年齢退行 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ第８話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2000/5/29(月)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真琴の兄、忠義と、その婚約者奈緒との結婚式が近づく中、結婚式場で花嫁以外の出席者が殺されるという事件が連続する。ノーマの影を察したトランスチームが取った手とは？<BR><B>【コメント】 </B>CGI文庫化の前に手直しをかけるつもりだったんですが、さっさとアップロードすることにしました。<BR>
<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回のエピソードのメインキャラは真琴ちゃん。いつもとは違った一面が見れるかも…</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF 近未来 <BR>【種別】 変身 超科学<BR>【キーワード】 オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ　第７話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2000/4/21</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>前回の予告を見よう！<BR><B>【コメント】 </B>構想も何もなしで進めると、単純に計画がずれこむだけですよね。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回は亜紀ちゃんメインのお話ですね。と同時に真琴ちゃん☆パニック！ な回でもありました。お気の毒に、というか(笑)。シリアスとコメディの配分が絶妙でした。第２話「運命のいたずら」をあらかじめ読み返しておくといいかも。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション SF 近未来 <BR>【種別】 変身 超科学<BR>【キーワード】 オレっ娘 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ　第６話</a></B></TD><TD><B><A href="mailto:yaji@lisa.novel.ac">矢治浩平</a></B> さん (<A href="http://www2k.novel.ac/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2000/3/6</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>いさみがつい最近まで住んでいたＮ市になぞの物体が現れた。地域住民を守るため！ 今日も彼女たちは闘う！<BR><B>【コメント】 </B>次回予告がやっと書けるようになりました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いさみが、実の妹である美優ちゃんと再会を果たします。が、美優ちゃんはまさかお兄さんがお姉さんになっているなんて知らず……というドキドキのシチュエーションです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション SF <BR>【種別】 変身 超科学<BR>【キーワード】 特撮</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/only_future.html">たった一つの未来に向かって</a></B></TD><TD><B><A href="mailto:yaji@mxv.mesh.ne.jp">矢治浩平</a></B> さん (<A href="http://www2k.biglobe.ne.jp/~yaji">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>1999/10/24</TD><TD>57KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>神無月匠が酔っ払って帰ってきた朝。気がつくと一日記憶が飛んでいて、床には女の子が眠っていた。<BR><B>【コメント】 </B>とにかく疲れました。100KBとか書く人いますけど、どうやったらあんなの書けるんですか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>自分と記憶を共有するもうひとりの自分がいたら…しかもそれが異性だったりしたら…？ この物語の主人公はそんな不思議な体験をします。読み応えのある作品です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 人格転移<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan18.html">華代ちゃんシリーズ 「スキャンダル」</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/8/23</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan11.html">華代ちゃんシリーズ 「満員電車」</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/8/21</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/title.html">生命戦隊トランスギャルズ　第５話</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/8/9</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真琴です。私たちの街で変な事件が起こってるの。あちこちで飛び降り自殺者が増えてるし、妙な交通事故が増えているの。真行寺博士は「ノーマの仕業だ」っていうんだけど。どうなのかしら？　え、いさみちゃんのお友達が屋上から飛び降りた?!　…今度の敵はちょっとやっかいね！<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/pool.html">ある暑い日</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/8/3</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B>今回は「<a href="novel/concerto/">「コンチェルト」</a>」一作目の空白の時間を埋める形になっています。夏休みのどこか、ほのぼのとした夏の暑い日の数日を描いてみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/tr_gals_no3.html">生命戦隊トランスギャルズ・第３話</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/5/13</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/tr_gals_no4.html">生命戦隊トランスギャルズ・第４話</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/5/13</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/rental/oem/kawaiiaitu.html">かわいい君が悪いのさ(Rental Body Kouhei.Yaji Version)</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/4/1</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 学園 <BR>【種別】 超科学<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/white_day.html">一番素敵な贈り物</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/3/13</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>コンチェルト・シリーズ最新作です。恒例となった感のある季節ネタですね！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 青春 <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/concerto_5.html">チョコレートに想いを込めて（コンチェルト・シリーズ）</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1999/2/11</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/concerto_4.html">一年目のクリスマス（コンチェルトシリーズ）</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/11/16</TD><TD>19KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/tr_gals_no2.html">生命戦隊トランスギャルズ・第２話</a></B></TD><TD><B>矢治浩平</B> さん (<A href="http://www2.sts.co.jp/~yaji/cgi-bin/transgals.cgi">Homepage</a>)</TD><TD><B>画</B>(<B>紅葉</B>さん)</TD><TD>1998/11/16</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><I>（管理人より）：原作者である矢治さんを中心にプロジェクトが進行中です。詳しくは、<a href="http://www2.sts.co.jp/~yaji/cgi-bin/transgals.cgi">矢治さんのページ</a>を御覧になって下さい。</I><BR>
<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/tr_gals/tr_gals_no1.html">生命戦隊トランスギャルズ</a></B></TD><TD><B><A href="mailto:yaji@mxv.mesh.ne.jp">矢治浩平</a></B> さん </TD><TD><B>画</B>(<B>紅葉</B>さん)</TD><TD>1998/10/24</TD><TD>17KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/my_brother/ani_2.html">お兄ちゃんと呼ばせて(２)</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/10/18</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>新たなる場所での新たなる生活。そして雪也は新たな決意をする。<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/my_brother/ani_1.html">おにいちゃんと呼ばせて(１)</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/10/14</TD><TD>12KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B><BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/concerto_3.html">通り雨（コンチェルトをもう一度・シリーズ）</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/9/23</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>高３になった雅たち。中間試験が近づく中、雅が隆一に勉強を教えるのだが？<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/itagaki.html">美少女指揮官ジュン＝イタガキ</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/9/23</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>イタガキ艦長が戦艦さざなみへ帰還する途上に事故発生。クルーは転送で救出を試みた。<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/concerto_1.html">コンチェルトをもう一度</a></B></TD><TD><B><A href="mailto:yaji@mxv.mesh.ne.jp">矢治浩平</a></B> さん (<A href="http://www2k.biglobe.ne.jp/~yaji/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>1998/9/20</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>突然女になった桐生雅章。彼は、桐生雅（みやび）として女として生き続ける。でも、あくまで女らしくではなくて自分らしく振る舞う雅。文化祭でのライブ。早川隆一は、怪我をした雅の親友・優の代わりに雅キーボードの代役を頼む。アクシデントが発生し、雅のソロ。そのソロの音色を聞いて早川隆一は思った。「この音をいつか俺は聞いた」。それは死んだはずの雅章の音色。隆一の追求が始まった<BR><B>【コメント】 </B>なんかなつかしいなー。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/concerto/concerto_2.html">続・コンチェルトをもう一度</a></B></TD><TD><B>矢治浩平</B> さん </TD><TD>(イラストなし)</TD><TD>1998/9/20</TD><TD>38KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=yaji">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>学校のクリスマスコンサートに共演することになった雅と隆一。ふたりはひかれて行くが、雅の過去から素直になれない二人。雅は隆一への思いから、「自分らしさと女らしさ」の狭間にゆれる。・・・クリスマス・イブに奇跡がおこる。<BR><B>【コメント】 </B><BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B></TD></TR><TR><TD COLSPAN=6>【ジャンル】  <BR>【種別】 <BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.146.98.143) , Competence : -1 -->
</BODY></HTML>


