<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8">
<BASE HREF="../index.html">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="../library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="manage2@ran.cgi">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy01.html">ホーリーメイデンズ　第壱夜「夕闇からの挑戦者」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/4/21(金)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>茜色の公園。そこで出会ったのは…。<BR><B>【コメント】 </B>初めまして、流離太という者です。初めての投稿なので、色々と不安です。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan24.html">華代ちゃんシリーズ「絵日記」</A> <FONT SIZE="-1">(猫野　丸太丸さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>伝奇や都市伝説を織り込んだ新感覚の戦隊タイプＴＳ魔法少女アクションです。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 魔法少女 巫女 ボクっ娘</TD></TR></TABLE><BR><BR>『流離太』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy_2_01.html">ホーリーメイデンズ２　第壱灯「模造された少女」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2009/12/30(水)</TD><TD>59KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>学校に流れるカーブミラーの噂。戦いはまだ、終わってはいなかった……。<BR><B>【コメント】 </B>お久しぶりです（＾＾；）　完成していたのは去年の今頃だったのですが、しばらく置かせて……って、置かせすぎた?！<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="http://www.novels.jp/~ts/bbs/2ndbbs/bbs.cgi?action=html2&key=20060625222953&log=2006082917">痛快！魔法少女解剖図解</A> <FONT SIZE="-1">(長束さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おまたせ！　あの巫女たちが、永い夜から帰ってきました。<BR>
<b>【<a href="../novel/200604/21135117/holy_title.html">シリーズタイトルはこちら</a>】</b></TD></TR><TR><TD COLSPAN=6>【ジャンル】  アクション 伝奇 学園 友情 <BR>【種別】 コピー 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex53.html">ハンター・シリーズ「ジゴラがやってきた」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/11/26(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>突如、太古の眠りから覚めたジゴラ。人類に、なす術はないのか！？<BR><B>【コメント】 </B>ジゴラジゴラジゴラがやってきた♪　伊福部マーチと一緒にお召し上がりくださいませ♪<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200606/28222647/hatsuyuki.html">紅い初雪</A> <FONT SIZE="-1">(英雄さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ネタも良い感じですが、地の文の表現が凝っていて楽しい逸品です。<BR>
<a href="../novel/kayo_chan/title-ex.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ナンセンス童話 <BR>【種別】 変身<BR>【キーワード】 ハンター・シリーズ 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy10.html">ホーリーメイデンズ　最終夜「明日へ」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD><B>画</B>(<B>ＭＯＴＨＧＯ</B>さん)</TD><TD>2006/9/22(金)</TD><TD>45KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに蘇る、闇の化身「八岐大蛇」。手と手を繋ぎ、きらめけホーリーメイデンズ！<BR><B>【コメント】 </B>これまで読んでいただいた方々、運営委員会の皆様、本当にありがとうございます！<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200207/03224430/roromi_title.html">微妙存在ろろみ</A> <FONT SIZE="-1">(こうけいさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>堂々の完結編です。また一つ、少年少女文庫に名作シリーズが誕生しました。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy09.html">ホーリーメイデンズ　第九夜「黄泉比良坂の戦い」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/9/8(金)</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>メイデンズ対アヤカシ。大蛇復活は？　夏月の思いとは？　そして終里は救われるのか？<BR><B>【コメント】 </B>夏っちゃん、やっぱり影が薄いよ（ＴＴ）<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200511/06220214/shinyu.html">親友</A> <FONT SIZE="-1">(セルさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>ブラボー！　すっかり騙されました。敢えて何も言いません。是非、ご覧下さい!!<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy08.html">ホーリーメイデンズ　第八夜「暗黒の使者」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/8/16(水)</TD><TD>40KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>交錯する、少女達の思い。舞台は、いよいよ最終決戦へ。<BR><B>【コメント】 </B>なんか、私の書くキャラは黒いやつばかりだ（苦笑）<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200512/06000905/lightning.html">落雷</A> <FONT SIZE="-1">(バレットさん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さり気なく挿入されたネタに、作家さん同士の繋がりを感じます。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 恋愛 伝奇 学園 友情 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy07.html">ホーリーメイデンズ　第七夜「ダーク・メイデン」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/28(水)</TD><TD>35KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>ついに牙をむく終里。その時、春花は？<BR><B>【コメント】 </B>なんか、どんどん思っても見なかった方向へ……。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200307/27055454/mirra0.html">ミイラの呪い</A> <FONT SIZE="-1">(奄美平次さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>おぉ、第六夜が見事なミスリードになっていてGOODです！<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 恋愛 伝奇 学園 友情 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 メガネっ娘 着せ替え ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy06.html">ホーリーメイデンズ　第六夜「君はだぁれ？（後編）」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/22(木)</TD><TD>31KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>巻き起こる白組対赤組の対決に、アヤカシが……。<BR><B>【コメント】 </B>運動会があまり本編に関係ないという。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200605/05101055/nijiiro_title01.htm">青空の魔法</A> <FONT SIZE="-1">(きりか進ノ介さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>複雑な恋愛関係の行方がとても気になる今日この頃。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション ファンタジー 伝奇 <BR>【種別】 入れ替わり 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy05.html">ホーリーメイデンズ　第伍夜「君はだぁれ？（前編）」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/7(水)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>アヤカシを２人だけで退治しに行った冬雪と春花の運命は？<BR><B>【コメント】 </B>……と言っていますがほぼ一瞬で決着がつきます（笑）<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/extra/kayo_ex42.htm">ハンター・シリーズ「三身一対〜30番目の多重人格者〜」</A> <FONT SIZE="-1">(天欄さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>わりと後方支援型っぽい二人が、今回はメインで大活躍！<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 入れ替わり 可変 魔法 変身<BR>【キーワード】 魔法少女 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy04.html">ホーリーメイデンズ　第四夜「狙われた学校」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/6/1(木)</TD><TD>24KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>術が使えないことに悩む冬雪。そんな中、謎の少女が……。<BR><B>【コメント】 </B>今回でひとまずレギュラーは全員集合です♪<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/200604/22210708/maple01.htm">めいぷる！ ─ザ・インセクト─</A> <FONT SIZE="-1">(Ｋ・伊藤さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いよいよ見えてくる黒幕の影。てっきり『彼』が黒幕だとばかり……（苦笑）。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/kayo_chan/extra/kayo_ex41.htm">華代ちゃんシリーズ番外編「こちょうのゆめ」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/22(月)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>穏やかな陽気の公園。そこで見る夢は……。<BR><B>【コメント】 </B>これ、本当に公園で思いついたネタです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>さすがの華代ちゃんも、これは初体験だったようで……？<BR>
<b><a href="novel/kayo_chan/title-ex.htm">【華代ちゃんシリーズ番外編タイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 入れ替わり 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy03.html">ホーリーメイデンズ　第参夜「怪しい転校生」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/14(日)</TD><TD>18KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>冬雪のクラスに来た転校生は…。<BR><B>【コメント】 </B>転校生が来るときってわくわくしますよね。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan95.html">華代ちゃんシリーズ 「贈り物」</A> <FONT SIZE="-1">(鈴忌 紫さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>いよいよ美少女戦士がそろい踏み？　しかも最後の戦士は……。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 可変 憑依 魔法 変身<BR>【キーワード】 魔法少女 オレっ娘 巫女 ボクっ娘 異形</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy02.html">ホーリーメイデンズ　第弐夜「ひとりぼっちの女の子」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/5/2(火)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>冬雪が見た紅い服の少女の正体は…。<BR><B>【コメント】 </B>都市伝説といったら勿論この娘。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan26.html">華代ちゃんシリーズ「先輩のすきなタイプ」</A> <FONT SIZE="-1">(もと(ＭＯＴＯ)さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>両親でお約束を押さえつつ、都市伝説で新しい風を吹き込んでます。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 可変 魔法 変身<BR>【キーワード】 鏡 オレっ娘 脳天気な両親 強制 魔法少女 メガネっ娘 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="novel/200604/21135117/holy01.html">ホーリーメイデンズ　第壱夜「夕闇からの挑戦者」</a></B></TD><TD><B><A href="mailto:leoobake@hotmail.com">流離太</a></B> さん </TD><TD>(イラストなし)</TD><TD>2006/4/21(金)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=rurita">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>茜色の公園。そこで出会ったのは…。<BR><B>【コメント】 </B>初めまして、流離太という者です。初めての投稿なので、色々と不安です。<BR><B>【流離太 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan24.html">華代ちゃんシリーズ「絵日記」</A> <FONT SIZE="-1">(猫野　丸太丸さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>伝奇や都市伝説を織り込んだ新感覚の戦隊タイプＴＳ魔法少女アクションです。<BR>
<a href="../novel/200604/21135117/holy_title.html"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アクション 伝奇 学園 <BR>【種別】 魔法 変身<BR>【キーワード】 魔法少女 巫女 ボクっ娘</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="../library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(52.87.253.202) , Competence : -1 -->
</BODY></HTML>


