<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=Shift_JIS">
<BASE HREF="http://ts.novels.jp/">
<TITLE>■　ランダムサーチ　■ -- http://ts.novels.jp/cgi-bin/manage2.cgi</TITLE>
</HEAD>
<BODY  BGCOLOR="#EEEEEE">
<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>
<DIV ALIGN=center><H2>■　ランダムサーチ　■</H2></DIV>今回のランダム検索はこれが選ばれました。　(<A HREF="http://ts.novels.jp/cgi-bin/manage2.cgi?ran">選び直す</A>)
 <BR><BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan45.html">華代ちゃんシリーズ 「ナイン」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/2/24</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>甲子園大会地区予選三回戦。第一シード南西高校に、暁仙高校が挑む。息詰まる熱戦が続いた。はたして奇跡は起こるのか？<BR><B>【コメント】 </B>疲れました。華代ちゃん、なかなか出てこないし。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これまた凝った「華代ちゃん」ものです。中盤まで全く華代ちゃんものに見えない（スポーツ物にみえる）のがミソです。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR>『水谷秋夫』さんのその他の著作<BR><BR><TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200403/27214253/entotsu.html">煙突のある町</a></B></TD><TD><B>水谷秋夫</B> さん (<A href="http://oikose.at.webry.info/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2012/11/2(金)</TD><TD>22KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>仕事一筋の男がいた。定年後、彼の職場だった工場は、不況の中で売却整理されることになった。工場の象徴だった巨大煙突が消えた翌朝、彼は亡くなった老妻の姿になっていた。<BR><B>【コメント】 </B>以前、「<b><a href="./novel/200403/27214253/chat_over_tea.htm">茶飲み話</a></b>」という婆さんの話を書きました。今度は爺さんの話です。<BR><B>【水谷秋夫 さんのオススメ作品】</B> <A HREF="./novel/concerto/concerto_2.html">続・コンチェルトをもう一度</A> <FONT SIZE="-1">(矢治浩平さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>誰にも責めることの出来ないほどの、真面目で真剣な人生。「煙突のある町」に懸けた男の生涯は、はたして誰に何を残すのでしょう。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 爺さん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan105.html">華代ちゃん『修羅場』</a></B></TD><TD><B>水谷秋夫</B> さん (<A href="http://oikose.at.webry.info/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2006/6/9(金)</TD><TD>4KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>できました<BR><B>【コメント】 </B>何年ぶりかの投稿で何を書いているのやら<BR><B>【水谷秋夫 さんのオススメ作品】</B> <A HREF="../novel/kayo_chan/kayo_chan02.html">華代ちゃん『正座』</A> <FONT SIZE="-1">(真城　悠さん作)</FONT></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>水谷さんのあらすじが<b>全てを</b>物語っていますっ（笑）。久しぶりに一撃必殺（？）な華代ちゃんを見たような……（笑）<BR>
<b><a href="../novel/kayo_chan/title06.html">【シリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 恋愛 <BR>【種別】 変身<BR>【キーワード】 強制 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan87.htm">華代ちゃんシリーズ「微動戦士アンダム DEED」</a></B></TD><TD><B>水谷秋夫</B> さん (<A href="http://oikose.at.webry.info/">Homepage</a>)</TD><TD>(イラストなし)</TD><TD>2004/11/5(金)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>アニメオタク氏が人気ロボットアニメを、独り声高に批判しながら鑑賞していた。そこに華代ちゃんが現れた。<BR><B>【コメント】 </B>むしろ華代ちゃんのほうがアニメオタクのような。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>そんなに二匹目のドジョウを狙いたいのかっ！？　あんたたちはああっ！！（←問題発言）<BR>
<b><a href="../novel/kayo_chan/index.html">【華代ちゃんシリーズタイトルはこちら】</a></b></TD></TR><TR><TD COLSPAN=6>【ジャンル】 アニメ <BR>【種別】 変身<BR>【キーワード】 強制 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/corrector/foster15.htm">次元管理人フォスター・シリーズ「ヘブン・アース・アンド――」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2004/5/9(日)</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=foster">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>戦国時代最大の激戦のひとつに数えられる川中島の合戦、その火蓋が切って落とされた･･･。<BR><B>【コメント】 </B>タイムパトロールに歴史物はつきものです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>毎度お騒がせのフォスターが、今度は戦国時代に登場だ！？<BR>
<a href="./novel/corrector/title.htm"><strong>【シリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 歴史 <BR>【種別】 変身<BR>【キーワード】 フォスター 強制</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200403/27214253/chat_over_tea.htm">茶飲み話</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2004/3/27(土)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>独り暮らしの老婆が、茶飲み話で自分の来し方を顧みる。<BR><B>【コメント】 </B>生きていれば年を取ります。わたしも、あなたも、TS少女も。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>お婆ちゃん萌えな方必見！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 <BR>【種別】 変身<BR>【キーワード】 婆さん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan79.html">華代ちゃんシリーズ「地には平和を」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2003/4/29(火)</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>某大国に蹂躙された独裁国家。帰らぬ夫と息子を待つ女。そこへ華代ちゃんが現れた。<BR><B>【コメント】 </B>書いたのは４月１６日。その数日後にはすっかり古くなってしまいました。これだから時事ネタは嫌いです。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>華代ちゃんはインターナショナルなトラブルメーカーかもしれません。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 戦記 <BR>【種別】 変身<BR>【キーワード】 強制 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel10.html">D.A.：愛していた</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2003/1/11(土)</TD><TD>46KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>鏡桐香に依頼されて仕事を始めた病院で、ダーティーエンジェル・白帆真澄はかつて自分が男性だった頃の恋人に再会した。<BR><B>【コメント】 </B>題名と冒頭とラストは声に出して読めない日本語です。決して音読なさらぬよう、お願いいたします。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>かつての、頭の片隅に押し込んだ記憶が蘇る。その時、“ダーティーエンジェル”は何を思ったのだろうか――<BR>
<B><A HREF="./share_world.html#d_a_">【ダーティーエンジェル　シェアワールド詳細はこちら】</A></B></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 恋愛 <BR>【種別】 変身 医術 薬品<BR>【キーワード】 ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/extra/kayo_ex11.htm">華代ちゃんシリーズ番外編 「ハンター科学班」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2002/10/23(水)</TD><TD>23KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真城華代の能力を解き明かさんと、ハンター科学班が発足した。<BR><B>【コメント】 </B>無理を承知で、華代ちゃんを科学してみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>「理屈と膏薬はどこにでもつく」と言いますが、はてさて……<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 その他（科学） <BR>【種別】 変身<BR>【キーワード】 華代ちゃん番外編</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200206/09210113/wedding.htm">お嫁さんになりたい</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2002/9/9(月)</TD><TD>9KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「大きくなったらお嫁さんになりたい」と言う男の子がいた。彼の希望は適えられるのか。<BR><B>【コメント】 </B>小ネタです。一応、ＳＦのつもり。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これこそ短編の極まりといったも過言ではない作品。皆さん、こんなこと考えても今の科学では解決できませんよ？</TD></TR><TR><TD COLSPAN=6>【ジャンル】 近未来ＳＦ <BR>【種別】 変身 医術<BR>【キーワード】 花嫁</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200206/09210113/masashi_and_makoto.htm">政史と真琴－六年間の軌跡－</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD><B>画</B>(<B>原田聖也</B>さん)</TD><TD>2002/6/9(日)</TD><TD>109KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「八歳まで男の子だった。鬼を見たせいで女になってしまった」と主張する少女・真琴とその友人・政史の小学二年から中学二年までの六年間を描く<BR><B>【コメント】 </B>日韓ワールドカップ共催記念サッカー作品。でもラストシーンは２０００年八月。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>真琴が男の子のようにふるまい、男の子に対抗することにこだわる理由とは？　政史と真琴、二人の成長を丁寧に描いた水谷さんの力作です。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 スポーツ 学園 恋愛 <BR>【種別】 神秘 変身<BR>【キーワード】 オレっ娘</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan60.html">華代ちゃんシリーズ 「苦悩する漫画家」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD><B>画</B>(<B>原田聖也</B>さん)</TD><TD>2002/2/19(火)</TD><TD>3KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>悩める漫画家に華代ちゃんが授けたある秘訣とは？<BR><B>【コメント】 </B>水谷さんの作品に挿し絵を描かせていただきました。（原田）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>うううっ……華代ちゃんストレート過ぎ（笑）。<BR>
水谷さんのお話に、原田さんのキュートな挿絵で二度美味しい作品です。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 現代 職業 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200111/27020302/nyohen.html">女変病の仮面</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2001/11/27(火)</TD><TD>10KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>時は中世。世の男達を女に変える女変病が蔓延していた。そこで、プロスペロ公は千人の貴族とともに城塞に籠もり、男ばかりの壮麗な仮面舞踏会を催した。<BR>
そして事件が起きた。<BR><B>【コメント】 </B>エドガー・アラン・ポーの傑作ゴシックホラー「赤死病の仮面」をＴＳ仕立てにしてみました。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>作品中に漂う怪しげな空気。原作の雰囲気が生きているこの作品、どうぞお楽しみ下さい。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ホラー 時代 二次創作 <BR>【種別】 変身<BR>【キーワード】 原典：エドガー・アラン・ポー「赤死病の仮面」</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan55.html">華代ちゃんシリーズ 「鋼鉄の肉体」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2001/11/12(月)</TD><TD>6KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>黙々とウェートトレーニングに取り組む円盤投げ選手。彼に少女が示した、肉体を効率よく鍛える方法とは？<BR><B>【コメント】 </B>会心作です(^^;<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>皆さん、身体鍛えてますか？　不条理これ極まれりの華代ちゃん流トレーニング方法とは……？<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 スポーツ 不条理 <BR>【種別】 変身<BR>【キーワード】 強制 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200010/20224827/kuzureru.htm">くずれる</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2001/5/9(水)</TD><TD>13KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>地下室で大学サークルの新人歓迎パーティーを行う男達。そこに突然の停電。暗闇のなか、惨劇の幕が上がる。<BR><B>【コメント】 </B>ホラーなんですけど、誰か怖がってくれませんか。誰です、うらやましいなんて言っている人は。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>　舞台は大学サークルの新人歓迎パーティ。そしてきっかけは些細なことだった。<BR>
　あなたの耳にも聞こえませんでしたか？　カチリ、という音が……。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 ホラー <BR>【種別】 変身<BR>【キーワード】 集団</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel_p01.html">D.A.パロ：　Dr.　セパルカー、デパートに行く</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/11/13(月)</TD><TD>11KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>そのまんま、タイトルの通りです<BR><B>【コメント】 </B>馬鹿馬鹿しい話を急に書きたくなりました。力を抜いてお読み下さい。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>プライドの高い男（女）の人って、ついからかいたくなっちゃうんですよね。<BR>
死を呼ぶ白い医師が、またまた突貫されてます！　だって、美白だもんなあ……</TD></TR><TR><TD COLSPAN=6>【ジャンル】 コメディ <BR>【種別】 変身 医術 薬品<BR>【キーワード】 ショッピング パロディー ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/200010/20224827/mizuho.html">みづほの駒音</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/10/20(金)</TD><TD>91KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>少年として育てられた美津夫は、中学一年の時、医師に女性であると告げられる。みづほと名を変え、やがてプロ棋士を目指していく彼女の、恋と友情と家族を描く。<BR><B>【コメント】 </B>長いので暇なときにお読みください。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B><B><I>君は君のままでいいんだ、って言うのなら、なにがぼくらしいんだろう</I></B> ～本文より～<BR>
これは、間違いなく傑作。ジェンダー物としても、青春物としても将棋物としても楽しめます！　十三年間、男として生きてきた少年が、自分の本当の性別は女だと告げられたとしたら──。「神田みづほ」の場合がここに描かれています。いやー、読み応えがあって、どこぞの小説賞の受賞作だと言われても全く違和感ないです。しかも読めば将棋業界の仕組みにも詳しくなれて一石二鳥！</TD></TR><TR><TD COLSPAN=6>【ジャンル】 青春 恋愛 <BR>【種別】 変身 仮性半陰陽<BR>【キーワード】 ボクっ娘 女友達</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel06.html">D.A.：医者はどこだ</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/7/2</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>「今回ばかりは私一人じゃ駄目。とびきり優秀な外科医がいないと」　そこへ現れたのは、髪も肌も服も白ずくめの女医だった。<BR><B>【コメント】 </B>セパルカーセンセ、大活躍。二人の因縁も明らかに（？）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>死を操る白き医師、ドクター・セパルカー登場!! 独自の展開をみせるシェアワールド「ダーティー・エンジェル」にまたひとつ新たな物語が加わりました。すでに<a href="http://www4.plala.or.jp/parallel/d_clinic/index.html">公式ページ</a>では大人気になってる突貫されキャラの「センセ」がストーリーに初登場なのです。初登場だからシリアスに決めています!!（でも、やっぱりちょっと突貫されました）</TD></TR><TR><TD COLSPAN=6>【ジャンル】 医療ドラマ <BR>【種別】 変身 医術 薬品<BR>【キーワード】 ナース ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel03.html">D.A.：あなたは死なせない</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/3/5</TD><TD>14KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>不治の病に冒された少年を看護するダーティーエンジェル。彼女が示した起死回生の治療法とは？<BR><B>【コメント】 </B>ダーティーエンジェルシリーズ第３弾、豪邸編。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>"こちらは、ダーティーエンジェルの「エンジェル」的側面を感じる作品です。Ｄエンジェルの最後のセリフがしびれます。皆さんもぜひ、しびれてみて下さい。<BR>【お知らせ】 シリーズ執筆者を募集中です。作品の書き方は、<a href="./novel/dirty/angel00.html">こちらを参照して下さい。</a>"</TD></TR><TR><TD COLSPAN=6>【ジャンル】 医療 <BR>【種別】 変身 薬品<BR>【キーワード】 ナース ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel02.html">D.A.：雪山に血の滴</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/3/5</TD><TD>7KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>降りしきる雪のため、山小屋に閉じこめられた銀行強盗と看護婦。看護婦の提案した取り引きは思わぬ結末を呼んだ。<BR><B>【コメント】 </B>ダーティーエンジェルシリーズ第２弾、雪山編。強盗さんのその後、知りたいですか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>"ある意味元ネタともいえる手塚先生の「ブラックジャック」的な風味が漂う回ですね。<BR>【お知らせ】 シリーズ執筆者を募集中です。作品の書き方は、、<a href="./novel/dirty/angel00.html">こちらを参照して下さい。</a>"</TD></TR><TR><TD COLSPAN=6>【ジャンル】 医療 <BR>【種別】 変身 薬品<BR>【キーワード】 ナース ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/dirty/angel01.html">D.A.：ダーティーエンジェル誕生</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/03/05</TD><TD>5KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=d_angel">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>交通事故で救急病院に運び込まれた男。彼は闇看護婦、「ダーティーエンジェル」として、復活する。<BR><B>【コメント】 </B>掲示板２に連載していたダーティーエンジェルシリーズ。シェアワールドとして少年少女文庫に登場。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>"闇看護婦ダーティーエンジェル誕生編です。<BR>【お知らせ】 シリーズ執筆者を募集中です。作品の書き方は、<a href="./novel/dirty/angel00.html">こちらを参照して下さい。</a>"</TD></TR><TR><TD COLSPAN=6>【ジャンル】 医療 <BR>【種別】 変身 薬品<BR>【キーワード】 ナース ダーティーエンジェル</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan45.html">華代ちゃんシリーズ 「ナイン」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>2000/2/24</TD><TD>37KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>甲子園大会地区予選三回戦。第一シード南西高校に、暁仙高校が挑む。息詰まる熱戦が続いた。はたして奇跡は起こるのか？<BR><B>【コメント】 </B>疲れました。華代ちゃん、なかなか出てこないし。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>これまた凝った「華代ちゃん」ものです。中盤まで全く華代ちゃんものに見えない（スポーツ物にみえる）のがミソです。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/the_fate.html">誠司の過去、耀子の未来</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/11/23</TD><TD>30KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=mizutani_akio">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>誠司は交通事故で死ぬたびに時間を遡っていた。その度に自分の運命を変えようとするが果たせない。しかし、最後に遡ったとき、誠司は妻の耀子になっていた。<BR><B>【コメント】 </B>オリジナル作品をお送りするのは初めてになります。よろしく。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>SFというジャンルというのは、上手くはまったときにラブロマンスの要素と非常に高い親和性を示すようです。また、SFという形ではじめて表現できるペーソスというものがあります。この作品などはまさにその見本と言ってもいいのではないでしょうか。性別変化の要素を別にしても充分に通用する実に完成度の高いストーリーです。</TD></TR><TR><TD COLSPAN=6>【ジャンル】 SF <BR>【種別】 人格転移<BR>【キーワード】 </TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan44.html">華代ちゃんシリーズ 「ウニ」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/11/18</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>浜の磯辺の観光地。ある男がウニの瓶詰めを見つめていた。そこへ華代ちゃんが現れて。<BR><B>【コメント】 </B>かつてこれほど食にこだわったＴＳ作品があっただろうか？<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>食にこだわった…というか「ウニ」にこだわった作品としても楽しめますが、同時にコスプレネタの斬新さにも度肝を抜かれます。これはコスプレの新境地でしょう！<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/extra/kayo_ex04.html">華代ちゃんシリーズ番外編 「しろつめ草の花冠」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/11/7</TD><TD>15KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>隣同士で兄妹のように仲の良い少年と少女がいました。しかし、少女の一途な想いは報われずに終わります。<BR><B>【コメント】 </B>おさな心の悲恋物語です。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>なんとっっ！ 「天災のような存在」などと恐怖されてきた(笑)華代ちゃんに、こんな淡せつない過去があったとは！ 「番外編」ならではの作品ですね。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 恋愛 <BR>【種別】 変身<BR>【キーワード】 華代ちゃん 番外編</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan42.html">華代ちゃんシリーズ 「代官と越後屋」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/10/13</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>真夜中、代官と越後屋は悪巧みをしていた。そこへ華代ちゃんが現れて<BR><B>【コメント】 </B>時代劇です。おなじみの設定と決まり文句の後は、お約束の結末になだれ込みます。<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>華代ちゃんを時代劇に登場させるという手もあったんですねえ。やられました。というか、時代物自体、文庫初登場のような気がします。最後の「あーれーっ」もいい味だしてますね。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 時代物 <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan41.html">華代ちゃんシリーズ 「憂鬱なる月曜日」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/10/7</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>休日を終えた月曜日のサラリーマンは憂鬱だ。休んだ気がしない。思わず、何ヶ月かずっと休めたらいいな、と夢想する。そこへ華代ちゃんが現れた。<BR><B>【コメント】 </B>今回はコレがコレやから（って、これじゃわからん）<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>今回の主人公（犠牲者ともいう）の悩みには共感を覚える人も多いんじゃないでしょうか。月曜日がユウウツだぁ、などとぼやいてるアナタ。ご用心、ご用心。（この推薦文ノリが変ですね。ま、いいでしょう。それと●●はコスプレとは違うような…。^^;）<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<TABLE BORDER=1 WIDTH="100%"><TR><TD><B><A href="./novel/kayo_chan/kayo_chan38.html">華代ちゃんシリーズ 「水泳嫌い」</a></B></TD><TD><B>水谷秋夫</B> さん </TD><TD>(イラストなし)</TD><TD>1999/10/2</TD><TD>8KB</TD><TD BGCOLOR="#E0D0C0"><A href="http://www.novels.jp/~ts/kansou/bbs.cgi?log=kayo_chan">感想</a></TD></TR><TR><TD COLSPAN=6><B>【あらすじ】 </B>水泳嫌いの少年が、体育の時間の直前、ひとり男子更衣室で佇んでいた。そこへ……<BR><B>【コメント】 </B>ネタは、と言えば、アレです<BR></TD></TR><TR><TD COLSPAN=6><B>【推薦文】 </B>水谷さんの意見「（華代ちゃんシリーズでは）女性になる理由が些細であればあるほどいいと思う」というのはなるほど一つの考え方だと感心しました。「アレ」に困惑してしまう新米女の子というのも良いものです(^^;。<BR>
<a href="./novel/kayo_chan/index.html"><strong>【華代ちゃんシリーズタイトルはこちら】</strong></a></TD></TR><TR><TD COLSPAN=6>【ジャンル】 ショートショート <BR>【種別】 変身<BR>【キーワード】 華代ちゃん</TD></TR></TABLE><BR><BR><BR>

<FONT size=-1><A href="http://ts.novels.jp/library.html">戻る</A></FONT>

<!-- 少年少女文庫用管理CGI manage2.cgi v2.4.3 2005/04/22 22:09:00 JST 作:kou -->
<!-- Login User : Guest(54.81.68.240) , Competence : -1 -->
</BODY></HTML>


